'use strict';
const crypto=require('crypto');const enterprise=require('../lib/enterprise-store');const webhooks=require('../lib/webhooks');const SYSTEM={email:'system@nutretium.local',role:'system'};
async function queue(templateKey,recipient,variables,source){if(!templateKey||!recipient)return false;const id=crypto.randomUUID();await enterprise.save('notification-jobs',{id,templateKey,recipient,variables:variables||{},status:'queued',source:source||'automation'},SYSTEM,{id,create:true,reason:'automation'});return true;}
async function marketingAllowed(email){const id=`${String(email||'').toLowerCase()}:marketing`,record=await enterprise.get('consent-settings',id).catch(()=>null);return record?.status==='granted'}
async function lowStockAlerts(){const items=await enterprise.list('inventory',{limit:1000});let queued=0;const recipient=process.env.INVENTORY_NOTIFICATION_EMAIL||process.env.ORDER_NOTIFICATION_EMAIL;for(const item of items){const point=Number(item.reorderPoint);if(!Number.isFinite(point)||Number(item.onHand||0)-Number(item.reserved||0)>point)continue;if(item.lowStockAlertedAt&&Date.now()-Date.parse(item.lowStockAlertedAt)<24*3600*1000)continue;if(recipient&&await queue('low-stock',recipient,{sku:item.sku,warehouseId:item.warehouseId,available:Number(item.onHand||0)-Number(item.reserved||0),reorderQty:item.reorderQty||0},'low-stock'))queued++;await enterprise.save('inventory',{...item,lowStockAlertedAt:new Date().toISOString()},SYSTEM,{id:item.id,reason:'low-stock-check'});}return queued;}
async function backInStock(){const alerts=(await enterprise.list('stock-alerts',{limit:1000})).filter(a=>a.status==='waiting'),inventory=await enterprise.list('inventory',{limit:1000});let queued=0;for(const alert of alerts){const available=inventory.filter(i=>i.sku===alert.sku).reduce((n,i)=>n+Math.max(0,Number(i.onHand||0)-Number(i.reserved||0)),0);if(available<=0)continue;if(await queue('back-in-stock',alert.customerEmail,{sku:alert.sku,productId:alert.productId,available},'back-in-stock'))queued++;await enterprise.save('stock-alerts',{...alert,status:'sent',sentAt:new Date().toISOString()},SYSTEM,{id:alert.id,reason:'back-in-stock'});}return queued;}
async function abandonedCarts(){const carts=(await enterprise.list('saved-carts',{limit:1000})).filter(c=>String(c.id||'').startsWith('active:')&&c.status==='active');let queued=0;for(const cart of carts){const last=Date.parse(cart.lastActivityAt||cart.updatedAt||cart.createdAt||0);if(!last||Date.now()-last<2*3600*1000)continue;if(cart.recoverySentAt)continue;const allowed=await marketingAllowed(cart.customerEmail);if(allowed&&await queue('abandoned-cart',cart.customerEmail,{cartId:cart.id,items:cart.items||[]},'abandoned-cart'))queued++;await enterprise.save('saved-carts',{...cart,status:'abandoned',recoverySentAt:allowed?new Date().toISOString():null,recoverySkippedReason:allowed?null:'marketing-consent-missing'},SYSTEM,{id:cart.id,reason:'abandoned-cart-check'});}return queued;}
async function scheduledRules(){const rules=(await enterprise.list('automation-rules',{limit:500})).filter(r=>r.status==='active'&&r.event==='schedule.daily');let executed=0;for(const rule of rules){for(const action of Array.isArray(rule.actions)?rule.actions:[]){if(action.type==='notification'&&action.templateKey&&action.recipient){await queue(action.templateKey,action.recipient,action.variables||{},`rule:${rule.key}`);executed++;}else if(action.type==='webhook'&&action.event){await webhooks.emit(action.event,{rule:rule.key,scheduledAt:new Date().toISOString(),payload:action.payload||{}});executed++;}}}return executed;}
async function subscriptionReminders(){const subs=(await enterprise.list('subscriptions',{limit:1000})).filter(s=>s.status==='active'&&s.nextAt&&Date.parse(s.nextAt)<=Date.now()+3*24*3600*1000&&Date.parse(s.nextAt)>=Date.now()-24*3600*1000);let queued=0;for(const sub of subs){if(sub.reminderFor===sub.nextAt)continue;if(await queue('subscription-reminder',sub.customerEmail,{subscriptionId:sub.id,nextAt:sub.nextAt},'subscription-reminder'))queued++;await enterprise.save('subscriptions',{...sub,reminderFor:sub.nextAt},SYSTEM,{id:sub.id,reason:'subscription-reminder'});}return queued;}
exports.handler=async function(){try{const[lowStock,restock,abandoned,rules,subscriptions]=await Promise.all([lowStockAlerts(),backInStock(),abandonedCarts(),scheduledRules(),subscriptionReminders()]);return{statusCode:200,body:JSON.stringify({ok:true,lowStock,restock,abandoned,rules,subscriptions})};}catch(error){console.error('[automation-worker]',error);return{statusCode:500,body:JSON.stringify({ok:false,error:'automation_worker_failed'})};}};
exports._test={queue,marketingAllowed};
