'use strict';
const {NUTRETIUM_PRODUCTS}=require('../../products-data.js');
const {exigeAdmin}=require('../lib/admin');
const {cabecerasCORS}=require('../lib/cors');
const content=require('../lib/product-content');
const enterprise=require('../lib/enterprise-store');
const CORS=cabecerasCORS('GET, OPTIONS');
function present(v){return Array.isArray(v)?v.length>0:Boolean(String(v??'').trim())}
function missingBase(product){const missing=[];if(!present(product.image))missing.push('foto');if(!present(product.brand))missing.push('marca');if(!present(product.code))missing.push('referencia');if(!present(product.category))missing.push('categoria');if(!Number.isFinite(Number(product.price))||Number(product.price)<=0)missing.push('precio');if(product.stock===null||product.stock===undefined)missing.push('stock-no-validado');return missing}
function quality(product,advanced,complianceApproved){const checks={foto:present(product.image),marca:present(product.brand),referencia:present(product.code),categoria:present(product.category),precio:Number.isFinite(Number(product.price))&&Number(product.price)>0,stock:typeof product.stock==='number',descripcion:present(advanced?.description||product.description),formato:present(advanced?.format||advanced?.size),ean:present(advanced?.ean),ingredientes:present(advanced?.ingredients),nutricion:present(advanced?.nutrition),alergenos:present(advanced?.allergens),uso:present(advanced?.instructions),advertencias:present(advanced?.warnings),seo:present(advanced?.seoTitle)&&present(advanced?.metaDescription),galeria:present(advanced?.gallery),aprobacionPim:advanced?.status==='approved',compliance:Boolean(complianceApproved)};const keys=Object.keys(checks),passed=keys.filter(k=>checks[k]).length;return{score:Math.round(passed/keys.length*100),checks,missing:keys.filter(k=>!checks[k])}}
exports.handler=async function(event){
 if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:CORS,body:''};if(event.httpMethod!=='GET')return{statusCode:405,headers:CORS,body:JSON.stringify({error:'Method Not Allowed'})};const auth=await exigeAdmin(event);if(!auth.ok)return{statusCode:auth.statusCode,headers:CORS,body:JSON.stringify({error:auth.error})};
 const active=(NUTRETIUM_PRODUCTS||[]).filter(p=>p&&p.active!==false);const [advancedRows,complianceRows]=await Promise.all([content.list().catch(()=>[]),enterprise.list('product-compliance',{limit:1000}).catch(()=>[])]);const advancedMap=new Map(advancedRows.map(r=>[String(r.code||'').toUpperCase(),r]));const complianceMap=new Map();for(const row of complianceRows){if(row.status==='approved'&&row.evidenceComplete===true&&Array.isArray(row.evidence)&&row.evidence.length)complianceMap.set(String(row.sku||'').toUpperCase(),true)}
 const issues=active.map(product=>{const code=String(product.code||'').toUpperCase(),q=quality(product,advancedMap.get(code),complianceMap.get(code));return{id:product.id,code:product.code||'',name:product.name||'',category:product.category||'',score:q.score,missing:q.missing,checks:q.checks}}).filter(i=>i.missing.length);
 const scores=active.map(p=>{const code=String(p.code||'').toUpperCase();return quality(p,advancedMap.get(code),complianceMap.get(code)).score});const stats={active:active.length,withImage:active.filter(p=>present(p.image)).length,withDescription:active.filter(p=>present(advancedMap.get(String(p.code||'').toUpperCase())?.description||p.description)).length,withBrand:active.filter(p=>present(p.brand)).length,knownStock:active.filter(p=>typeof p.stock==='number').length,outOfStock:active.filter(p=>typeof p.stock==='number'&&p.stock<=0).length,featured:active.filter(p=>p.featured===true).length,withReviews:active.filter(p=>Number(p.reviews||0)>0).length,incomplete:issues.length,approvedPim:advancedRows.filter(r=>r.status==='approved').length,complianceApproved:active.filter(p=>complianceMap.get(String(p.code||'').toUpperCase())).length,averageQuality:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,quality90:scores.filter(s=>s>=90).length};const issueCounts={};issues.forEach(item=>item.missing.forEach(key=>{issueCounts[key]=(issueCounts[key]||0)+1;}));return{statusCode:200,headers:{...CORS,'Cache-Control':'no-store'},body:JSON.stringify({stats,issueCounts,issues:issues.sort((a,b)=>a.score-b.score).slice(0,150),generatedAt:new Date().toISOString()})};
};
exports._test={quality,missingBase};
