'use strict';
const {requireStaff}=require('../lib/staff');
const enterprise=require('../lib/enterprise-store');
const {getBlobStore}=require('../lib/blob-store');
const {cabecerasCORS}=require('../lib/cors');
const CORS=cabecerasCORS('GET, OPTIONS');
const response=(s,b)=>({statusCode:s,headers:{...CORS,'Cache-Control':'no-store'},body:JSON.stringify(b)});
function orderTime(o){const raw=o.createdAt||o.receivedAt||o.updatedAt||'';const n=Date.parse(raw);return Number.isFinite(n)?n:0}
function summarize(rows,costMap){let revenue=0,cost=0,items=0;const unknown=new Set();for(const o of rows){revenue+=Math.round(Number(o.amount||0)*100);for(const line of o.items||[]){const qty=Number(line.qty||line.quantity||0);items+=qty;const sku=String(line.code||line.sku||'');const c=costMap.get(sku);if(Number.isFinite(c))cost+=c*qty;else if(sku)unknown.add(sku)}}const margin=revenue-cost;return{orders:rows.length,items,revenueCents:revenue,knownCostCents:cost,grossProfitKnownCostCents:margin,grossMarginKnownCostPct:revenue&&unknown.size===0?Math.round(margin/revenue*10000)/100:null,unknownCostSkus:[...unknown]}}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:CORS,body:''};if(event.httpMethod!=='GET')return response(405,{error:'Method Not Allowed'});const auth=await requireStaff(event,'analytics.read');if(!auth.ok)return response(auth.statusCode,{error:auth.error});try{const ordersStore=getBlobStore('redsys-orders');if(!ordersStore)return response(503,{error:'Pedidos no disponibles.'});const list=await ordersStore.list();const keys=(list.blobs||[]).slice(-1000).map(b=>b.key),orders=(await Promise.all(keys.map(k=>ordersStore.get(k,{type:'json',consistency:'strong'}).catch(()=>null)))).filter(o=>o&&o.status==='PAID');const costs=await enterprise.list('product-costs',{limit:1000}),costMap=new Map(costs.map(c=>[String(c.sku),Math.round(Number((c.landedCost??c.unitCost)??0)*100)])),now=Date.now(),periods={last24h:summarize(orders.filter(o=>orderTime(o)>=now-24*3600*1000),costMap),last7d:summarize(orders.filter(o=>orderTime(o)>=now-7*24*3600*1000),costMap),last30d:summarize(orders.filter(o=>orderTime(o)>=now-30*24*3600*1000),costMap),stored:summarize(orders,costMap)},base=periods.stored;const inventory=await enterprise.list('inventory',{limit:1000}),available=inventory.reduce((n,i)=>n+Math.max(0,Number(i.onHand||0)-Number(i.reserved||0)),0),returns=await enterprise.list('returns',{limit:1000}),shipments=await enterprise.list('shipments',{limit:1000});return response(200,{period:'stored-paid-orders-up-to-1000',...base,periods,inventoryAvailable:available,returnsOpen:returns.filter(r=>!['closed','rejected'].includes(r.status)).length,shipmentsOpen:shipments.filter(s=>!['delivered','returned','cancelled'].includes(s.status)).length,generatedAt:new Date().toISOString()})}catch(err){return response(500,{error:err.message})}};
exports._test={orderTime,summarize};