'use strict';
const crypto=require('crypto');const usuarios=require('../lib/usuarios');const {signJWT,secretConfigured}=require('../lib/jwt');const {roleFor}=require('../lib/staff');const {secretFor,verify:verifyTotp}=require('../lib/totp');const {cabecerasCORS}=require('../lib/cors');const {getBlobStore}=require('../lib/blob-store');const CORS=cabecerasCORS('POST, OPTIONS'),response=(s,b,h={})=>({statusCode:s,headers:{...CORS,'Cache-Control':'no-store',...h},body:JSON.stringify(b)});
function verifyPassword(password,stored){try{const[salt,hash]=String(stored||'').split(':'),attempt=crypto.pbkdf2Sync(password,salt,100000,64,'sha512').toString('hex'),a=Buffer.from(hash,'hex'),b=Buffer.from(attempt,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
function attemptStore(){return getBlobStore('staff-auth-attempts')}function attemptKey(email){return crypto.createHash('sha256').update(String(email||'').toLowerCase()).digest('hex')}
async function checkThrottle(email){const s=attemptStore();if(!s)return{ok:true};const now=Date.now(),r=await s.get(attemptKey(email),{type:'json'}).catch(()=>null);if(r&&Number(r.until)>now)return{ok:false,retryAfter:Math.ceil((Number(r.until)-now)/1000)};return{ok:true}}
async function failAttempt(email){const s=attemptStore();if(!s)return;const key=attemptKey(email),now=Date.now(),r=(await s.get(key,{type:'json'}).catch(()=>null))||{fails:0,first:now,until:0},inside=now-Number(r.first||0)<15*60*1000,fails=(inside?Number(r.fails||0):0)+1;await s.setJSON(key,{fails,first:inside?r.first:now,until:fails>=5?now+15*60*1000:0})}
async function clearAttempts(email){const s=attemptStore();if(s)await s.delete(attemptKey(email)).catch(()=>{})}
exports.handler=async event=>{if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:CORS,body:''};if(event.httpMethod!=='POST')return response(405,{error:'Method Not Allowed'});if(!secretConfigured())return response(503,{error:'Sesiones no disponibles.'});let body;try{body=JSON.parse(event.body||'{}')}catch{return response(400,{error:'JSON no válido.'})}const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||''),mfaCode=String(body.mfaCode||''),wait=await checkThrottle(email);if(!wait.ok)return response(429,{error:'Demasiados intentos. Prueba más tarde.'},{'Retry-After':String(wait.retryAfter)});const user=await usuarios.lee(email),role=roleFor(email);if(!user||role==='client'||!verifyPassword(password,user.passwordHash)){await failAttempt(email);return response(401,{error:'Credenciales incorrectas.'})}const secret=secretFor(email),requireMfa=String(process.env.REQUIRE_STAFF_MFA||'false').toLowerCase()==='true';if(requireMfa&&!secret)return response(503,{error:'MFA obligatorio pero esta cuenta no tiene TOTP configurado.'});if(secret&&!verifyTotp(secret,mfaCode)){await failAttempt(email);return response(401,{error:'Código MFA incorrecto.',mfaRequired:true})}await clearAttempts(email);const token=signJWT({sub:user.id,email,role,mfa:Boolean(secret),sv:Number(user.sessionVersion||0),exp:Math.floor(Date.now()/1000)+8*3600});return response(200,{user:{id:user.id,name:user.name,surname:user.surname,email:user.email,phone:user.phone,role,token,mfa:Boolean(secret)}})};
exports._test={verifyPassword,checkThrottle};
