(function(){'use strict';
const KEY='nutretium_user',CSRF_KEY='nutretium_admin_csrf',$=id=>document.getElementById(id);let overview=null,staff=[],editingEmail=null,restoreKey=null,restoreRequired=null,csrf=sessionStorage.getItem(CSRF_KEY)||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
function requestId(){if(globalThis.crypto?.randomUUID)return crypto.randomUUID();return`nt-${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`}
function secureHeaders(extra={}){return{'Content-Type':'application/json','x-nutretium-request':requestId(),...(csrf?{'x-nutretium-csrf':csrf}:{}),...extra}}
async function jsonFetch(url,options={}){const r=await fetch(url,options),d=await r.json().catch(()=>({}));return{r,d}}
async function gov(body){const{r,d}=await jsonFetch('/.netlify/functions/admin-governance',{method:'POST',headers:secureHeaders(),body:JSON.stringify(body)});if([401,403].includes(r.status))throw Object.assign(new Error(d.error||'Sin acceso'),{auth:true});if(!r.ok)throw new Error(d.error||'No se pudo completar la operación');return d}
async function restore(body){const{r,d}=await jsonFetch('/.netlify/functions/platform-restore',{method:'POST',headers:secureHeaders(),body:JSON.stringify(body)});if([401,403].includes(r.status))throw Object.assign(new Error(d.error||'Sin acceso'),{auth:true});if(!r.ok)throw new Error(d.error||'No se pudo preparar la restauración');return d}
async function exchange(token,user){const{r,d}=await jsonFetch('/.netlify/functions/admin-session',{method:'POST',headers:secureHeaders({Authorization:'Bearer '+token}),body:JSON.stringify({action:'exchange'})});if(!r.ok)throw new Error(d.error||'No se pudo crear la sesión administrativa segura.');csrf=String(d.csrf||'');sessionStorage.setItem(CSRF_KEY,csrf);localStorage.setItem(KEY,JSON.stringify({id:user.id,name:user.name,surname:user.surname,email:user.email,phone:user.phone,role:d.role||user.role,mfa:user.mfa===true,mfaExempt:user.mfaExempt===true}));return d}
async function sessionStatus(){const{r,d}=await jsonFetch('/.netlify/functions/admin-session',{method:'POST',headers:secureHeaders(),body:JSON.stringify({action:'status'})});if(!r.ok)throw Object.assign(new Error(d.error||'Sesión no válida.'),{auth:true});csrf=String(d.csrf||'');sessionStorage.setItem(CSRF_KEY,csrf);const current=session()||{};localStorage.setItem(KEY,JSON.stringify({...current,email:d.email,role:d.role||current.role}));return d}
async function logout(){try{await jsonFetch('/.netlify/functions/admin-session',{method:'POST',headers:secureHeaders(),body:JSON.stringify({action:'logout'})})}catch{}localStorage.removeItem(KEY);sessionStorage.removeItem(CSRF_KEY);csrf='';showLogin('Sesión cerrada.')}
function showLogin(msg=''){$('login').classList.remove('hidden');$('app').classList.add('hidden');$('loginError').textContent=msg}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function card(label,value,note,cls=''){return`<div class="card"><span class="muted">${esc(label)}</span><strong class="big ${cls}">${esc(value)}</strong><small class="muted">${esc(note||'')}</small></div>`}
const modules=[['/backoffice.html#orders','Pedidos','Pago, preparación y estado'],['/admin.html','Productos','Precio, stock y publicación'],['/enterprise.html#inventory','Inventario','Almacenes, reservas y ajustes'],['/enterprise.html#suppliers','Proveedores','Ficha y estado'],['/enterprise.html#purchase-orders','Compras','Pedidos a proveedor'],['/enterprise.html#returns','Devoluciones','Postventa y reembolso'],['/enterprise.html#reviews','Reseñas','Moderación'],['/enterprise.html#crm-tickets','Soporte CRM','Tickets de clientes'],['/enterprise.html#stock-alerts','Alertas stock','Avisos solicitados'],['/enterprise.html#product-questions','Preguntas','Consultas por producto'],['/enterprise.html#subscriptions','Suscripciones','Cadencias y estado'],['/enterprise.html#referrals','Referidos','Códigos y recompensas'],['/enterprise.html#tax-rules','Impuestos','Reglas fiscales'],['/enterprise.html#fraud-rules','Antifraude','Reglas y estado'],['/enterprise.html#privacy-requests','Privacidad','Solicitudes RGPD'],['/enterprise.html#translations','Traducciones','Textos por idioma']];
function renderOverview(){const s=overview.security||{},b=overview.backups||[],tpv=overview.tpvsol||{};$('who').textContent=`${overview.actor.email} · ${overview.actor.role}`;$('overviewCards').innerHTML=card('Rol',overview.actor.role,'Permisos efectivos')+card('MFA administrador',s.mfaExempt?'Exento':'Según usuario',s.mfaExempt?'Owner/Admin no requieren código MFA':'MFA individual por cuenta',s.mfaExempt?'ok':'')+card('Auditoría',s.audit?.valid?'Íntegra':'Revisar',s.audit?`${s.audit.checked||0} eventos comprobados`:'Solo owner/admin',s.audit?.valid?'ok':'bad')+card('Último backup',b[0]?.key?.replace('daily/','')||'Sin datos',`${b.length} copias listadas`);$('modules').innerHTML=modules.map(([href,name,desc])=>`<a class="module" href="${href}"><strong>${esc(name)}</strong><small>${esc(desc)}</small></a>`).join('');$('tpvCard').innerHTML=`<div class="brand">TPVSOL / FACTUSOL</div><h3 style="margin:7px 0">${esc(tpv.status||'NO VALIDADO')}</h3><p>${esc(tpv.message||'')}</p><p class="muted">No se mostrará una sincronización ficticia. Cuando existan API/credenciales o un mecanismo oficial verificable, se podrá activar aquí.</p>`}
async function load(){try{overview=await gov({action:'overview'});showApp();renderOverview()}catch(e){if(e.auth)showLogin(e.message);else showLogin(e.message)}}
function switchTab(name){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['overview','team','audit','backups','integrations'].forEach(x=>$(x+'Tab').classList.toggle('hidden',x!==name));if(name==='team')loadStaff();if(name==='audit')loadAudit();if(name==='backups')loadBackups()}
async function loadStaff(){try{const d=await gov({action:'staff-list'});staff=d.records||[];$('staffRows').innerHTML=staff.map(r=>{const mfa=r.mfaEnabled===true&&r.mfaConfigured===true;const mfaButtons=r.accountExists?(mfa?`<button data-mfa-regen="${esc(r.email)}">Regenerar MFA</button> <button data-mfa-off="${esc(r.email)}">Desactivar MFA</button>`:`<button data-mfa-on="${esc(r.email)}">Activar MFA</button>`):'';return`<tr><td><strong>${esc(r.name||r.email)}</strong><br><small class="muted">${esc(r.email)}</small></td><td><span class="badge">${esc(r.role)}</span></td><td class="${r.accountExists?'ok':'warn'}">${r.accountExists?'Existe':'Falta cuenta'}</td><td class="${mfa?'ok':'muted'}">${mfa?'Activo':'Desactivado'}</td><td class="${r.active!==false?'ok':'bad'}">${r.active!==false?'Activo':'Desactivado'}</td><td><div class="actions" style="margin-top:0"><button data-edit="${esc(r.email)}">Editar</button>${mfaButtons}<button data-remove="${esc(r.email)}">Quitar acceso</button></div></td></tr>`}).join('')||'<tr><td colspan="6" class="muted">No hay personal dinámico configurado.</td></tr>';$('staffRows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openStaff(staff.find(x=>x.email===b.dataset.edit)));$('staffRows').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeStaff(b.dataset.remove));$('staffRows').querySelectorAll('[data-mfa-on]').forEach(b=>b.onclick=()=>enableMfa(b.dataset.mfaOn,false));$('staffRows').querySelectorAll('[data-mfa-regen]').forEach(b=>b.onclick=()=>enableMfa(b.dataset.mfaRegen,true));$('staffRows').querySelectorAll('[data-mfa-off]').forEach(b=>b.onclick=()=>disableMfa(b.dataset.mfaOff))}catch(e){$('staffRows').innerHTML=`<tr><td colspan="6" class="bad">${esc(e.message)}</td></tr>`}}
function openStaff(r=null){editingEmail=r?.email||null;$('staffFormTitle').textContent=r?'Editar acceso':'Añadir persona';$('staffName').value=r?.name||'';$('staffEmail').value=r?.email||'';$('staffEmail').disabled=Boolean(r);$('staffRole').value=r?.role||'manager';$('staffActive').value=String(r?.active!==false);$('staffPermissions').value=(r?.permissions||[]).join(', ');$('staffPassword').value='';$('staffStatus').className='muted';$('staffStatus').textContent=r&&!r.accountExists?'Esta persona no tiene cuenta: indica una contraseña inicial de al menos 12 caracteres para crearla.':'';$('staffFormCard').classList.remove('hidden')}
function closeStaff(){$('staffFormCard').classList.add('hidden');editingEmail=null;$('staffEmail').disabled=false}
async function saveStaff(){const btn=$('saveStaff');btn.disabled=true;$('staffStatus').className='muted';$('staffStatus').textContent='Guardando…';try{const record={name:$('staffName').value.trim(),email:$('staffEmail').value.trim().toLowerCase(),role:$('staffRole').value,active:$('staffActive').value==='true',permissions:$('staffPermissions').value.split(',').map(v=>v.trim()).filter(Boolean)};const d=await gov({action:'staff-save',record,initialPassword:$('staffPassword').value});$('staffStatus').textContent=d.account?.missing?'Acceso guardado, pero la cuenta aún no existe. Añade una contraseña inicial para crearla.':'Acceso guardado correctamente.';await loadStaff();if(!d.account?.missing)setTimeout(closeStaff,500)}catch(e){$('staffStatus').textContent=e.message;$('staffStatus').className='bad'}finally{btn.disabled=false}}
async function removeStaff(email){if(!confirm(`Quitar el acceso interno de ${email}? La cuenta de cliente no se borra.`))return;try{await gov({action:'staff-remove',email});await loadStaff()}catch(e){alert(e.message)}}
function showMfaProvision(email,mfa){$('mfaTarget').textContent=email;$('mfaSetupSecret').textContent=mfa.setupSecret||'';$('mfaProvisionUri').textContent=mfa.provisioningUri||'';$('mfaProvisionCard').classList.remove('hidden');$('mfaProvisionCard').scrollIntoView({behavior:'smooth',block:'center'})}
async function enableMfa(email,regenerate){const wording=regenerate?'Regenerar MFA invalidará la configuración anterior y cerrará las sesiones activas de este empleado. ¿Continuar?':'Activar MFA cerrará las sesiones activas del empleado. ¿Continuar?';if(!confirm(wording))return;try{const d=await gov({action:regenerate?'staff-mfa-regenerate':'staff-mfa-enable',email});showMfaProvision(email,d.mfa||{});await loadStaff()}catch(e){alert(e.message)}}
async function disableMfa(email){if(!confirm(`Desactivar MFA para ${email}? También se cerrarán sus sesiones activas.`))return;try{await gov({action:'staff-mfa-disable',email});$('mfaProvisionCard').classList.add('hidden');await loadStaff()}catch(e){alert(e.message)}}
async function copyText(value){try{await navigator.clipboard.writeText(String(value||''));return true}catch{return false}}
async function loadAudit(){try{const d=await gov({action:'audit-list',limit:150});$('auditState').textContent=d.verification?.valid?`Cadena íntegra · ${d.verification.checked} eventos verificados`:`Revisión necesaria: ${d.verification?.error||'sin datos'}`;$('auditRows').innerHTML=(d.events||[]).map(r=>`<tr><td>${esc(new Date(r.at).toLocaleString('es-ES'))}</td><td>${esc(r.actor)}</td><td>${esc(r.action)}</td><td>${esc(r.resource)}</td><td>${esc(r.outcome)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Sin eventos.</td></tr>'}catch(e){$('auditState').textContent=e.message}}
async function loadBackups(){try{const d=await gov({action:'backup-list'});$('backupRows').innerHTML=(d.backups||[]).map(b=>`<tr><td><strong>${esc(b.key.replace('daily/',''))}</strong><br><small class="muted">${esc(b.key)}</small></td><td class="ok">Disponible</td><td><button data-restore="${esc(b.key)}">Preparar restauración</button></td></tr>`).join('')||'<tr><td colspan="3" class="muted">No hay backups disponibles.</td></tr>';$('backupRows').querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>prepareRestore(b.dataset.restore))}catch(e){$('backupRows').innerHTML=`<tr><td colspan="3" class="bad">${esc(e.message)}</td></tr>`}}
async function prepareRestore(key){try{const d=await restore({key});restoreKey=key;restoreRequired=d.requiredConfirmation;$('restorePlan').innerHTML=`Backup <strong>${esc(key)}</strong> · ${Number(d.plan?.records||0).toLocaleString('es-ES')} registros en ${Object.keys(d.plan?.domains||{}).length} dominios. Antes de restaurar, el servidor crea una copia de seguridad preventiva del estado actual.`;$('restoreConfirm').value='';$('restoreConfirm').placeholder=restoreRequired||'';$('restoreStatus').textContent='';$('restoreBox').classList.remove('hidden')}catch(e){alert(e.message)}}
async function executeRestore(){const btn=$('executeRestore');if($('restoreConfirm').value!==restoreRequired){$('restoreStatus').textContent='La confirmación no coincide exactamente.';$('restoreStatus').className='bad';return}btn.disabled=true;$('restoreStatus').textContent='Restaurando…';try{const d=await restore({key:restoreKey,confirm:restoreRequired});$('restoreStatus').textContent=`Restauración completada: ${d.restored} registros. Copia preventiva: ${d.safetyBackup}`;$('restoreStatus').className='ok';await loadBackups()}catch(e){$('restoreStatus').textContent=e.message;$('restoreStatus').className='bad'}finally{btn.disabled=false}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('loginError').textContent='';try{const payload={email:$('email').value.trim(),password:$('password').value};if(!$('mfaWrap').classList.contains('hidden'))payload.mfaCode=$('mfaCode').value.trim();const{r,d}=await jsonFetch('/.netlify/functions/staff-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){if(d.mfaRequired){$('mfaWrap').classList.remove('hidden');$('mfaCode').focus()}throw new Error(d.error||'No se pudo entrar')}await exchange(d.user.token,d.user);$('mfaCode').value='';$('mfaWrap').classList.add('hidden');await load()}catch(err){$('loginError').textContent=err.message}finally{btn.disabled=false}};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('newStaff').onclick=()=>openStaff();$('cancelStaff').onclick=closeStaff;$('saveStaff').onclick=saveStaff;$('loadAudit').onclick=loadAudit;$('loadBackups').onclick=loadBackups;$('cancelRestore').onclick=()=>{$('restoreBox').classList.add('hidden');restoreKey=restoreRequired=null};$('executeRestore').onclick=executeRestore;$('refresh').onclick=load;$('logout').onclick=logout;$('closeMfaProvision').onclick=()=>$('mfaProvisionCard').classList.add('hidden');$('copyMfaSecret').onclick=async()=>{const ok=await copyText($('mfaSetupSecret').textContent);$('copyMfaSecret').textContent=ok?'Copiado':'No se pudo copiar';setTimeout(()=>$('copyMfaSecret').textContent='Copiar clave',1200)};$('copyMfaUri').onclick=async()=>{const ok=await copyText($('mfaProvisionUri').textContent);$('copyMfaUri').textContent=ok?'Copiado':'No se pudo copiar';setTimeout(()=>$('copyMfaUri').textContent='Copiar URI',1200)};
(async()=>{try{await sessionStatus();await load()}catch{localStorage.removeItem(KEY);sessionStorage.removeItem(CSRF_KEY);csrf='';showLogin()}})();
})();