'use strict';

const SESSION_KEY = 'nutretium_user';
let state = { pedidos: [], metricas: {}, admin: '', currentView: 'dashboard' };
const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = (v) => new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v||0));
const date = (v) => v ? new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)) : '—';
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function token(){return (session()||{}).token||''}
function address(envio){if(!envio)return '—';return [envio.direccion,envio.piso,envio.codigoPostal,envio.localidad,envio.provincia].filter(Boolean).join(', ')}
function badge(value,type=''){return `<span class="badge ${type}">${esc(value||'—')}</span>`}
function payBadge(s){return badge(s,s==='PAID'?'paid':s==='FAILED'?'failed':'warn')}
function fulfilmentLabel(s){return ({PENDING_FULFILMENT:'Pendiente',PREPARING:'Preparando',READY_TO_SHIP:'Listo para enviar',SHIPPED:'Enviado',DELIVERED:'Entregado',CANCELLED:'Cancelado',REVIEW_REQUIRED:'Revisar'})[s]||s||'—'}
async function api(body){const res=await fetch('/.netlify/functions/admin-orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok)throw Object.assign(new Error(data.error||'Error del servidor'),{status:res.status});return data}
async function login(email,password){const res=await fetch('/.netlify/functions/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',email,password})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'No se pudo iniciar sesión');localStorage.setItem(SESSION_KEY,JSON.stringify(data.user));return data.user}
async function load(){try{const data=await api({action:'list'});state.pedidos=data.pedidos||[];state.metricas=data.metricas||{};state.admin=data.administrador||'';$('adminEmail').textContent=state.admin;showApp();renderAll()}catch(e){if([401,403].includes(e.status)){showLogin(e.message)}else{throw e}}}
function showLogin(msg=''){$('login').classList.remove('hidden');$('app').classList.add('hidden');$('loginError').textContent=msg}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function renderMetrics(){const m=state.metricas;$('metrics').innerHTML=[['Ventas confirmadas',money(m.ventas)],['Pedidos pagados',m.pagados||0],['Ticket medio',money(m.ticketMedio)],['Por preparar',m.pendientes||0],['Incidencias',m.incidencias||0],['Clientes',m.clientes||0]].map(([k,v])=>`<div class="card metric"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}
function row(p,button=true){return `<tr><td><strong>${esc(p.order)}</strong></td><td>${esc(p.cliente||'—')}<br><small class="muted">${esc(p.email||'')}</small></td><td>${money(p.amount)}</td><td>${payBadge(p.status)}</td><td>${badge(fulfilmentLabel(p.fulfilmentStatus),p.fulfilmentStatus==='REVIEW_REQUIRED'?'warn':'')}</td><td>${date(p.createdAt||p.receivedAt)}</td>${button?`<td><button data-open="${esc(p.order)}">Abrir</button></td>`:''}</tr>`}
function renderRecent(){$('recentRows').innerHTML=state.pedidos.slice(0,10).map(p=>row(p,false)).join('')||'<tr><td colspan="6" class="muted">No hay pedidos todavía.</td></tr>'}
function filteredOrders(){const q=$('search').value.trim().toLowerCase(),pay=$('paymentFilter').value,ful=$('fulfilmentFilter').value;return state.pedidos.filter(p=>(!pay||p.status===pay)&&(!ful||p.fulfilmentStatus===ful)&&(!q||[p.order,p.cliente,p.email,p.telefono].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderOrders(){$('orderRows').innerHTML=filteredOrders().map(p=>row(p,true)).join('')||'<tr><td colspan="7" class="muted">No hay resultados.</td></tr>'}
function renderShipping(){const list=state.pedidos.filter(p=>p.status==='PAID'||p.fulfilmentStatus==='REVIEW_REQUIRED').filter(p=>!['DELIVERED','CANCELLED'].includes(p.fulfilmentStatus));$('shippingRows').innerHTML=list.map(p=>`<tr><td><strong>${esc(p.order)}</strong></td><td>${esc(p.cliente||p.email||'—')}</td><td>${esc(address(p.envio))}</td><td>${badge(fulfilmentLabel(p.fulfilmentStatus),p.fulfilmentStatus==='REVIEW_REQUIRED'?'warn':'')}</td><td>${p.tracking?.code?`${esc(p.tracking.carrier||'')}<br><small>${esc(p.tracking.code)}</small>`:'—'}</td><td><button data-open="${esc(p.order)}">Gestionar</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No hay pedidos en la cola logística.</td></tr>'}
function renderCustomers(){const map=new Map();state.pedidos.filter(p=>p.email).forEach(p=>{const key=p.email.toLowerCase(),c=map.get(key)||{email:p.email,name:p.cliente||'',phone:p.telefono||'',orders:0,spent:0,last:null};c.orders++;if(p.status==='PAID')c.spent+=Number(p.amount||0);if(!c.last||String(p.createdAt||'')>String(c.last||''))c.last=p.createdAt;map.set(key,c)});$('customerGrid').innerHTML=[...map.values()].sort((a,b)=>b.spent-a.spent).map(c=>`<article class="customer"><strong>${esc(c.name||c.email)}</strong><small>${esc(c.email)}${c.phone?' · '+esc(c.phone):''}</small><p><b>${c.orders}</b> pedidos · <b>${money(c.spent)}</b></p><small>Último pedido: ${date(c.last)}</small></article>`).join('')||'<p class="muted">Aún no hay clientes con pedidos.</p>'}
function renderAll(){renderMetrics();renderRecent();renderOrders();renderShipping();renderCustomers()}
function openOrder(order){const p=state.pedidos.find(x=>x.order===order);if(!p)return;$('drawerTitle').textContent='#'+p.order;const items=(p.items||[]).map(i=>`<li>${esc(i.name||i.nombre||'Producto')} × ${esc(i.qty||i.quantity||1)}${i.price!=null?' · '+money(Number(i.price)*(Number(i.qty||i.quantity||1))):''}</li>`).join('')||'<li>Sin detalle de artículos</li>';$('drawerBody').innerHTML=`<div class="section"><strong>${esc(p.cliente||'Cliente')}</strong><br><span class="muted">${esc(p.email||'')} ${p.telefono?'· '+esc(p.telefono):''}</span><p>${esc(address(p.envio))}</p></div><div class="section"><div class="row"><div>Pago<br>${payBadge(p.status)}</div><div>Importe<br><strong>${money(p.amount)}</strong></div></div>${p.amountMismatch?'<p class="error">⚠ Importe cobrado distinto del esperado. Revisión obligatoria.</p>':''}</div><div class="section"><strong>Productos</strong><ul>${items}</ul></div><form id="fulfilmentForm" class="section"><label>Estado logístico</label><select id="drawerStatus">${['PENDING_FULFILMENT','PREPARING','READY_TO_SHIP','SHIPPED','DELIVERED','REVIEW_REQUIRED','CANCELLED'].map(s=>`<option value="${s}" ${p.fulfilmentStatus===s?'selected':''}>${fulfilmentLabel(s)}</option>`).join('')}</select><div class="row"><div><label>Transportista</label><input id="carrier" value="${esc(p.tracking?.carrier||'')}"></div><div><label>Tracking</label><input id="trackingCode" value="${esc(p.tracking?.code||'')}"></div></div><label>URL seguimiento</label><input id="trackingUrl" type="url" value="${esc(p.tracking?.url||'')}"><label>Nota interna</label><textarea id="internalNote" rows="3">${esc(p.internalNote||'')}</textarea><button class="primary" style="margin-top:14px">Guardar estado</button><span id="saveStatus" class="muted" style="margin-left:10px"></span></form>`;$('drawer').classList.remove('hidden');$('fulfilmentForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('saveStatus').textContent='Guardando…';try{const data=await api({action:'update-fulfilment',order:p.order,fulfilmentStatus:$('drawerStatus').value,tracking:{carrier:$('carrier').value,code:$('trackingCode').value,url:$('trackingUrl').value},internalNote:$('internalNote').value});const idx=state.pedidos.findIndex(x=>x.order===p.order);state.pedidos[idx]=data.pedido;renderAll();$('saveStatus').textContent='Guardado';setTimeout(()=>openOrder(p.order),300)}catch(err){$('saveStatus').textContent=err.message;$('saveStatus').className='error'}finally{btn.disabled=false}}}
function switchView(v){state.currentView=v;document.querySelectorAll('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));['dashboard','orders','shipping','customers'].forEach(x=>$(x+'View').classList.toggle('hidden',x!==v));$('viewTitle').textContent=({dashboard:'Dashboard',orders:'Pedidos',shipping:'Envíos',customers:'Clientes'})[v]}
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)openOrder(b.dataset.open)});document.querySelectorAll('.nav button[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));['search','paymentFilter','fulfilmentFilter'].forEach(id=>$(id).addEventListener('input',renderOrders));$('catalogBtn').onclick=()=>location.href='/admin.html';$('closeDrawer').onclick=()=>$('drawer').classList.add('hidden');$('logout').onclick=()=>{localStorage.removeItem(SESSION_KEY);showLogin('Sesión cerrada.')};$('refresh').onclick=async()=>{const b=$('refresh');b.disabled=true;b.textContent='Actualizando…';try{await load()}finally{b.disabled=false;b.textContent='Actualizar'}};$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('loginError').textContent='';try{await login($('email').value.trim(),$('password').value);await load()}catch(err){$('loginError').textContent=err.message}finally{btn.disabled=false}};
if(token())load().catch(e=>showLogin(e.message));else showLogin();
