'use strict';
const CART='nutretium_cart_v1',SESSION='nutretium_user';
const $=id=>document.getElementById(id);
const PRODUCTS=window.NUTRETIUM_PRODUCTS||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function savedCart(){try{return JSON.parse(localStorage.getItem(CART)||'[]')}catch{return[]}}
function itemRows(){return savedCart().map(row=>{const p=PRODUCTS.find(x=>Number(x.id)===Number(row.id));if(!p)return null;return{id:p.id,code:p.code,qty:Math.max(1,Number(row.quantity)||1),name:p.name,price:Number(p.price)}}).filter(Boolean)}
function subtotal(){return itemRows().reduce((s,i)=>s+i.price*i.qty,0)}
function track(name){try{if(localStorage.getItem('nutretium_cookies')==='accepted')fetch('/.netlify/functions/analytics-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})}catch{}}
let appliedCoupon='';
function render(){const rows=itemRows();$('lines').innerHTML=rows.length?rows.map(i=>`<div class="line"><span>${esc(i.name)} ×${i.qty}</span><span>${(i.price*i.qty).toFixed(2)} €</span></div>`).join(''):'<p class="muted">El carrito está vacío.</p>';$('subtotal').textContent=subtotal().toFixed(2)+' €';$('total').textContent=subtotal().toFixed(2)+' €';$('pay').disabled=!rows.length}
async function applyCoupon(){const code=$('coupon').value.trim();if(!code){appliedCoupon='';$('couponMsg').textContent='';$('discountRow').classList.add('hidden');$('total').textContent=subtotal().toFixed(2)+' €';return}const r=await fetch('/.netlify/functions/commerce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'coupon',code,subtotalCents:Math.round(subtotal()*100)})});const d=await r.json().catch(()=>({}));if(!r.ok){appliedCoupon='';$('couponMsg').textContent=d.reason==='minimum'?'No alcanzas el mínimo de este cupón.':'Cupón no válido o no activo.';$('discountRow').classList.add('hidden');$('total').textContent=subtotal().toFixed(2)+' €';return}appliedCoupon=d.code;$('couponMsg').textContent=`Cupón ${d.code} aplicado.`;$('discount').textContent='−'+(d.discountCents/100).toFixed(2)+' €';$('discountRow').classList.remove('hidden');$('total').textContent=(d.totalCents/100).toFixed(2)+' €';track('coupon_apply')}
function guest(){return{name:$('name').value.trim(),surname:$('surname').value.trim(),email:$('email').value.trim(),phone:$('phone').value.trim(),direccion:{calle:$('calle').value.trim(),piso:$('piso').value.trim(),cp:$('cp').value.trim(),localidad:$('localidad').value.trim(),provincia:$('provincia').value.trim(),pais:$('pais').value.trim()}}}
function validateGuest(g){if(!g.name)return'Escribe tu nombre.';if(!g.email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(g.email))return'Introduce un email válido.';if(!g.direccion.calle)return'Falta la calle y el número.';if(!/^\d{5}$/.test(g.direccion.cp))return'El código postal debe tener cinco cifras.';if(!g.direccion.localidad)return'Falta la localidad.';if(!g.direccion.provincia)return'Falta la provincia.';if(!g.direccion.pais)return'Falta el país.';return null}
function submitRedsys(data){localStorage.setItem('nutretium_last_order',data.order);const f=document.createElement('form');f.method='POST';f.action=data.redsysUrl;[['Ds_SignatureVersion',data.Ds_SignatureVersion],['Ds_MerchantParameters',data.Ds_MerchantParameters],['Ds_Signature',data.Ds_Signature]].forEach(([n,v])=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i)});document.body.appendChild(f);f.submit()}
async function pay(){const s=session();$('error').textContent='';const body={items:itemRows().map(({id,code,qty})=>({id,code,qty})),coupon:appliedCoupon||undefined};if(!body.items.length){$('error').textContent='El carrito está vacío.';return}if(s?.token)body.token=s.token;else{body.guest=guest();const problem=validateGuest(body.guest);if(problem){$('error').textContent=problem;return}}$('pay').disabled=true;$('pay').textContent='Preparando pago…';try{track('begin_checkout');const r=await fetch('/.netlify/functions/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo preparar el pago.');submitRedsys(d)}catch(e){$('error').textContent=e.message;$('pay').disabled=false;$('pay').textContent='Continuar a Redsys'}}
const s=session();if(s?.token){$('guestFields').classList.add('hidden');$('modeText').textContent='Comprarás con tu cuenta y la dirección guardada en Mi Nutretium.'}else{$('modeText').textContent='Compra como invitado: solo necesitamos los datos necesarios para gestionar tu pedido.'}
$('applyCoupon').onclick=applyCoupon;$('pay').onclick=pay;$('coupon').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyCoupon()}});render();
