'use strict';
const SESSION='nutretium_user';const $=id=>document.getElementById(id);
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function token(){return session()?.token||''}
async function get(url){const r=await fetch(url,{headers:{Authorization:'Bearer '+token()}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo cargar');return d}
function metric(label,value,{raw=false,note=''}={}){const shown=raw?String(value??'NO VALIDADO'):Number(value||0).toLocaleString('es-ES');return `<div class="card"><span class="muted">${label}</span><b>${shown}</b>${note?`<small class="muted">${note}</small>`:''}</div>`}
const pct=v=>v===null||v===undefined?'NO VALIDADO':`${Number(v).toLocaleString('es-ES',{maximumFractionDigits:2})}%`;
async function load(){try{const[a,h]=await Promise.all([get('/.netlify/functions/admin-analytics'),get('/.netlify/functions/system-health')]);$('login').classList.add('hidden');$('panel').classList.remove('hidden');const t=a.totals||{},f=a.funnel||{};$('metrics').innerHTML=metric('Vistas producto',t.view_item)+metric('Añadir carrito',t.add_to_cart)+metric('Inicio checkout',t.begin_checkout)+metric('Retorno compra',t.purchase_view)+metric('Vista → carrito',pct(f.viewToCartPct),{raw:true,note:'eventos registrados'})+metric('Checkout → retorno compra',pct(f.checkoutToPurchaseViewPct),{raw:true,note:'no equivale a conciliación bancaria'});$('checks').innerHTML=Object.entries(h.checks||{}).map(([k,v])=>`<div class="check"><strong>${k}</strong><div class="${v?'ok':'bad'}">${v?'Configurado':'Pendiente'}</div></div>`).join('');$('days').innerHTML=(a.days||[]).map(d=>`<tr><td>${d.date}</td><td>${d.events?.view_item||0}</td><td>${d.events?.add_to_cart||0}</td><td>${d.events?.begin_checkout||0}</td><td>${d.events?.coupon_apply||0}</td><td>${d.events?.recommendation||0}</td></tr>`).join('')}catch(e){$('err').textContent=e.message}}
$('loginBtn').onclick=async()=>{try{const r=await fetch('/.netlify/functions/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',email:$('email').value.trim(),password:$('password').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo entrar');localStorage.setItem(SESSION,JSON.stringify(d.user));await load()}catch(e){$('err').textContent=e.message}};if(token())load();
