'use strict';
const SESSION='nutretium_user', CART='nutretium_cart_v1', WISH='nutretium_wishlist_v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function token(){return session()?.token||''}
function products(){return (window.NUTRETIUM_PRODUCTS||[]).filter(p=>p.active!==false)}
function productByName(name){return products().find(p=>p.name===name)||null}
function productByKey(key){return products().find(p=>String(p.code||p.id)===String(key))||null}
function cartWrite(items){localStorage.setItem(CART,JSON.stringify(items))}
function addLines(lines){const current=(()=>{try{return JSON.parse(localStorage.getItem(CART)||'[]')}catch{return[]}})();const map=new Map(current.map(x=>[String(x.id),x]));for(const line of lines){const p=productByName(line.name)||productByKey(line.code||line.id);if(!p)continue;const k=String(p.id);const prev=map.get(k)||{key:k,id:p.id,quantity:0,customization:null};prev.quantity=Math.min(99,Math.max(1,Number(prev.quantity||0)+Number(line.qty||1)));map.set(k,prev)}cartWrite([...map.values()]);location.href='/?cart=1'}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),Authorization:'Bearer '+token()};const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo cargar');return d}
function renderWishlist(){let ids=[];try{ids=JSON.parse(localStorage.getItem(WISH)||'[]')}catch{};const set=new Set(ids.map(Number));const list=products().filter(p=>set.has(Number(p.id)));$('wishlistCount').textContent=list.length;$('wishlist').innerHTML=list.length?list.map(p=>`<div class="row"><div><strong>${esc(p.name)}</strong><div class="muted">${Number(p.price).toFixed(2)} €</div></div><a class="btn" href="/producto/${encodeURIComponent((p.name||'producto').toLowerCase().replace(/[^a-z0-9]+/g,'-'))}-${p.id}">Ver</a></div>`).join(''):'<div class="empty">No tienes favoritos guardados.</div>'}
function statusLabel(o){const f=o.fulfilmentStatus||'';if(f==='SHIPPED')return 'Enviado';if(f==='DELIVERED')return 'Entregado';if(f==='PREPARING')return 'Preparando';if(f==='READY_TO_SHIP')return 'Listo para enviar';if(f==='REVIEW_REQUIRED')return 'En revisión';return o.status==='PAID'?'Pagado':'En proceso'}
async function load(){const s=session();if(!s?.token){$('loginBox').hidden=false;return}$('account').hidden=false;$('hello').textContent=s.name?`Hola, ${s.name}.`:'Tu cuenta Nutretium';renderWishlist();try{const [commerce,orders,saved]=await Promise.all([api('/.netlify/functions/commerce'),api('/.netlify/functions/orders'),api('/.netlify/functions/saved-cart')]);const sum=commerce.summary||{};$('points').textContent=Number(sum.points||0).toLocaleString('es-ES');$('ordersCount').textContent=sum.orders||0;$('spent').textContent=Number(sum.spent||0).toFixed(2)+' €';const freq=sum.frequentProducts||[];$('reorder').innerHTML=freq.length?freq.map(x=>`<div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">Comprado ${x.qty} veces/unidades</div></div><button class="btn" data-reorder="${esc(x.key)}">Añadir</button></div>`).join(''):'<div class="empty">Cuando tengas compras confirmadas aparecerán aquí tus productos habituales.</div>';$('orders').innerHTML=(orders.orders||[]).length?(orders.orders||[]).map(o=>`<div class="row"><div><strong>Pedido ${esc(o.order)}</strong><div class="muted">${statusLabel(o)} · ${Number(o.amount||0).toFixed(2)} €${o.tracking?.code?` · Tracking ${esc(o.tracking.code)}`:''}</div></div><button class="btn" data-order="${esc(o.order)}">Repetir</button></div>`).join(''):'<div class="empty">Aún no hay pedidos.</div>';const c=saved.cart;$('savedCart').innerHTML=c&&Array.isArray(c.items)&&c.items.length?`<div class="row"><div><strong>${c.items.length} líneas guardadas</strong><div class="muted">Valor actual ${Number(c.total||0).toFixed(2)} €</div></div><button id="restoreCart" class="btn">Recuperar carrito</button></div>`:'<div class="empty">No hay carrito guardado en tu cuenta.</div>';$('restoreCart')?.addEventListener('click',()=>addLines(c.items));document.querySelectorAll('[data-reorder]').forEach(b=>b.onclick=()=>{const p=productByKey(b.dataset.reorder);if(p)addLines([{name:p.name,qty:1}])});document.querySelectorAll('[data-order]').forEach(b=>{const o=(orders.orders||[]).find(x=>x.order===b.dataset.order);if(o)addLines(o.items||[])})}catch(e){$('reorder').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$('loginBtn').onclick=async()=>{try{const r=await fetch('/.netlify/functions/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',email:$('email').value.trim(),password:$('password').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo entrar');localStorage.setItem(SESSION,JSON.stringify(d.user));location.reload()}catch(e){$('loginError').textContent=e.message}};
load();
