(function () {
  'use strict';
  const KEY='nutretium_user',$=(id)=>document.getElementById(id);
  function user(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
  function token(){return(user()||{}).token||''}
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(body,path='customer-commerce'){const r=await fetch('/.netlify/functions/'+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la operación');return d}
  function items(rows,empty='Sin registros'){return(rows||[]).map(r=>`<div class="item"><b>${esc(r.subject||r.orderId||r.name||r.cadence||r.type||r.code||r.id)}</b><div class="muted">${esc(r.status||'')}</div></div>`).join('')||`<div class="muted">${esc(empty)}</div>`}
  function renderOrders(rows){return(rows||[]).map(r=>{const total=Number(r.amount||0).toFixed(2),date=r.createdAt?new Date(r.createdAt).toLocaleDateString('es-ES'):'';return `<div class="item"><b>Pedido ${esc(r.order)}</b><div class="muted">${esc(r.status)} · ${total} € · ${esc(date)}</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:7px">${r.status==='PAID'&&r.invoiceReady?`<button class="btn invoice" data-order="${esc(r.order)}">Descargar factura</button>`:''}${r.status==='PAID'?`<button class="btn return" data-order="${esc(r.order)}">Solicitar devolución</button>`:''}</div></div>`}).join('')||'<div class="muted">Aún no hay pedidos.</div>'}
  async function downloadInvoice(order){const r=await fetch('/.netlify/functions/invoice-download?order='+encodeURIComponent(order),{headers:{Authorization:'Bearer '+token()}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'No se pudo descargar la factura')}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Nutretium-'+order+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function bindOrders(){document.querySelectorAll('.invoice').forEach(b=>b.onclick=async()=>{try{await downloadInvoice(b.dataset.order)}catch(e){alert(e.message)}});document.querySelectorAll('.return').forEach(b=>b.onclick=async()=>{const reason=prompt('Motivo de la devolución:','');if(!reason)return;try{await api({action:'request-return',orderId:b.dataset.order,reason,items:[]});await load()}catch(e){alert(e.message)}})}

  function latestConsent(rows,purpose){const m=(rows||[]).filter(r=>r.purpose===purpose).sort((a,b)=>String(b.changedAt||b.updatedAt||'').localeCompare(String(a.changedAt||a.updatedAt||'')))[0];return m?.status==='granted'}
  async function load(){if(!token()){$('login').hidden=false;$('app').hidden=true;return}try{const d=await api({action:'overview'});$('login').hidden=true;$('app').hidden=false;$('loyalty').innerHTML=d.loyalty?`<strong style="font-size:1.7rem;color:#d4af37">${Number(d.loyalty.balance||0)}</strong><div class="muted">puntos disponibles</div>`:'<div class="muted">Sin saldo todavía.</div>';$('orders').innerHTML=renderOrders(d.orders);bindOrders();$('subscriptions').innerHTML=items(d.subscriptions);$('returns').innerHTML=items(d.returns);$('tickets').innerHTML=items(d.tickets);$('carts').innerHTML=items(d.savedCarts);$('privacy').innerHTML=items(d.privacyRequests);$('reviews').innerHTML=items(d.reviews,'Aún no has enviado reseñas.');$('referrals').innerHTML=(d.referrals||[]).length?d.referrals.map(r=>`<div class="item"><div class="code">${esc(r.code)}</div><div class="muted">${Number(r.conversions||0)} conversiones · ${esc(r.status)}</div></div>`).join(''):'<div class="muted">Aún no tienes código.</div>';$('consentAnalytics').checked=latestConsent(d.consents,'analytics');$('consentMarketing').checked=latestConsent(d.consents,'marketing');$('consentPersonalization').checked=latestConsent(d.consents,'personalization')}catch(e){if(/sesión|iniciar/i.test(e.message)){localStorage.removeItem(KEY);location.reload()}else alert(e.message)}}
  $('supportForm').onsubmit=async e=>{e.preventDefault();try{await api({action:'support-ticket',subject:$('subject').value,message:$('message').value});e.target.reset();await load()}catch(err){alert(err.message)}};
  $('privacyForm').onsubmit=async e=>{e.preventDefault();try{await api({action:'privacy-request',type:$('privacyType').value,details:$('privacyDetails').value});e.target.reset();await load()}catch(err){alert(err.message)}};
  $('passwordForm').onsubmit=async e=>{e.preventDefault();$('securityMsg').textContent='';try{await api({action:'change-password',oldPassword:$('oldPassword').value,newPassword:$('newPassword').value},'account-security');$('securityMsg').textContent='Contraseña actualizada.';$('securityMsg').className='status ok';e.target.reset()}catch(err){$('securityMsg').textContent=err.message;$('securityMsg').className='status bad'}};
  $('referralCreate').onclick=async()=>{try{await api({action:'referral-create'});await load()}catch(err){alert(err.message)}};
  $('reviewForm').onsubmit=async e=>{e.preventDefault();$('reviewMsg').textContent='';try{await api({action:'submit-review',orderId:$('reviewOrder').value.trim(),productId:Number($('reviewProduct').value),rating:Number($('reviewRating').value),title:$('reviewTitle').value,body:$('reviewBody').value});$('reviewMsg').textContent='Reseña enviada a moderación.';$('reviewMsg').className='status ok';e.target.reset();await load()}catch(err){$('reviewMsg').textContent=err.message;$('reviewMsg').className='status bad'}};
  $('giftCardForm').onsubmit=async e=>{e.preventDefault();$('giftCardResult').textContent='';try{const d=await api({action:'gift-card-balance',code:$('giftCardCode').value});const g=d.giftCard;$('giftCardResult').innerHTML=`Estado: <b>${esc(g.status)}</b> · Saldo: <b>${(Number(g.balanceCents||0)/100).toFixed(2)} ${esc(g.currency||'EUR')}</b>`}catch(err){$('giftCardResult').textContent=err.message}};
  $('b2bForm').onsubmit=async e=>{e.preventDefault();$('b2bMsg').textContent='';try{await api({action:'b2b-apply',companyName:$('b2bCompany').value,taxId:$('b2bTax').value,contactName:$('b2bContact').value});$('b2bMsg').textContent='Solicitud B2B registrada.';$('b2bMsg').className='status ok';e.target.reset()}catch(err){$('b2bMsg').textContent=err.message;$('b2bMsg').className='status bad'}};
  async function setConsent(purpose,granted){try{await api({action:'consent-set',purpose,granted});if(window.NUTRETIUM_CONSENT&&purpose==='analytics'){granted?window.NUTRETIUM_CONSENT.acepta?.():window.NUTRETIUM_CONSENT.rechaza?.()}}catch(err){alert(err.message);await load()}}
  $('consentAnalytics').onchange=e=>setConsent('analytics',e.target.checked);$('consentMarketing').onchange=e=>setConsent('marketing',e.target.checked);$('consentPersonalization').onchange=e=>setConsent('personalization',e.target.checked);
  load();
})();

