/* NUTRETIUM Guardian Runtime — browser observability and safe recovery */
(function(){'use strict';
const sent=new Set(),retried=new WeakSet();
const nativeFetch=window.fetch.bind(window);
let networkSeq=0,lastRuntimeErrorAt=0,successSeq=0,lastSuccessAction='';
function localUrl(v){try{const u=new URL(String(v||''),location.href);return u.origin===location.origin?u:null}catch{return null}}
function sensitive(v){return /\b(?:checkout|pago|payment|redsys|refund|reembolso|delete|borrar|remove-account|password|contrase(?:n|ñ)a|mfa|totp|admin|staff|permission|role|secret|token|dns|migration|migraci(?:o|ó)n|pedido-final|order-finalize)\b/i.test(String(v||''))}
function actionId(el){return String(el?.dataset?.guardianAction||el?.id||el?.getAttribute?.('aria-label')||el?.name||el?.textContent||el?.className||'control').replace(/\s+/g,' ').trim().slice(0,160)}
function controlState(el){if(!el)return'';try{return JSON.stringify({text:String(el.textContent||'').replace(/\s+/g,' ').trim().slice(0,180),value:'value'in el?String(el.value||'').slice(0,180):'',className:String(el.className||'').slice(0,240),disabled:Boolean(el.disabled),ariaDisabled:el.getAttribute?.('aria-disabled')||'',ariaBusy:el.getAttribute?.('aria-busy')||'',ariaPressed:el.getAttribute?.('aria-pressed')||'',ariaExpanded:el.getAttribute?.('aria-expanded')||'',hidden:Boolean(el.hidden)})}catch{return''}}
function report(kind,message,extra={}){try{
 const key=`${kind}|${location.pathname}|${extra.actionId||''}|${message}`.slice(0,420);if(sent.has(key)||sent.size>=80)return;sent.add(key);
 const body={kind,message:String(message||'').slice(0,500),path:`${location.pathname}${location.search}`.slice(0,220),ua:navigator.userAgent.slice(0,240),actionId:String(extra.actionId||'').slice(0,160),method:String(extra.method||'').slice(0,12),url:String(extra.url||'').slice(0,300),status:Number(extra.status)||null,contract:String(extra.contract||'').slice(0,80),recovery:String(extra.recovery||'').slice(0,80),extra:{source:String(extra.source||'').split('/').pop().slice(0,120),line:Number(extra.line)||0,col:Number(extra.col)||0}};
 nativeFetch('/.netlify/functions/client-error',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:true,credentials:'same-origin'}).catch(()=>{});
}catch{}}
window.fetch=async function guardianFetch(input,init={}){
 const req=input instanceof Request?input:null,method=String(init.method||req?.method||'GET').toUpperCase(),url=String(req?.url||input||''),tracked=!url.includes('/.netlify/functions/client-error');if(tracked)networkSeq++;
 let response;try{response=await nativeFetch(input,init)}catch(error){if(tracked){lastRuntimeErrorAt=Date.now();report('network_error',error?.message||'Network request failed',{method,url})}throw error}
 if(tracked&&response.status>=500){const safe=(method==='GET'||method==='HEAD')&&Boolean(localUrl(url));report('network_5xx',`HTTP ${response.status}`,{method,url,status:response.status,recovery:safe?'retry-once':'none'});if(safe){try{await new Promise(r=>setTimeout(r,180));const retry=await nativeFetch(input,init);if(retry.ok)report('network_recovered',`HTTP ${response.status} recovered`,{method,url,status:retry.status,recovery:'retry-once'});return retry}catch{return response}}}
 return response;
};
window.addEventListener('error',e=>{lastRuntimeErrorAt=Date.now();const t=e.target;if(t&&t!==window&&t.tagName){report('resource_error',`Resource failed: ${String(t.tagName).toLowerCase()}`,{source:t.src||t.href||''});return}report('error',e.message,{source:String(e.filename||''),line:e.lineno||0,col:e.colno||0})},true);
window.addEventListener('unhandledrejection',e=>{lastRuntimeErrorAt=Date.now();report('promise',e.reason?.message||String(e.reason||'Unhandled promise rejection'))});
document.addEventListener('nt:guardian:success',e=>{successSeq++;lastSuccessAction=String(e?.detail?.actionId||'')});
function recover(el,id){if(sensitive(`${id} ${location.pathname}`))return 'protected';const fallback=localUrl(el?.dataset?.guardianFallbackHref);if(fallback&&fallback.pathname!==location.pathname){location.assign(fallback.href);return 'fallback-navigation'}if(el?.dataset?.guardianRetry==='safe'&&!retried.has(el)){retried.add(el);setTimeout(()=>{try{el.click()}catch{}},0);return 'safe-retry'}const key=`nt-guardian-reload:${location.pathname}`;if(Date.now()-lastRuntimeErrorAt<3500&&sessionStorage.getItem(key)!=='1'){sessionStorage.setItem(key,'1');setTimeout(()=>location.reload(),120);return 'reload-after-runtime-error'}return 'reported'}
function monitor(e){const el=e.target?.closest?.('button,[role="button"],input[type="button"],input[type="submit"]');if(!el||el.disabled||el.getAttribute('aria-disabled')==='true'||el.dataset.guardianIgnore==='true')return;const id=actionId(el),contract=String(el.dataset.guardianContract||'').trim(),before={href:location.href,network:networkSeq,success:successSeq,state:controlState(el)};setTimeout(()=>{if(!document.documentElement.contains(el))return;const explicitSuccess=successSeq!==before.success&&(!lastSuccessAction||lastSuccessAction===id);const changed=location.href!==before.href||networkSeq!==before.network||controlState(el)!==before.state||explicitSuccess;if(changed)return;const recovery=recover(el,id);report(contract?'contract_failure':'functional_failure',`Control without observable result: ${id}`,{actionId:id,contract,recovery})},Math.max(50,Number(el.dataset.guardianTimeout)||2200))}
document.addEventListener('click',monitor,true);
})();