// ─────────────────────────────────────────────────────────────────────────────
// NUTRETIUM — CATÁLOGO DE VENTA ACTIVO
// Generado desde "Listado de stock disponible.pdf" (corte 05/08/2026 23:28) y
// mantenido desde entonces con las herramientas del proyecto.
//
// NO EDITAR A MANO. Cada campo tiene su herramienta, y todas dejan ver antes lo
// que van a hacer:
//   · precios, altas, bajas, fotos y qué se publica → npm run panel   (visual)
//                                                     npm run catalogo (Excel)
//   · stock                                         → npm run stock
//   · incorporar fotos del buzón                    → npm run fotos
//
// Actualizado el 31/8/2026: 153 productos, 153 publicados (131 disponibles, 22 agotados).
//
// Reglas aplicadas (ver AUDITORIA_CATALOGO.md):
//   1. Fuente única de precios: columna P.Venta del listado oficial, sin recalcular.
//      Excepción AMRO (30 referencias): PVPR del Excel del distribuidor, que es el
//      precio que va en el nombre de cada archivo de sources/01_PNG_MAX_CALIDAD_CON_PVP.
//   2. Excluidos TODOS los productos AMIX (118 filas), con o sin stock.
//   3. Excluidas las familias no vendibles online: máquinas vending, servicio masaje,
//      bolsas, extras de mostrador y productos pendientes (221 filas).
//   4. Excluidos los productos con P.Venta = 0,00 € (44 filas): sin precio oficial
//      no se publican. Pendientes de precio en el ERP.
//
//   5. Excluidos los refrescos y energéticas de marca ajena (28 referencias):
//      Coca-cola, Fanta, Kas, Aquarius, Nestea, Seven Up, Trina, Dr Pepper,
//      Chupa Chups, Cacaolat, Bifrutas, Don Simón, Monster y Red Bull. Reventa
//      de marca que no pinta nada en una tienda de nutrición. La lista está en
//      netlify/lib/no-vendibles.js y las tres vías de edición la respetan: si
//      alguien regenera el catálogo desde el ERP, no vuelven solos.
//
//   553 filas leídas → 179 productos, de los que 28 se dieron de baja después
//      por la regla 5. Incluye 9 altas AMRO tomadas del Excel PVPR del
//      distribuidor (no figuran en el listado oficial: código provisional
//      AMRO-*, pendientes de alta en el ERP).
//
// Campos de trazabilidad: 'code' y 'pdfDescription' permiten cuadrar cada fila
// contra el PDF original. 'stock' es el valor Stock(GEN) del listado.
// 'image' apunta a sources/productos/<CATEGORIA>/<CODIGO>__<NOMBRE>.jpg cuando hay foto,
// y es null mientras se espera (ver sources/productos/LEEME.md). Las 30 fotos AMRO
// salen de sources/01_PNG_MAX_CALIDAD_CON_PVP; su PVPR viene en el nombre del archivo original.
// ─────────────────────────────────────────────────────────────────────────────

// Este archivo lo cargan DOS sitios y por eso se exporta de las dos formas:
//   - el navegador, con <script src>  → deja NUTRETIUM_PRODUCTS en window;
//   - las funciones de Netlify, con require() → lo deja en module.exports.
// El backend necesita leerlo para poner él los precios del pedido: nunca se
// cobra el importe que manda el navegador (ver netlify/lib/catalogo.js).
(function (NUTRETIUM_RAIZ) {

NUTRETIUM_RAIZ.NUTRETIUM_CATEGORIES = [
 "Bowls",
 "Yogures",
 "Smoothies y batidos",
 "Waffles y caprichos",
 "Café y matcha",
 "Bebidas",
 "Accesorios gym",
 "Proteínas",
 "Alimentación proteica",
 "Helados",
 "Vitaminas y salud",
 "Barritas y snacks",
 "Colágeno y bienestar",
 "Creatinas",
 "Pre-entrenos"
];

NUTRETIUM_RAIZ.NUTRETIUM_PRODUCTS = [
 {"id":1,"code":"ABB-1000","name":"Açaí Berry Brutal 1000 ml","category":"Bowls","price":18.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Açaí Berry Brutal 1000 ml"},
 {"id":2,"code":"ABB-500","name":"Açaí Berry Brutal 500 ml","category":"Bowls","price":10.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BOWLS/ABB-500__ACAI_BERRY_BRUTAL_500_ML.webp","emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Açaí Berry Brutal 500 ml"},
 {"id":3,"code":"ABB-750","name":"Açaí Berry Brutal 750 ml","category":"Bowls","price":13.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Açaí Berry Brutal 750 ml"},
 {"id":4,"code":"BG-1000","name":"Bahía Gold 1000 ml","category":"Bowls","price":18.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Bahía Gold 1000 ml"},
 {"id":5,"code":"BG-500","name":"Bahía Gold 500 ml","category":"Bowls","price":10.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Bahía Gold 500 ml"},
 {"id":6,"code":"BG-750","name":"Bahía Gold 750 ml","category":"Bowls","price":13.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Bahía Gold 750 ml"},
 {"id":7,"code":"BCB-1000","name":"Black Cacao Berry 1000 ml","category":"Bowls","price":17.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Black Cacao Berry 1000 ml"},
 {"id":8,"code":"BCB-500","name":"Black Cacao Berry 500 ml","category":"Bowls","price":11.98,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Black Cacao Berry 500 ml"},
 {"id":9,"code":"BCB-750","name":"Black Cacao Berry 750 ml","category":"Bowls","price":12.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Black Cacao Berry 750 ml"},
 {"id":10,"code":"CP-1000","name":"Choco Peanut 1000 ml","category":"Bowls","price":17.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Choco Peanut 1000 ml"},
 {"id":11,"code":"CP-500","name":"Choco Peanut 500 ml","category":"Bowls","price":9.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Choco Peanut 500 ml"},
 {"id":12,"code":"CP-750","name":"Choco Peanut 750 ml","category":"Bowls","price":12.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Choco Peanut 750 ml"},
 {"id":13,"code":"DP-1000","name":"Dubai Pistachio 1000 ml","category":"Bowls","price":19.95,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Dubai Pistachio 1000 ml"},
 {"id":14,"code":"DP-500","name":"Dubai Pistachio 500 ml","category":"Bowls","price":11.89,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Dubai Pistachio 500 ml"},
 {"id":15,"code":"DP-750","name":"Dubai Pistachio 750 ml","category":"Bowls","price":15.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Dubai Pistachio 750 ml"},
 {"id":16,"code":"MS-1000","name":"Matcha Strawberry 1000 ml","category":"Bowls","price":18.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Matcha Strawberry 1000 ml"},
 {"id":17,"code":"MS-500","name":"Matcha Strawberry 500 ml","category":"Bowls","price":10.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Matcha Strawberry 500 ml"},
 {"id":18,"code":"MS-750","name":"Matcha Strawberry 750 ml","category":"Bowls","price":13.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Matcha Strawberry 750 ml"},
 {"id":19,"code":"RX-1000","name":"Royal X 1.000 ml","category":"Bowls","price":22.91,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Royal X 1.000 ml"},
 {"id":20,"code":"RX-500","name":"Royal X 500 ml","category":"Bowls","price":13.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Royal X 500 ml"},
 {"id":21,"code":"RX-750","name":"Royal X 750 ml","category":"Bowls","price":16.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"010 - Bowls estrella","pdfDescription":"Royal X 750 ml"},
 {"id":22,"code":"BOWL-1000","name":"Personaliza Bowl 1.000 ml","category":"Bowls","price":17.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"020 - Personaliza tu bowl","pdfDescription":"Personaliza Bowl 1.000 ml"},
 {"id":23,"code":"BOWL-500","name":"Personaliza Bowl 500 ml","category":"Bowls","price":9.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"020 - Personaliza tu bowl","pdfDescription":"Personaliza Bowl 500 ml"},
 {"id":24,"code":"BOWL-750","name":"Personaliza Bowl 750 ml","category":"Bowls","price":17.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"020 - Personaliza tu bowl","pdfDescription":"Personaliza Bowl 750 ml"},
 {"id":25,"code":"DAILY-BERRY","name":"Daily Berry 500 ml","category":"Yogures","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥛","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"030 - Daily Yogurt","pdfDescription":"Daily Berry 500 ml"},
 {"id":26,"code":"DAILY-CACAO","name":"Daily Cacao Crunch 500 ml","category":"Yogures","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥛","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"030 - Daily Yogurt","pdfDescription":"Daily Cacao Crunch 500 ml"},
 {"id":27,"code":"DAILY-TROPI","name":"Daily Tropical 500 ml","category":"Yogures","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥛","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"030 - Daily Yogurt","pdfDescription":"Daily Tropical 500 ml"},
 {"id":28,"code":"00538","name":"Batido Chocolate","category":"Smoothies y batidos","price":4.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"040 - Smoothies y batidos","pdfDescription":"batido chocolate"},
 {"id":29,"code":"00537","name":"Batido Mango","category":"Smoothies y batidos","price":4.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"040 - Smoothies y batidos","pdfDescription":"batido mango"},
 {"id":30,"code":"BATI-BC","name":"Berry Cloud","category":"Smoothies y batidos","price":7.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"040 - Smoothies y batidos","pdfDescription":"Berry Cloud"},
 {"id":31,"code":"00534","name":"Berry Smoothie","category":"Smoothies y batidos","price":4.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/SMOOTHIES_Y_BATIDOS/00534__BERRY_SMOOTHIE.webp","emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"040 - Smoothies y batidos","pdfDescription":"berry smoothie"},
 {"id":32,"code":"BATI-CP","name":"Cacao Peanut","category":"Smoothies y batidos","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"040 - Smoothies y batidos","pdfDescription":"Cacao Peanut"},
 {"id":33,"code":"CAPRI-BCP","name":"Berry Cloud Pop","category":"Waffles y caprichos","price":6.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🧇","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"050 - Waffles y caprichos","pdfDescription":"Berry Cloud Pop"},
 {"id":34,"code":"00536","name":"Capricho Fresa","category":"Waffles y caprichos","price":4.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🧇","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"050 - Waffles y caprichos","pdfDescription":"capricho fresa"},
 {"id":35,"code":"CAPRI-MSC","name":"Mini Sphere Cup","category":"Waffles y caprichos","price":7.2,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🧇","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"050 - Waffles y caprichos","pdfDescription":"Mini Sphere Cup"},
 {"id":36,"code":"CAPRI-PGP","name":"Pistachio Gold Pop","category":"Waffles y caprichos","price":8.49,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🧇","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"050 - Waffles y caprichos","pdfDescription":"Pistachio Gold Pop"},
 {"id":37,"code":"CAFE-AMERICAN","name":"Americano","category":"Café y matcha","price":2.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"Americano"},
 {"id":38,"code":"CAFE-CAPPUCCI","name":"Cappuccino","category":"Café y matcha","price":3.61,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"Cappuccino"},
 {"id":39,"code":"CAFE-CORTADO","name":"Cortado","category":"Café y matcha","price":2.7,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"Cortado"},
 {"id":40,"code":"CAFE-ESPRESO","name":"Espresso","category":"Café y matcha","price":2.2,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"Espresso"},
 {"id":41,"code":"CAFE-ICED","name":"LAT Iced Latte","category":"Café y matcha","price":3.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"LAT Iced Latte"},
 {"id":42,"code":"CAFE-LATTE","name":"Latte","category":"Café y matcha","price":3.4,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"060 - Café y matcha","pdfDescription":"Latte"},
 {"id":43,"code":"00532","name":"Agua Aquadeus 1.5l","category":"Bebidas","price":1.4,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"agua aquadeus 1.5l"},
 {"id":44,"code":"00500","name":"Agua Aquadeus 1.5l","category":"Bebidas","price":1.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"agua aquadeus 1.5l"},
 {"id":45,"code":"00001","name":"Agua Pequeña 33ml","category":"Bebidas","price":0.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"agua pequeña 33ml"},
 {"id":46,"code":"00531","name":"Agua Solares Pequeña 0.50ml","category":"Bebidas","price":0.8,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"agua solares pequeña 0.50ml"},
 {"id":47,"code":"00533","name":"Agua Solares 1.5l","category":"Bebidas","price":1.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"agua solares 1.5l"},
 {"id":61,"code":"ICE-CC","name":"Iced Cacao Coffee","category":"Bebidas","price":5.51,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Iced Cacao Coffee"},
 {"id":62,"code":"ICE-MC","name":"Iced Matcha Classic","category":"Bebidas","price":4.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Iced Matcha Classic"},
 {"id":63,"code":"ICE-PM","name":"Iced Pistachio Matcha","category":"Bebidas","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Iced Pistachio Matcha"},
 {"id":67,"code":"ICE-MT","name":"Mango Tropical","category":"Bebidas","price":5.9,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Mango Tropical"},
 {"id":68,"code":"00347","name":"Milkshake Banana 330ml Barebells","category":"Bebidas","price":2.95,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BEBIDAS/00347__MILKSHAKE_BANANA_330ML_BAREBELLS.webp","emoji":"🥤","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"milkshake banana 330ml barebells"},
 {"id":69,"code":"00348","name":"Milkshake Chocolate 330ml Barebells","category":"Bebidas","price":2.95,"stock":15,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BEBIDAS/00348__MILKSHAKE_CHOCOLATE_330ML_BAREBELLS.webp","emoji":"🥤","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"milkshake chocolate 330ml barebells"},
 {"id":70,"code":"00350","name":"Milkshake Cookies & Cream 330ml Barebells","category":"Bebidas","price":2.95,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"milkshake cookies & cream 330ml barebells"},
 {"id":71,"code":"00346","name":"Milkshake Strawberry 330ml Barebells","category":"Bebidas","price":2.95,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"milkshake strawberry 330ml barebells"},
 {"id":72,"code":"00349","name":"Milkshake Vainilla 330ml Barebells","category":"Bebidas","price":3.57,"stock":7,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"milkshake vainilla 330ml barebells"},
 {"id":80,"code":"00363","name":"NABE Aloe Vera THE Original","category":"Bebidas","price":2.5,"stock":20,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"NABE","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"NABE aloe vera THE ORIGINAL"},
 {"id":82,"code":"00353","name":"Nocco BCAA Mango 355ml","category":"Bebidas","price":2.5,"stock":22,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco BCAA MANGO 355ml"},
 {"id":83,"code":"00352","name":"Nocco BCAA+ Manzana 355ml","category":"Bebidas","price":2.5,"stock":48,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco BCAA+ MANZANA 355ml"},
 {"id":84,"code":"00355","name":"Nocco Electrolyte Blood Orange 355ml","category":"Bebidas","price":2.5,"stock":24,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco electrolyte BLOOD ORANGE 355ml"},
 {"id":85,"code":"00351","name":"Nocco Electrolyte Lima/limon 355ml","category":"Bebidas","price":2.5,"stock":24,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco electrolyte LIMA/LIMON 355ml"},
 {"id":86,"code":"00354","name":"Nocco Focus Grand Sour Limon/manzana 330ml","category":"Bebidas","price":2.5,"stock":24,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco FOCUS GRAND SOUR LIMON/MANZANA 330ml"},
 {"id":87,"code":"00356","name":"Nocco Focus Ramonade 330ml","category":"Bebidas","price":2.5,"stock":48,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Nocco","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Nocco FOCUS RAMONADE 330ml"},
 {"id":88,"code":"00480","name":"Oferta Pack Aqua Deus 6 Botellas 1.5l","category":"Bebidas","price":2.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"oferta pack aqua deus 6 botellas 1.5l"},
 {"id":89,"code":"00479","name":"Oferta Pack Solares 6 Botellas 1.5l","category":"Bebidas","price":2.95,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"oferta pack solares 6 botellas 1.5l"},
 {"id":90,"code":"00539","name":"Pack Aquadeus 6 Botellas 1.5l","category":"Bebidas","price":2.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"pack aquadeus 6 botellas 1.5l"},
 {"id":94,"code":"00358","name":"Vitamin Well Boost Arándanos Y Frambuesa","category":"Bebidas","price":2.5,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Vitamin Well","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Vitamin well boost ARÁNDANOS Y FRAMBUESA"},
 {"id":95,"code":"00357","name":"Vitamin Well Refresh Limonada/kiwi","category":"Bebidas","price":2.5,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Vitamin Well","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Vitamin well refresh LIMONADA/KIWI"},
 {"id":96,"code":"00360","name":"Vitamin Well Sport 002 Limón/lima","category":"Bebidas","price":3.03,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Vitamin Well","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Vitamin well sport 002 LIMÓN/LIMA"},
 {"id":97,"code":"00361","name":"Vitamin Well Zero Limón","category":"Bebidas","price":2.5,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Vitamin Well","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Vitamin well zero LIMÓN"},
 {"id":98,"code":"00359","name":"Vitamin Well Zero Peach Melocotón","category":"Bebidas","price":2.5,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":"Vitamin Well","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"Vitamin well zero peach MELOCOTÓN"},
 {"id":99,"code":"00083","name":"Zumo Naranja 500ml","category":"Bebidas","price":3.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥤","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"070 - Bebidas frías","pdfDescription":"zumo naranja 500ml"},
 {"id":101,"code":"00155","name":"Pastillero","category":"Accesorios gym","price":3.8,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🎒","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"10 - No existe...","pdfDescription":"Pastillero"},
 {"id":102,"code":"00289","name":"Proteina Isolada Moca 2kg Amro","category":"Proteínas","price":89.9,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00289__PROTEINA_ISOLADA_MOCA_2KG_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"100 - Proteínas","pdfDescription":"proteina isolada moca 2kg amro"},
 {"id":103,"code":"00284","name":"Cafe + Leche","category":"Café y matcha","price":1.8,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"☕","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"11 - No existe...","pdfDescription":"Cafe + leche"},
 {"id":104,"code":"00302","name":"Crema De Proteina Bonbon Crisp Protella 200g","category":"Alimentación proteica","price":7.99,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"crema de proteina bonbon crisp protella 200g"},
 {"id":105,"code":"00301","name":"Crema De Proteina Choco Hazenut Protella 200g","category":"Alimentación proteica","price":7.99,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00301__CREMA_DE_PROTEINA_CHOCO_HAZENUT_PROTELLA_200G.webp","emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"crema de proteina choco hazenut protella 200g"},
 {"id":106,"code":"00300","name":"Crema De Proteina Chocolate Blanco Protella 200g","category":"Alimentación proteica","price":7.99,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"crema de proteina chocolate blanco protella 200g"},
 {"id":107,"code":"00303","name":"Crema De Proteina Cookie Dough Protella 200g","category":"Alimentación proteica","price":7.99,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"crema de proteina cookie dough protella 200g"},
 {"id":108,"code":"00341","name":"Harina De Avena Chocolate 1000g Amro","category":"Alimentación proteica","price":6.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00341__HARINA_DE_AVENA_CHOCOLATE_1000G_AMRO.jpg","emoji":"🥣","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"harina de avena chocolate 1000g AMRO"},
 {"id":109,"code":"00340","name":"Harina De Avena Galleta Maria 1000g Amro","category":"Alimentación proteica","price":6.5,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00340__HARINA_DE_AVENA_GALLETA_MARIA_1000G_AMRO.jpg","emoji":"🥣","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"harina de avena galleta maria 1000g AMRO"},
 {"id":110,"code":"00367","name":"Salsa Barbacoa 320ml Servivita","category":"Alimentación proteica","price":3.9,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00367__SALSA_BARBACOA_320ML_SERVIVITA.webp","emoji":"🥣","customizable":false,"brand":"Servivita","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"salsa barbacoa 320ml servivita"},
 {"id":111,"code":"00365","name":"Salsa Cesar Zero 320ml Servivita","category":"Alimentación proteica","price":3.9,"stock":6,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00365__SALSA_CESAR_ZERO_320ML_SERVIVITA.webp","emoji":"🥣","customizable":false,"brand":"Servivita","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"salsa cesar zero 320ml servivita"},
 {"id":112,"code":"00366","name":"Salsa Ketchup 320ml Servivita","category":"Alimentación proteica","price":3.9,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00366__SALSA_KETCHUP_320ML_SERVIVITA.webp","emoji":"🥣","customizable":false,"brand":"Servivita","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"salsa ketchup 320ml servivita"},
 {"id":113,"code":"00368","name":"Salsa Mayonesa 320ml Servivita","category":"Alimentación proteica","price":3.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00368__SALSA_MAYONESA_320ML_SERVIVITA.webp","emoji":"🥣","customizable":false,"brand":"Servivita","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"salsa mayonesa 320ml servivita"},
 {"id":114,"code":"00364","name":"Salsa Miel & Mostaza 320ml Servivita","category":"Alimentación proteica","price":3.9,"stock":6,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00364__SALSA_MIEL_MOSTAZA_320ML_SERVIVITA.webp","emoji":"🥣","customizable":false,"brand":"Servivita","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"160 - Alimentación proteica","pdfDescription":"salsa miel & mostaza 320ml servivita"},
 {"id":115,"code":"00095","name":"Dip Extra Salsa","category":"Waffles y caprichos","price":0.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🧇","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"2 - No existe...","pdfDescription":"dip extra salsa"},
 {"id":116,"code":"00494","name":"Helado Cacao & Avellana 100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/HELADOS/00494__HELADO_CACAO_AVELLANA_100ML_PROTZEN.webp","emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado cacao & avellana 100ml protzen"},
 {"id":117,"code":"00488","name":"Helado Cacao & Avellana 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/HELADOS/00488__HELADO_CACAO_AVELLANA_460ML_PROTZEN.webp","emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado cacao & avellana 460ml protzen"},
 {"id":118,"code":"00496","name":"Helado Chocolate Negro 100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado chocolate negro 100ml protzen"},
 {"id":119,"code":"00490","name":"Helado Chocolate Negro 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado chocolate negro 460ml protzen"},
 {"id":120,"code":"00493","name":"Helado Merengada 100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/HELADOS/00493__HELADO_MERENGADA_100ML_PROTZEN.webp","emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado merengada 100ml protzen"},
 {"id":121,"code":"00487","name":"Helado Merengada 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/HELADOS/00487__HELADO_MERENGADA_460ML_PROTZEN.webp","emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado merengada 460ml protzen"},
 {"id":122,"code":"00491","name":"Helado Moka Fuel 100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado moka fuel 100ml protzen"},
 {"id":123,"code":"00485","name":"Helado Moka Fuel 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado moka fuel 460ml protzen"},
 {"id":124,"code":"00486","name":"Helado Pistacho 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado pistacho 460ml protzen"},
 {"id":125,"code":"00492","name":"Helado Pistacho100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado pistacho100ml protzen"},
 {"id":126,"code":"00495","name":"Helado Vainilla 100ml Protzen","category":"Helados","price":2.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado vainilla 100ml protzen"},
 {"id":127,"code":"00489","name":"Helado Vainilla 460ml Protzen","category":"Helados","price":7.99,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍦","customizable":false,"brand":"Protzen","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"200 - helados","pdfDescription":"helado vainilla 460ml protzen"},
 {"id":128,"code":"00086","name":"Bolw Grande","category":"Bowls","price":5.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"6 - No existe...","pdfDescription":"bolw grande"},
 {"id":129,"code":"00085","name":"Bolw Mediano","category":"Bowls","price":4.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"6 - No existe...","pdfDescription":"bolw mediano"},
 {"id":130,"code":"00084","name":"Bolw Pequeño","category":"Bowls","price":3.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍧","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"6 - No existe...","pdfDescription":"bolw pequeño"},
 {"id":131,"code":"00320","name":"Ashwagandha 60cps Protella","category":"Vitaminas y salud","price":22.95,"stock":8,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00320__ASHWAGANDHA_60CPS_PROTELLA.webp","emoji":"🌿","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"ashwagandha 60cps protella"},
 {"id":132,"code":"00311","name":"Barrita Proteina Fudge Brownie 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00311__BARRITA_PROTEINA_FUDGE_BROWNIE_16G_BAREBELLS.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina fudge brownie 16g barebells"},
 {"id":133,"code":"00304","name":"Barrita Proteina Lemon Cheesecake 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina lemon cheesecake 16g barebells"},
 {"id":134,"code":"00307","name":"Barrita Proteina Peanut Butter 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":9,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00307__BARRITA_PROTEINA_PEANUT_BUTTER_16G_BAREBELLS.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina peanut butter 16g barebells"},
 {"id":135,"code":"00306","name":"Barrita Proteina Peanut Caramel 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":11,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00306__BARRITA_PROTEINA_PEANUT_CARAMEL_16G_BAREBELLS.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina peanut caramel 16g barebells"},
 {"id":136,"code":"00305","name":"Barrita Proteina Peanut Cloud 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00305__BARRITA_PROTEINA_PEANUT_CLOUD_16G_BAREBELLS.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina peanut cloud 16g barebells"},
 {"id":137,"code":"00309","name":"Barrita Proteina Salty Peanut 16g Barebells 73","category":"Barritas y snacks","price":2.75,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00309__BARRITA_PROTEINA_SALTY_PEANUT_16G_BAREBELLS_73.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina salty peanut 16g barebells 73"},
 {"id":138,"code":"00310","name":"Barrita Proteina Strawberry Sundae 16g Barebells","category":"Barritas y snacks","price":2.75,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina strawberry sundae 16g barebells"},
 {"id":139,"code":"00308","name":"Barrita Proteina White Chocolate 16g Barebells","category":"Barritas y snacks","price":3.33,"stock":12,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/BARRITAS_Y_SNACKS/00308__BARRITA_PROTEINA_WHITE_CHOCOLATE_16G_BAREBELLS.webp","emoji":"🍫","customizable":false,"brand":"Barebells","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"barrita proteina white chocolate 16g barebells"},
 {"id":140,"code":"00292","name":"BCAA Glutamina Limon 500g Amro","category":"Proteínas","price":39.9,"stock":4,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00292__BCAA_GLUTAMINA_LIMON_500G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"bcaa glutamina limon 500g amro"},
 {"id":141,"code":"00291","name":"BCAA Glutamina Watermelon 500g Amro","category":"Proteínas","price":39.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00291__BCAA_GLUTAMINA_WATERMELON_500G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"bcaa glutamina watermelon 500g amro"},
 {"id":142,"code":"00331","name":"Colageno Mango 180g Protella","category":"Colágeno y bienestar","price":19.95,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"✨","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"colageno mango 180g protella"},
 {"id":143,"code":"00333","name":"Colageno Neutro 200g Protella","category":"Colágeno y bienestar","price":19.95,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/COLAGENO_Y_BIENESTAR/00333__COLAGENO_NEUTRO_200G_PROTELLA.webp","emoji":"✨","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"colageno neutro 200g protella"},
 {"id":144,"code":"00332","name":"Colageno Sandia 180g Protella","category":"Colágeno y bienestar","price":19.95,"stock":3,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/COLAGENO_Y_BIENESTAR/00332__COLAGENO_SANDIA_180G_PROTELLA.webp","emoji":"✨","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"colageno sandia 180g protella"},
 {"id":145,"code":"00334","name":"Creatina Monohydrate Lollipop 300g Protella","category":"Creatinas","price":16.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/CREATINAS/00334__CREATINA_MONOHYDRATE_LOLLIPOP_300G_PROTELLA.webp","emoji":"💪","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"creatina monohydrate lollipop 300g protella"},
 {"id":146,"code":"00335","name":"Creatina Monohydrate Melon Gum,300g Protella","category":"Creatinas","price":16.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"💪","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"creatina monohydrate melon gum,300g protella"},
 {"id":147,"code":"00295","name":"Creatina Micronized Natural 500g Amro","category":"Creatinas","price":34.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/CREATINAS/00295__CREATINA_MICRONIZED_NATURAL_500G_AMRO.jpg","emoji":"💪","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"creatina micronized natural 500g amro"},
 {"id":148,"code":"00345","name":"Creatina Monohydrate 300g Protella","category":"Creatinas","price":16.9,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"💪","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"creatina monohydrate 300g protella"},
 {"id":149,"code":"00337","name":"Crema De Arroz Cookie Dough 500g Protella","category":"Alimentación proteica","price":12.5,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"crema de arroz cookie dough 500g protella"},
 {"id":150,"code":"00336","name":"Crema De Arroz Speculoos 500g Protella","category":"Alimentación proteica","price":12.5,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"crema de arroz speculoos 500g protella"},
 {"id":151,"code":"00339","name":"Crema De Arroz Chocolatte 500g Protella","category":"Alimentación proteica","price":12.5,"stock":3,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00339__CREMA_DE_ARROZ_CHOCOLATTE_500G_PROTELLA.webp","emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"crema de arroz chocolatte 500g protella"},
 {"id":152,"code":"00338","name":"Crema De Arroz Peanut 500g Protella","category":"Alimentación proteica","price":12.5,"stock":3,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"crema de arroz peanut 500g protella"},
 {"id":153,"code":"00321","name":"Daily One 60caps Amro","category":"Vitaminas y salud","price":18.9,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00321__DAILY_ONE_60CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"daily one 60caps AMRO"},
 {"id":154,"code":"00323","name":"Diurex XT 120 caps Amro","category":"Vitaminas y salud","price":34.9,"stock":4,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00323__DIUREX_XT_120_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"diurex xt 120 caps AMRO"},
 {"id":155,"code":"00294","name":"F-22 Raptor Pre- Entreno Piña/mango 400g Amro","category":"Pre-entrenos","price":39.9,"stock":11,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PRE_ENTRENOS/00294__F_22_RAPTOR_PRE_ENTRENO_PINA_MANGO_400G_AMRO.jpg","emoji":"⚡","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"F-22 Raptor pre- entreno piña/mango 400g amro"},
 {"id":156,"code":"00343","name":"Harina De Avena Black Cookies 1000g Amro","category":"Alimentación proteica","price":6.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00343__HARINA_DE_AVENA_BLACK_COOKIES_1000G_AMRO.jpg","emoji":"🥣","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"harina de avena black cookies 1000g AMRO"},
 {"id":157,"code":"00342","name":"Harina De Avena Brownie 1000g Amro","category":"Alimentación proteica","price":6.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00342__HARINA_DE_AVENA_BROWNIE_1000G_AMRO.jpg","emoji":"🥣","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"harina de avena brownie 1000g AMRO"},
 {"id":158,"code":"00344","name":"Harina De Avena Chocolate Blanco 1000g Amro","category":"Alimentación proteica","price":6.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00344__HARINA_DE_AVENA_CHOCOLATE_BLANCO_1000G_AMRO.jpg","emoji":"🥣","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"harina de avena chocolate blanco 1000g AMRO"},
 {"id":159,"code":"00293","name":"M.A.P Kojak 500g Amro","category":"Proteínas","price":54.9,"stock":7,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00293__M_A_P_KOJAK_500G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"M.A.P kojak 500g amro"},
 {"id":160,"code":"00322","name":"Magnesium + Vitamina B6 100 caps Amro","category":"Vitaminas y salud","price":17.9,"stock":4,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00322__MAGNESIUM_VITAMINA_B6_100_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"magnesium + vitamina B6 100 caps AMRO"},
 {"id":161,"code":"00298","name":"Mermelada Melocoton Protella 170g","category":"Alimentación proteica","price":3.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"mermelada melocoton protella 170g"},
 {"id":162,"code":"00299","name":"Mermelada Strawberry Protella 170g","category":"Alimentación proteica","price":3.5,"stock":5,"badge":null,"badgeColor":"","featured":false,"image":null,"emoji":"🥣","customizable":false,"brand":"Protella","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"mermelada strawberry protella 170g"},
 {"id":163,"code":"00362","name":"NABE Aloe Vera Sunny Mango","category":"Vitaminas y salud","price":2.5,"stock":20,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00362__NABE_ALOE_VERA_SUNNY_MANGO.webp","emoji":"🌿","customizable":false,"brand":"NABE","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"NABE aloe vera sunny MANGO"},
 {"id":164,"code":"00290","name":"Proteina Isolate Strawberry 1kg Amro","category":"Proteínas","price":49.5,"stock":0,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00290__PROTEINA_ISOLATE_STRAWBERRY_1KG_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina isolate strawberry 1kg amro"},
 {"id":165,"code":"00297","name":"Proteina Whey Chocolate 1kg Amro","category":"Proteínas","price":39.9,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00297__PROTEINA_WHEY_CHOCOLATE_1KG_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina whey chocolate 1kg amro"},
 {"id":166,"code":"00318","name":"Proteina Whey 100% Chocolate 2000g Amro","category":"Proteínas","price":74.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00318__PROTEINA_WHEY_100_CHOCOLATE_2000G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina whey 100% chocolate 2000g AMRO"},
 {"id":167,"code":"00316","name":"Proteina Whey 100% Strawberry 2000g Amro","category":"Proteínas","price":74.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00316__PROTEINA_WHEY_100_STRAWBERRY_2000G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina whey 100% strawberry 2000g AMRO"},
 {"id":168,"code":"00317","name":"Proteina Whey 100% Vainilla 2000g Amro","category":"Proteínas","price":74.9,"stock":2,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00317__PROTEINA_WHEY_100_VAINILLA_2000G_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina whey 100% vainilla 2000g AMRO"},
 {"id":169,"code":"00296","name":"Proteina Whey Vainilla 1kg Amro","category":"Proteínas","price":39.9,"stock":1,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/PROTEINAS/00296__PROTEINA_WHEY_VAINILLA_1KG_AMRO.jpg","emoji":"🥛","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"proteina whey vainilla 1kg amro"},
 {"id":170,"code":"00324","name":"Volcano Thermogenic 90 caps Amro","category":"Vitaminas y salud","price":37.9,"stock":4,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/00324__VOLCANO_THERMOGENIC_90_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"9 - No existe...","pdfDescription":"volcano thermogenic 90 caps AMRO"},
 {"id":171,"code":"AMRO-CREAPURE-500","name":"Creatina Creapure Neutro 500g Amro","category":"Creatinas","price":44.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/CREATINAS/AMRO-CREAPURE-500__CREATINA_CREAPURE_NEUTRO_500G_AMRO.jpg","emoji":"💪","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":172,"code":"AMRO-LCARN2000-90","name":"L-Carnitine 2000 Carnipure 90 caps Amro","category":"Vitaminas y salud","price":24.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-LCARN2000-90__L_CARNITINE_2000_CARNIPURE_90_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":173,"code":"AMRO-LCARN3000-500","name":"L-Carnitine 3000 Limon 500ml Amro","category":"Vitaminas y salud","price":29.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-LCARN3000-500__L_CARNITINE_3000_LIMON_500ML_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":174,"code":"AMRO-LCARN3000-20","name":"L-Carnitine 3000 Limon 20 x 25ml Amro","category":"Vitaminas y salud","price":34.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-LCARN3000-20__L_CARNITINE_3000_LIMON_20_X_25ML_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":175,"code":"AMRO-ANABOL-90","name":"Anabol Pro 90 caps Amro","category":"Vitaminas y salud","price":39.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-ANABOL-90__ANABOL_PRO_90_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":176,"code":"AMRO-OMEGA3-90","name":"Super Omega 3 35/25 90 perlas Amro","category":"Vitaminas y salud","price":28.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-OMEGA3-90__SUPER_OMEGA_3_35_25_90_PERLAS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":177,"code":"AMRO-VITC1000-100","name":"Vitamin C 1000 100 caps Amro","category":"Vitaminas y salud","price":24.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-VITC1000-100__VITAMIN_C_1000_100_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":178,"code":"AMRO-NAC-120","name":"NAC 120 caps Amro","category":"Vitaminas y salud","price":23.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/VITAMINAS_Y_SALUD/AMRO-NAC-120__NAC_120_CAPS_AMRO.jpg","emoji":"🌿","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":179,"code":"AMRO-COLAGENO-400","name":"Colageno Limon 400g Amro","category":"Colágeno y bienestar","price":29.9,"stock":10,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/COLAGENO_Y_BIENESTAR/AMRO-COLAGENO-400__COLAGENO_LIMON_400G_AMRO.jpg","emoji":"✨","customizable":false,"brand":"Amro","description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Excel PVPR distribuidor AMRO","pdfDescription":null},
 {"id":180,"code":"00100","name":"Tarta de Queso","category":"Alimentación proteica","price":5.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/ALIMENTACION_PROTEICA/00100__TARTA_DE_QUESO.webp","emoji":"🥣","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Alta manual (hoja/panel)","pdfDescription":null},
 {"id":181,"code":"000541","name":"creatina monohidratada 300g","category":"Creatinas","price":32.5,"stock":null,"badge":null,"badgeColor":"","featured":false,"image":"sources/productos/CREATINAS/000541__CREATINA_MONOHIDRATADA_300G.webp","emoji":"💪","customizable":false,"brand":null,"description":null,"rating":0,"reviews":0,"active":true,"sourceFamily":"Alta manual (hoja/panel)","pdfDescription":null}
];

})(typeof module !== 'undefined' && module.exports ? module.exports : window);
