// AUTO-GENERADO desde el catálogo real AMIX — no editar a mano.
// 160 productos con PVP reales y sus imágenes.
window.NUTRETIUM_PRODUCTS = [
 {
  "id": 1,
  "code": "110",
  "name": "WHEY-PRO Fusion SACO 500 GR",
  "category": "Proteínas",
  "price": 30.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__110__WHEY_PRO_FUSION_SACO_500_GR__PVP_30_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "WHEY-PRO Fusion SACO 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 250,
  "active": true
 },
 {
  "id": 2,
  "code": "100",
  "name": "Isoprime CFM Isolate SACO 500 GR",
  "category": "Proteínas",
  "price": 36.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__100__ISOPRIME_CFM_ISOLATE_SACO_500_GR__PVP_36_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Isoprime CFM Isolate SACO 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 170,
  "active": true
 },
 {
  "id": 3,
  "code": "135",
  "name": "Clear ISO WHEY SACO 500 GR",
  "category": "Proteínas",
  "price": 38.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__135__CLEAR_ISO_WHEY_SACO_500_GR__PVP_38_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Clear ISO WHEY SACO 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 353,
  "active": true
 },
 {
  "id": 4,
  "code": "117",
  "name": "WHEY-PRO Fusion 700 GR Natural",
  "category": "Proteínas",
  "price": 41.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__117__WHEY_PRO_FUSION_700_GR_NATURAL__PVP_41_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "WHEY-PRO Fusion 700 GR Natural. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 390,
  "active": true
 },
 {
  "id": 5,
  "code": "131",
  "name": "Predator Protein 1 KG",
  "category": "Proteínas",
  "price": 41.7,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__131__PREDATOR_PROTEIN_1_KG__PVP_41_70_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Predator Protein 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 280,
  "active": true
 },
 {
  "id": 6,
  "code": "196",
  "name": "Gourmet Protein 1 KG",
  "category": "Proteínas",
  "price": 50.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__196__GOURMET_PROTEIN_1_KG__PVP_50_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Gourmet Protein 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 338,
  "active": true
 },
 {
  "id": 7,
  "code": "171",
  "name": "Monster BEEF Protein 1 KG",
  "category": "Proteínas",
  "price": 52.0,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__171__MONSTER_BEEF_PROTEIN_1_KG__PVP_52_00_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Monster BEEF Protein 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 222,
  "active": true
 },
 {
  "id": 8,
  "code": "161",
  "name": "Micellar Casein 1 KG",
  "category": "Proteínas",
  "price": 52.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__161__MICELLAR_CASEIN_1_KG__PVP_52_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Micellar Casein 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 424,
  "active": true
 },
 {
  "id": 9,
  "code": "111",
  "name": "WHEY-PRO Fusion 1 KG",
  "category": "Proteínas",
  "price": 53.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__111__WHEY_PRO_FUSION_1_KG__PVP_53_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "WHEY-PRO Fusion 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 327,
  "active": true
 },
 {
  "id": 10,
  "code": "141",
  "name": "Nightpro Elite 1 KG",
  "category": "Proteínas",
  "price": 61.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__141__NIGHTPRO_ELITE_1_KG__PVP_61_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Nightpro Elite 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 216,
  "active": true
 },
 {
  "id": 11,
  "code": "101",
  "name": "Isoprime CFM Isolate 1 KG",
  "category": "Proteínas",
  "price": 64.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__101__ISOPRIME_CFM_ISOLATE_1_KG__PVP_64_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Isoprime CFM Isolate 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 292,
  "active": true
 },
 {
  "id": 12,
  "code": "136",
  "name": "Clear ISO WHEY 1 KG",
  "category": "Proteínas",
  "price": 69.5,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__136__CLEAR_ISO_WHEY_1_KG__PVP_69_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Clear ISO WHEY 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 113,
  "active": true
 },
 {
  "id": 13,
  "code": "132",
  "name": "Predator Protein 2 KG",
  "category": "Proteínas",
  "price": 74.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__132__PREDATOR_PROTEIN_2_KG__PVP_74_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Predator Protein 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 269,
  "active": true
 },
 {
  "id": 14,
  "code": "194",
  "name": "Hydrobeef Protein 2 KG",
  "category": "Proteínas",
  "price": 91.6,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__194__HYDROBEEF_PROTEIN_2_KG__PVP_91_60_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Hydrobeef Protein 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 27,
  "active": true
 },
 {
  "id": 15,
  "code": "112",
  "name": "WHEY-PRO Fusion 2,3 KG",
  "category": "Proteínas",
  "price": 92.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__112__WHEY_PRO_FUSION_2_3_KG__PVP_92_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "WHEY-PRO Fusion 2,3 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 145,
  "active": true
 },
 {
  "id": 16,
  "code": "172",
  "name": "Monster BEEF 2 KG+200 GR FREE",
  "category": "Proteínas",
  "price": 98.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__172__MONSTER_BEEF_2_KG_200_GR_FREE__PVP_98_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Monster BEEF 2 KG+200 GR FREE. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 69,
  "active": true
 },
 {
  "id": 17,
  "code": "195",
  "name": "Hydropure WHEY CFM 1600 GR",
  "category": "Proteínas",
  "price": 104.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__195__HYDROPURE_WHEY_CFM_1600_GR__PVP_104_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Hydropure WHEY CFM 1600 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 46,
  "active": true
 },
 {
  "id": 18,
  "code": "192",
  "name": "Anabolic Monster WHEY 2 KG",
  "category": "Proteínas",
  "price": 108.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__192__ANABOLIC_MONSTER_WHEY_2_KG__PVP_108_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Anabolic Monster WHEY 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 52,
  "active": true
 },
 {
  "id": 19,
  "code": "102",
  "name": "Isoprime CFM Isolate 2 KG",
  "category": "Proteínas",
  "price": 111.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__102__ISOPRIME_CFM_ISOLATE_2_KG__PVP_111_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Isoprime CFM Isolate 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 100,
  "active": true
 },
 {
  "id": 20,
  "code": "134",
  "name": "Predator Protein 4 KG",
  "category": "Proteínas",
  "price": 118.5,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__134__PREDATOR_PROTEIN_4_KG__PVP_118_50_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "Predator Protein 4 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 455,
  "active": true
 },
 {
  "id": 21,
  "code": "114",
  "name": "WHEY-PRO Fusion 4 KG",
  "category": "Proteínas",
  "price": 165.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PROTEINAS/PROTEINAS__114__WHEY_PRO_FUSION_4_KG__PVP_165_90_EUR.webp",
  "emoji": "🥛",
  "customizable": false,
  "brand": "Amix",
  "description": "WHEY-PRO Fusion 4 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 91,
  "active": true
 },
 {
  "id": 22,
  "code": "3111",
  "name": "GLUTAMINE+BCAA 300 GR",
  "category": "Aminoácidos",
  "price": 23.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__3111__GLUTAMINE_BCAA_300_GR__PVP_23_70_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "GLUTAMINE+BCAA 300 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 263,
  "active": true
 },
 {
  "id": 23,
  "code": "399",
  "name": "L-GLUTAMINE Powder Drink 360 GR",
  "category": "Aminoácidos",
  "price": 25.9,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__399__L_GLUTAMINE_POWDER_DRINK_360_GR__PVP_25_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "L-GLUTAMINE Powder Drink 360 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 398,
  "active": true
 },
 {
  "id": 24,
  "code": "394",
  "name": "L-LEUCINE PURE 1000 MG 120 CAPS",
  "category": "Aminoácidos",
  "price": 26.0,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__394__L_LEUCINE_PURE_1000_MG_120_CAPS__PVP_26_00_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "L-LEUCINE PURE 1000 MG 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 381,
  "active": true
 },
 {
  "id": 25,
  "code": "301",
  "name": "BCAA Elite RATE 120 CAPS",
  "category": "Aminoácidos",
  "price": 28.5,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__301__BCAA_ELITE_RATE_120_CAPS__PVP_28_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BCAA Elite RATE 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 232,
  "active": true
 },
 {
  "id": 26,
  "code": "351",
  "name": "L-LYSINE 600 MG 120 CAPS",
  "category": "Aminoácidos",
  "price": 28.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__351__L_LYSINE_600_MG_120_CAPS__PVP_28_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "L-LYSINE 600 MG 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 284,
  "active": true
 },
 {
  "id": 27,
  "code": "393",
  "name": "L-TRYPTOPHAN 90 CAPS",
  "category": "Aminoácidos",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__393__L_TRYPTOPHAN_90_CAPS__PVP_29_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "L-TRYPTOPHAN 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 419,
  "active": true
 },
 {
  "id": 28,
  "code": "396",
  "name": "Amino Pills 330 TABL.",
  "category": "Aminoácidos",
  "price": 30.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__396__AMINO_PILLS_330_TABL__PVP_30_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Amino Pills 330 TABL.. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 38,
  "active": true
 },
 {
  "id": 29,
  "code": "341",
  "name": "Arginine 120 CAPS",
  "category": "Aminoácidos",
  "price": 31.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__341__ARGININE_120_CAPS__PVP_31_70_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Arginine 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 436,
  "active": true
 },
 {
  "id": 30,
  "code": "303",
  "name": "BCAA EN Polvo 350 GR",
  "category": "Aminoácidos",
  "price": 36.5,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__303__BCAA_EN_POLVO_350_GR__PVP_36_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BCAA EN Polvo 350 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 249,
  "active": true
 },
 {
  "id": 31,
  "code": "311",
  "name": "GLUTAMINE+BCAA 530 GR",
  "category": "Aminoácidos",
  "price": 39.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__311__GLUTAMINE_BCAA_530_GR__PVP_39_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "GLUTAMINE+BCAA 530 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 352,
  "active": true
 },
 {
  "id": 32,
  "code": "312",
  "name": "GLUTAMINE+BCAA 360 CAPS",
  "category": "Aminoácidos",
  "price": 39.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__312__GLUTAMINE_BCAA_360_CAPS__PVP_39_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "GLUTAMINE+BCAA 360 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 101,
  "active": true
 },
 {
  "id": 33,
  "code": "321",
  "name": "BEEF Extra Amino 360 CAPS",
  "category": "Aminoácidos",
  "price": 40.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__321__BEEF_EXTRA_AMINO_360_CAPS__PVP_40_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BEEF Extra Amino 360 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 118,
  "active": true
 },
 {
  "id": 34,
  "code": "332",
  "name": "Glutamine 360 CAPS",
  "category": "Aminoácidos",
  "price": 41.9,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__332__GLUTAMINE_360_CAPS__PVP_41_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Glutamine 360 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 123,
  "active": true
 },
 {
  "id": 35,
  "code": "331",
  "name": "Glutamine 500 GR",
  "category": "Aminoácidos",
  "price": 42.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__331__GLUTAMINE_500_GR__PVP_42_00_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Glutamine 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 420,
  "active": true
 },
 {
  "id": 36,
  "code": "308",
  "name": "Amino HYDRO-32 250 TABL.",
  "category": "Aminoácidos",
  "price": 44.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__308__AMINO_HYDRO_32_250_TABL__PVP_44_00_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Amino HYDRO-32 250 TABL.. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 88,
  "active": true
 },
 {
  "id": 37,
  "code": "307",
  "name": "BCAA GOLD 2:1:1 300 TABL.",
  "category": "Aminoácidos",
  "price": 45.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__307__BCAA_GOLD_2_1_1_300_TABL__PVP_45_50_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BCAA GOLD 2:1:1 300 TABL.. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 239,
  "active": true
 },
 {
  "id": 38,
  "code": "306",
  "name": "Recovery MAX 575 GR",
  "category": "Aminoácidos",
  "price": 47.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__306__RECOVERY_MAX_575_GR__PVP_47_70_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Recovery MAX 575 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 191,
  "active": true
 },
 {
  "id": 39,
  "code": "361",
  "name": "BEEF Amino 250 Tablets",
  "category": "Aminoácidos",
  "price": 48.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__361__BEEF_AMINO_250_TABLETS__PVP_48_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BEEF Amino 250 Tablets. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 263,
  "active": true
 },
 {
  "id": 40,
  "code": "310",
  "name": "BCAA Instant Juice 500 GR",
  "category": "Aminoácidos",
  "price": 50.9,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__310__BCAA_INSTANT_JUICE_500_GR__PVP_50_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "BCAA Instant Juice 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 355,
  "active": true
 },
 {
  "id": 41,
  "code": "3110",
  "name": "GLUTAMINE+BCAA 1 KG",
  "category": "Aminoácidos",
  "price": 72.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__3110__GLUTAMINE_BCAA_1_KG__PVP_72_90_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "GLUTAMINE+BCAA 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 232,
  "active": true
 },
 {
  "id": 42,
  "code": "333",
  "name": "Glutamine 1 KG",
  "category": "Aminoácidos",
  "price": 79.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/AMINOACIDOS/AMINOACIDOS__333__GLUTAMINE_1_KG__PVP_79_00_EUR.webp",
  "emoji": "🧬",
  "customizable": false,
  "brand": "Amix",
  "description": "Glutamine 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 359,
  "active": true
 },
 {
  "id": 43,
  "code": "405",
  "name": "Creatine Monohydrate Drink 360 GR",
  "category": "Creatinas",
  "price": 32.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__405__CREATINE_MONOHYDRATE_DRINK_360_GR__PVP_32_20_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "Creatine Monohydrate Drink 360 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 93,
  "active": true
 },
 {
  "id": 44,
  "code": "CREAT300",
  "name": "Creatine Monohydrate 300 GR",
  "category": "Creatinas",
  "price": 32.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__CREAT300__CREATINE_MONOHYDRATE_300_GR__PVP_32_20_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "Creatine Monohydrate 300 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 48,
  "active": true
 },
 {
  "id": 45,
  "code": "403",
  "name": "Creatine Monohydrate 220 CAPS",
  "category": "Creatinas",
  "price": 40.9,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__403__CREATINE_MONOHYDRATE_220_CAPS__PVP_40_90_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "Creatine Monohydrate 220 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 417,
  "active": true
 },
 {
  "id": 46,
  "code": "411",
  "name": "Krealkalyn 120 CAPS+30 FREE",
  "category": "Creatinas",
  "price": 41.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__411__KREALKALYN_120_CAPS_30_FREE__PVP_41_70_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "Krealkalyn 120 CAPS+30 FREE. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 254,
  "active": true
 },
 {
  "id": 47,
  "code": "404",
  "name": "Creatine 500 GR +250 GR FREE",
  "category": "Creatinas",
  "price": 53.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__404__CREATINE_500_GR_250_GR_FREE__PVP_53_90_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "Creatine 500 GR +250 GR FREE. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 384,
  "active": true
 },
 {
  "id": 48,
  "code": "431",
  "name": "CREA-TRIX 824 GR",
  "category": "Creatinas",
  "price": 60.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CREATINAS/CREATINAS__431__CREA_TRIX_824_GR__PVP_60_30_EUR.webp",
  "emoji": "💪",
  "customizable": false,
  "brand": "Amix",
  "description": "CREA-TRIX 824 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 237,
  "active": true
 },
 {
  "id": 49,
  "code": "512",
  "name": "Nitric Oxide 120 CAPS",
  "category": "Voluminizadores",
  "price": 35.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__512__NITRIC_OXIDE_120_CAPS__PVP_35_70_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "Nitric Oxide 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 265,
  "active": true
 },
 {
  "id": 50,
  "code": "502",
  "name": "AAKG SHOT 4000 MG 20*60 ML",
  "category": "Voluminizadores",
  "price": 36.0,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__502__AAKG_SHOT_4000_MG_20_60_ML__PVP_36_00_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "AAKG SHOT 4000 MG 20*60 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 323,
  "active": true
 },
 {
  "id": 51,
  "code": "511",
  "name": "Nitric 125 CAPS",
  "category": "Voluminizadores",
  "price": 42.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__511__NITRIC_125_CAPS__PVP_42_70_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "Nitric 125 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 292,
  "active": true
 },
 {
  "id": 52,
  "code": "541",
  "name": "Cellzoom 315 GR",
  "category": "Voluminizadores",
  "price": 53.5,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__541__CELLZOOM_315_GR__PVP_53_50_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "Cellzoom 315 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 72,
  "active": true
 },
 {
  "id": 53,
  "code": "531",
  "name": "Cellumax 1,8 KG",
  "category": "Voluminizadores",
  "price": 59.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__531__CELLUMAX_1_8_KG__PVP_59_20_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "Cellumax 1,8 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 401,
  "active": true
 },
 {
  "id": 54,
  "code": "514",
  "name": "Nitric 350 CAPS",
  "category": "Voluminizadores",
  "price": 73.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VOLUMINIZADORES/VOLUMINIZADORES__514__NITRIC_350_CAPS__PVP_73_50_EUR.webp",
  "emoji": "🏋️",
  "customizable": false,
  "brand": "Amix",
  "description": "Nitric 350 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 460,
  "active": true
 },
 {
  "id": 55,
  "code": "230",
  "name": "Anabolic Masster SACO 500 GR",
  "category": "Carbohidratos",
  "price": 23.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__230__ANABOLIC_MASSTER_SACO_500_GR__PVP_23_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Anabolic Masster SACO 500 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 464,
  "active": true
 },
 {
  "id": 56,
  "code": "262",
  "name": "WAXYGO! 2 KG",
  "category": "Carbohidratos",
  "price": 34.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__262__WAXYGO_2_KG__PVP_34_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "WAXYGO! 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 80,
  "active": true
 },
 {
  "id": 57,
  "code": "243",
  "name": "Carbojet Basic 3 KG",
  "category": "Carbohidratos",
  "price": 36.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__243__CARBOJET_BASIC_3_KG__PVP_36_30_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Carbojet Basic 3 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 172,
  "active": true
 },
 {
  "id": 58,
  "code": "202",
  "name": "Carbojet GAIN 2,25 KG",
  "category": "Carbohidratos",
  "price": 40.5,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__202__CARBOJET_GAIN_2_25_KG__PVP_40_50_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Carbojet GAIN 2,25 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 393,
  "active": true
 },
 {
  "id": 59,
  "code": "251",
  "name": "Carbojet MASS Professional 1800 GR",
  "category": "Carbohidratos",
  "price": 40.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__251__CARBOJET_MASS_PROFESSIONAL_1800_GR__PVP_40_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Carbojet MASS Professional 1800 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 171,
  "active": true
 },
 {
  "id": 60,
  "code": "211",
  "name": "Vitargo LOAD 1 KG",
  "category": "Carbohidratos",
  "price": 41.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__211__VITARGO_LOAD_1_KG__PVP_41_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Vitargo LOAD 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 69,
  "active": true
 },
 {
  "id": 61,
  "code": "204",
  "name": "Carbojet GAIN 4 KG",
  "category": "Carbohidratos",
  "price": 64.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__204__CARBOJET_GAIN_4_KG__PVP_64_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Carbojet GAIN 4 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 356,
  "active": true
 },
 {
  "id": 62,
  "code": "212",
  "name": "Vitargo LOAD 2 KG",
  "category": "Carbohidratos",
  "price": 65.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__212__VITARGO_LOAD_2_KG__PVP_65_90_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Vitargo LOAD 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 276,
  "active": true
 },
 {
  "id": 63,
  "code": "222",
  "name": "VITARGO+KREALKALYN 2 KG",
  "category": "Carbohidratos",
  "price": 69.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__222__VITARGO_KREALKALYN_2_KG__PVP_69_50_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "VITARGO+KREALKALYN 2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 192,
  "active": true
 },
 {
  "id": 64,
  "code": "253",
  "name": "Carbojet MASS Professional 3 KG",
  "category": "Carbohidratos",
  "price": 70.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__253__CARBOJET_MASS_PROFESSIONAL_3_KG__PVP_70_50_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Carbojet MASS Professional 3 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 173,
  "active": true
 },
 {
  "id": 65,
  "code": "231",
  "name": "Anabolic Masster 2,2 KG",
  "category": "Carbohidratos",
  "price": 83.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO/CARBOHIDRATOS_Y_SUBIDORES_DE_PESO__231__ANABOLIC_MASSTER_2_2_KG__PVP_83_50_EUR.webp",
  "emoji": "🌾",
  "customizable": false,
  "brand": "Amix",
  "description": "Anabolic Masster 2,2 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 452,
  "active": true
 },
 {
  "id": 66,
  "code": "3006",
  "name": "Exclusive Protein BAR 12*85GR",
  "category": "Barritas y snacks",
  "price": 33.6,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3006__EXCLUSIVE_PROTEIN_BAR_12_85GR__PVP_33_60_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Exclusive Protein BAR 12*85GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 181,
  "active": true
 },
 {
  "id": 67,
  "code": "3001",
  "name": "Mcpro Protein BAR 24*35 GR",
  "category": "Barritas y snacks",
  "price": 34.8,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3001__MCPRO_PROTEIN_BAR_24_35_GR__PVP_34_80_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Mcpro Protein BAR 24*35 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 268,
  "active": true
 },
 {
  "id": 68,
  "code": "3007",
  "name": "Exclusive Protein BAR 24*40 GR",
  "category": "Barritas y snacks",
  "price": 36.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3007__EXCLUSIVE_PROTEIN_BAR_24_40_GR__PVP_36_00_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Exclusive Protein BAR 24*40 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 290,
  "active": true
 },
 {
  "id": 69,
  "code": "3009",
  "name": "ZERO HERO Protein BAR 15*65 GR",
  "category": "Barritas y snacks",
  "price": 36.75,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3009__ZERO_HERO_PROTEIN_BAR_15_65_GR__PVP_36_75_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "ZERO HERO Protein BAR 15*65 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 295,
  "active": true
 },
 {
  "id": 70,
  "code": "3014",
  "name": "Vegan Protein BAR 20*45 GR",
  "category": "Barritas y snacks",
  "price": 43.0,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3014__VEGAN_PROTEIN_BAR_20_45_GR__PVP_43_00_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Vegan Protein BAR 20*45 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 238,
  "active": true
 },
 {
  "id": 71,
  "code": "3011",
  "name": "Protein NUTS BAR 25*40 GR",
  "category": "Barritas y snacks",
  "price": 51.25,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3011__PROTEIN_NUTS_BAR_25_40_GR__PVP_51_25_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Protein NUTS BAR 25*40 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 220,
  "active": true
 },
 {
  "id": 72,
  "code": "3012",
  "name": "Tigger ZERO Protein BAR 20*60 GR",
  "category": "Barritas y snacks",
  "price": 55.0,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3012__TIGGER_ZERO_PROTEIN_BAR_20_60_GR__PVP_55_00_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Tigger ZERO Protein BAR 20*60 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 25,
  "active": true
 },
 {
  "id": 73,
  "code": "3013",
  "name": "Tigger Crunchy Protein BAR 20*60 GR",
  "category": "Barritas y snacks",
  "price": 55.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BARRITAS/BARRITAS__3013__TIGGER_CRUNCHY_PROTEIN_BAR_20_60_GR__PVP_55_00_EUR.webp",
  "emoji": "🍫",
  "customizable": false,
  "brand": "Amix",
  "description": "Tigger Crunchy Protein BAR 20*60 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 352,
  "active": true
 },
 {
  "id": 74,
  "code": "4900",
  "name": "AMIX L-CARNITINE Drink 24*250 ML Cereza",
  "category": "Bebidas",
  "price": 48.0,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4900__AMIX_L_CARNITINE_DRINK_24_250_ML_CEREZA__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX L-CARNITINE Drink 24*250 ML Cereza. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 216,
  "active": true
 },
 {
  "id": 75,
  "code": "4901",
  "name": "AMIX Sport Drink 24*250 ML Limón",
  "category": "Bebidas",
  "price": 48.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4901__AMIX_SPORT_DRINK_24_250_ML_LIMON__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Sport Drink 24*250 ML Limón. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 358,
  "active": true
 },
 {
  "id": 76,
  "code": "4902",
  "name": "AMIX Caffeine Drink 24*250 ML Naranja",
  "category": "Bebidas",
  "price": 48.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4902__AMIX_CAFFEINE_DRINK_24_250_ML_NARANJA__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Caffeine Drink 24*250 ML Naranja. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 332,
  "active": true
 },
 {
  "id": 77,
  "code": "4903",
  "name": "AMIX BCAA Drink 24*250 ML Tropical",
  "category": "Bebidas",
  "price": 48.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4903__AMIX_BCAA_DRINK_24_250_ML_TROPICAL__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX BCAA Drink 24*250 ML Tropical. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 348,
  "active": true
 },
 {
  "id": 78,
  "code": "4904",
  "name": "AMIX Collagene Drink 24*250 ML Té Y Limón",
  "category": "Bebidas",
  "price": 48.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4904__AMIX_COLLAGENE_DRINK_24_250_ML_TE_Y_LIMON__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Collagene Drink 24*250 ML Té Y Limón. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 179,
  "active": true
 },
 {
  "id": 79,
  "code": "4905",
  "name": "AMIX Antiox Drink 24*250 ML Frutos Rojos",
  "category": "Bebidas",
  "price": 48.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/BEBIDAS/BEBIDAS__4905__AMIX_ANTIOX_DRINK_24_250_ML_FRUTOS_ROJOS__PVP_48_00_EUR.webp",
  "emoji": "🥤",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Antiox Drink 24*250 ML Frutos Rojos. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 35,
  "active": true
 },
 {
  "id": 80,
  "code": "5001",
  "name": "Shake 4 FIT & SLIM 1 KG",
  "category": "Sustitutivos",
  "price": 41.7,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/SUSTITUTIVO_DE_COMIDAS/SUSTITUTIVO_DE_COMIDAS__5001__SHAKE_4_FIT_SLIM_1_KG__PVP_41_70_EUR.webp",
  "emoji": "🥣",
  "customizable": false,
  "brand": "Amix",
  "description": "Shake 4 FIT & SLIM 1 KG. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 311,
  "active": true
 },
 {
  "id": 81,
  "code": "932",
  "name": "Chromium Picolinate 200 MCG 100 CAPS",
  "category": "Vitaminas y minerales",
  "price": 14.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__932__CHROMIUM_PICOLINATE_200_MCG_100_CAPS__PVP_14_30_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Chromium Picolinate 200 MCG 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 102,
  "active": true
 },
 {
  "id": 82,
  "code": "901",
  "name": "Vitamina C 1000 MG 100 CAPS",
  "category": "Vitaminas y minerales",
  "price": 18.9,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__901__VITAMINA_C_1000_MG_100_CAPS__PVP_18_90_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Vitamina C 1000 MG 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 189,
  "active": true
 },
 {
  "id": 83,
  "code": "902",
  "name": "Daily ONE 60 TABL",
  "category": "Vitaminas y minerales",
  "price": 19.5,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__902__DAILY_ONE_60_TABL__PVP_19_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Daily ONE 60 TABL. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 479,
  "active": true
 },
 {
  "id": 84,
  "code": "936",
  "name": "Collagen Viscofan® Drink 300 GR",
  "category": "Vitaminas y minerales",
  "price": 24.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__936__COLLAGEN_VISCOFAN_DRINK_300_GR__PVP_24_30_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Collagen Viscofan® Drink 300 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 114,
  "active": true
 },
 {
  "id": 85,
  "code": "905",
  "name": "ALA - Alpha Lipoic ACID 60 CAPS",
  "category": "Vitaminas y minerales",
  "price": 26.0,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__905__ALA_ALPHA_LIPOIC_ACID_60_CAPS__PVP_26_00_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "ALA - Alpha Lipoic ACID 60 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 86,
  "active": true
 },
 {
  "id": 86,
  "code": "919",
  "name": "Osteo Glucosamine 1000 MG 90 CAPS",
  "category": "Vitaminas y minerales",
  "price": 26.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__919__OSTEO_GLUCOSAMINE_1000_MG_90_CAPS__PVP_26_00_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Osteo Glucosamine 1000 MG 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 443,
  "active": true
 },
 {
  "id": 87,
  "code": "903",
  "name": "Multi Megastack 120 TABL",
  "category": "Vitaminas y minerales",
  "price": 26.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__903__MULTI_MEGASTACK_120_TABL__PVP_26_90_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Multi Megastack 120 TABL. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 285,
  "active": true
 },
 {
  "id": 88,
  "code": "910",
  "name": "CALCIUM+MAGNESIUM&ZINK 100 TBL",
  "category": "Vitaminas y minerales",
  "price": 27.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__910__CALCIUM_MAGNESIUM_ZINK_100_TBL__PVP_27_30_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "CALCIUM+MAGNESIUM&ZINK 100 TBL. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 363,
  "active": true
 },
 {
  "id": 89,
  "code": "920",
  "name": "Psyllium PURE 1500 MG 120 CAPS",
  "category": "Vitaminas y minerales",
  "price": 27.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__920__PSYLLIUM_PURE_1500_MG_120_CAPS__PVP_27_30_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Psyllium PURE 1500 MG 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 287,
  "active": true
 },
 {
  "id": 90,
  "code": "929",
  "name": "PURE Resveratrol ANTI-OX 60 CAPS",
  "category": "Vitaminas y minerales",
  "price": 27.3,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__929__PURE_RESVERATROL_ANTI_OX_60_CAPS__PVP_27_30_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "PURE Resveratrol ANTI-OX 60 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 341,
  "active": true
 },
 {
  "id": 91,
  "code": "908",
  "name": "B Complex 90 CAPS",
  "category": "Vitaminas y minerales",
  "price": 28.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__908__B_COMPLEX_90_CAPS__PVP_28_70_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "B Complex 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 68,
  "active": true
 },
 {
  "id": 92,
  "code": "904",
  "name": "Osteo Gelatine 200 CAPS",
  "category": "Vitaminas y minerales",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__904__OSTEO_GELATINE_200_CAPS__PVP_29_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Osteo Gelatine 200 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 459,
  "active": true
 },
 {
  "id": 93,
  "code": "912",
  "name": "Enzymex Multi 90 CAPS",
  "category": "Vitaminas y minerales",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__912__ENZYMEX_MULTI_90_CAPS__PVP_29_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Enzymex Multi 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 448,
  "active": true
 },
 {
  "id": 94,
  "code": "921",
  "name": "Super Fiber 3 PLUS 90 CAPS",
  "category": "Vitaminas y minerales",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__921__SUPER_FIBER_3_PLUS_90_CAPS__PVP_29_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Super Fiber 3 PLUS 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 240,
  "active": true
 },
 {
  "id": 95,
  "code": "931",
  "name": "Multi HD 60 Liquid CAPS",
  "category": "Vitaminas y minerales",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__931__MULTI_HD_60_LIQUID_CAPS__PVP_29_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Multi HD 60 Liquid CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 231,
  "active": true
 },
 {
  "id": 96,
  "code": "909",
  "name": "Super Omega 3 90 CAPS",
  "category": "Vitaminas y minerales",
  "price": 29.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__909__SUPER_OMEGA_3_90_CAPS__PVP_29_90_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Super Omega 3 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 326,
  "active": true
 },
 {
  "id": 97,
  "code": "935",
  "name": "Bodyguard Ultimate Immunity Booster 120 CAPS",
  "category": "Vitaminas y minerales",
  "price": 32.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__935__BODYGUARD_ULTIMATE_IMMUNITY_BOOSTER_120_CAPS__PVP_32_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Bodyguard Ultimate Immunity Booster 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 393,
  "active": true
 },
 {
  "id": 98,
  "code": "915",
  "name": "LIFE´S Vitality 60 TABL",
  "category": "Vitaminas y minerales",
  "price": 33.5,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__915__LIFE_S_VITALITY_60_TABL__PVP_33_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "LIFE´S Vitality 60 TABL. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 417,
  "active": true
 },
 {
  "id": 99,
  "code": "925",
  "name": "Mellanox Sleep PLUS 120 CAPS",
  "category": "Vitaminas y minerales",
  "price": 35.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__925__MELLANOX_SLEEP_PLUS_120_CAPS__PVP_35_70_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Mellanox Sleep PLUS 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 97,
  "active": true
 },
 {
  "id": 100,
  "code": "928",
  "name": "Krill OIL 1000 MG 60 CAPS",
  "category": "Vitaminas y minerales",
  "price": 35.7,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__928__KRILL_OIL_1000_MG_60_CAPS__PVP_35_70_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Krill OIL 1000 MG 60 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 339,
  "active": true
 },
 {
  "id": 101,
  "code": "918",
  "name": "Osteo Ultra Joint Drink 600 GR",
  "category": "Vitaminas y minerales",
  "price": 40.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__918__OSTEO_ULTRA_JOINT_DRINK_600_GR__PVP_40_50_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Osteo Ultra Joint Drink 600 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 252,
  "active": true
 },
 {
  "id": 102,
  "code": "930",
  "name": "OPTI-PACK Osteo FLEX 30 Bolsas",
  "category": "Vitaminas y minerales",
  "price": 41.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__930__OPTI_PACK_OSTEO_FLEX_30_BOLSAS__PVP_41_70_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "OPTI-PACK Osteo FLEX 30 Bolsas. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 201,
  "active": true
 },
 {
  "id": 103,
  "code": "911",
  "name": "Osteo Anagenesis 120 CAPS",
  "category": "Vitaminas y minerales",
  "price": 44.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/VITAMINAS_MINERALES_ARTICULARES/VITAMINAS_MINERALES_ARTICULARES__911__OSTEO_ANAGENESIS_120_CAPS__PVP_44_00_EUR.webp",
  "emoji": "🌿",
  "customizable": false,
  "brand": "Amix",
  "description": "Osteo Anagenesis 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 174,
  "active": true
 },
 {
  "id": 104,
  "code": "716",
  "name": "AMIX Super FAT Burner Booster GEL 200 ML",
  "category": "Cosmética",
  "price": 32.5,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/COSMETICA/COSMETICA__716__AMIX_SUPER_FAT_BURNER_BOOSTER_GEL_200_ML__PVP_32_50_EUR.webp",
  "emoji": "🧴",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Super FAT Burner Booster GEL 200 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 473,
  "active": true
 },
 {
  "id": 105,
  "code": "717",
  "name": "AMIX Super ANTI-CELLULITE Booster GEL 200 ML",
  "category": "Cosmética",
  "price": 32.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/COSMETICA/COSMETICA__717__AMIX_SUPER_ANTI_CELLULITE_BOOSTER_GEL_200_ML__PVP_32_50_EUR.webp",
  "emoji": "🧴",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Super ANTI-CELLULITE Booster GEL 200 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 382,
  "active": true
 },
 {
  "id": 106,
  "code": "316",
  "name": "Peptide Pepform Arginine 90 CAPS",
  "category": "Péptidos",
  "price": 29.9,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PEPTIDOS/PEPTIDOS__316__PEPTIDE_PEPFORM_ARGININE_90_CAPS__PVP_29_90_EUR.webp",
  "emoji": "🧪",
  "customizable": false,
  "brand": "Amix",
  "description": "Peptide Pepform Arginine 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 303,
  "active": true
 },
 {
  "id": 107,
  "code": "318",
  "name": "Peptide Pepform Glutamine 90 CAPS",
  "category": "Péptidos",
  "price": 29.9,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PEPTIDOS/PEPTIDOS__318__PEPTIDE_PEPFORM_GLUTAMINE_90_CAPS__PVP_29_90_EUR.webp",
  "emoji": "🧪",
  "customizable": false,
  "brand": "Amix",
  "description": "Peptide Pepform Glutamine 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 116,
  "active": true
 },
 {
  "id": 108,
  "code": "319",
  "name": "Peptide Pepform BCAA 90 CAPS",
  "category": "Péptidos",
  "price": 29.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PEPTIDOS/PEPTIDOS__319__PEPTIDE_PEPFORM_BCAA_90_CAPS__PVP_29_90_EUR.webp",
  "emoji": "🧪",
  "customizable": false,
  "brand": "Amix",
  "description": "Peptide Pepform BCAA 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 452,
  "active": true
 },
 {
  "id": 109,
  "code": "808",
  "name": "Caffeine 200 MG WITH Taurine 90 CAPS",
  "category": "Energéticos",
  "price": 24.9,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__808__CAFFEINE_200_MG_WITH_TAURINE_90_CAPS__PVP_24_90_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Caffeine 200 MG WITH Taurine 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 276,
  "active": true
 },
 {
  "id": 110,
  "code": "8050",
  "name": "Citrulyn Powder 300 GR Neutro",
  "category": "Energéticos",
  "price": 25.9,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__8050__CITRULYN_POWDER_300_GR_NEUTRO__PVP_25_90_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Citrulyn Powder 300 GR Neutro. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 268,
  "active": true
 },
 {
  "id": 111,
  "code": "804",
  "name": "Inosine 100 CAPS",
  "category": "Energéticos",
  "price": 26.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__804__INOSINE_100_CAPS__PVP_26_30_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Inosine 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 405,
  "active": true
 },
 {
  "id": 112,
  "code": "801",
  "name": "Taurine 120 CAPS",
  "category": "Energéticos",
  "price": 27.2,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__801__TAURINE_120_CAPS__PVP_27_20_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Taurine 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 167,
  "active": true
 },
 {
  "id": 113,
  "code": "802",
  "name": "Coffitime 90 CAPS",
  "category": "Energéticos",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__802__COFFITIME_90_CAPS__PVP_29_50_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Coffitime 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 342,
  "active": true
 },
 {
  "id": 114,
  "code": "807",
  "name": "Carnosyn 600 MG 100 CAPS",
  "category": "Energéticos",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__807__CARNOSYN_600_MG_100_CAPS__PVP_29_50_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Carnosyn 600 MG 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 169,
  "active": true
 },
 {
  "id": 115,
  "code": "809",
  "name": "ATP Energy Liquid 10*25 ML",
  "category": "Energéticos",
  "price": 32.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__809__ATP_ENERGY_LIQUID_10_25_ML__PVP_32_00_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "ATP Energy Liquid 10*25 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 229,
  "active": true
 },
 {
  "id": 116,
  "code": "805",
  "name": "Citrulyn 750 MG 120 CAPS",
  "category": "Energéticos",
  "price": 32.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__805__CITRULYN_750_MG_120_CAPS__PVP_32_20_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Citrulyn 750 MG 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 68,
  "active": true
 },
 {
  "id": 117,
  "code": "890",
  "name": "Guarex Energy & Mental SHOT 20*60 ML",
  "category": "Energéticos",
  "price": 43.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__890__GUAREX_ENERGY_MENTAL_SHOT_20_60_ML__PVP_43_00_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "Guarex Energy & Mental SHOT 20*60 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 47,
  "active": true
 },
 {
  "id": 118,
  "code": "806",
  "name": "ATP Energy 90 CAPS",
  "category": "Energéticos",
  "price": 53.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ENERGETICOS/ENERGETICOS__806__ATP_ENERGY_90_CAPS__PVP_53_50_EUR.webp",
  "emoji": "⚡",
  "customizable": false,
  "brand": "Amix",
  "description": "ATP Energy 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 472,
  "active": true
 },
 {
  "id": 119,
  "code": "651",
  "name": "Diosgen 100 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__651__DIOSGEN_100_CAPS__PVP_29_50_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Diosgen 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 162,
  "active": true
 },
 {
  "id": 120,
  "code": "671",
  "name": "GH 120 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 29.5,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__671__GH_120_CAPS__PVP_29_50_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "GH 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 397,
  "active": true
 },
 {
  "id": 121,
  "code": "607",
  "name": "Gamma Oryzanol 120 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 30.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__607__GAMMA_ORYZANOL_120_CAPS__PVP_30_90_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Gamma Oryzanol 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 131,
  "active": true
 },
 {
  "id": 122,
  "code": "606",
  "name": "Peruvian MACA 120 CAPS.",
  "category": "Estimulantes de crecimiento",
  "price": 31.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__606__PERUVIAN_MACA_120_CAPS__PVP_31_90_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Peruvian MACA 120 CAPS.. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 319,
  "active": true
 },
 {
  "id": 123,
  "code": "604",
  "name": "Tribulyn 40 % 120 CAPS+100 CAPS FREE",
  "category": "Estimulantes de crecimiento",
  "price": 32.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__604__TRIBULYN_40_120_CAPS_100_CAPS_FREE__PVP_32_20_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Tribulyn 40 % 120 CAPS+100 CAPS FREE. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 200,
  "active": true
 },
 {
  "id": 124,
  "code": "631",
  "name": "Catuabolix 100 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 32.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__631__CATUABOLIX_100_CAPS__PVP_32_20_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Catuabolix 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 97,
  "active": true
 },
 {
  "id": 125,
  "code": "681",
  "name": "D-AA MAX PURE 100 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 35.6,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__681__D_AA_MAX_PURE_100_CAPS__PVP_35_60_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "D-AA MAX PURE 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 258,
  "active": true
 },
 {
  "id": 126,
  "code": "682",
  "name": "BETA-ECDYX 90 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 35.6,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__682__BETA_ECDYX_90_CAPS__PVP_35_60_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "BETA-ECDYX 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 289,
  "active": true
 },
 {
  "id": 127,
  "code": "602",
  "name": "Tribulyn 90 % 90 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 35.7,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__602__TRIBULYN_90_90_CAPS__PVP_35_70_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Tribulyn 90 % 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 138,
  "active": true
 },
 {
  "id": 128,
  "code": "621",
  "name": "ZMA 90 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 35.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__621__ZMA_90_CAPS__PVP_35_70_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "ZMA 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 349,
  "active": true
 },
 {
  "id": 129,
  "code": "605",
  "name": "TRIBU-ZMA 90 TABL.",
  "category": "Estimulantes de crecimiento",
  "price": 42.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__605__TRIBU_ZMA_90_TABL__PVP_42_90_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "TRIBU-ZMA 90 TABL.. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 459,
  "active": true
 },
 {
  "id": 130,
  "code": "601",
  "name": "Myosterones 90 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 47.7,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__601__MYOSTERONES_90_CAPS__PVP_47_70_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Myosterones 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 328,
  "active": true
 },
 {
  "id": 131,
  "code": "611",
  "name": "Anabolic Power Tribusten 200 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 53.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__611__ANABOLIC_POWER_TRIBUSTEN_200_CAPS__PVP_53_50_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Anabolic Power Tribusten 200 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 308,
  "active": true
 },
 {
  "id": 132,
  "code": "661",
  "name": "Anabolic Explosion 200 CAPS",
  "category": "Estimulantes de crecimiento",
  "price": 53.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/ESTIMULANTES_DE_CRECIMIENTO/ESTIMULANTES_DE_CRECIMIENTO__661__ANABOLIC_EXPLOSION_200_CAPS__PVP_53_50_EUR.webp",
  "emoji": "📈",
  "customizable": false,
  "brand": "Amix",
  "description": "Anabolic Explosion 200 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 175,
  "active": true
 },
 {
  "id": 133,
  "code": "718",
  "name": "Synephrine 20 MG 90 Vcaps",
  "category": "Quemadores de grasa",
  "price": 19.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__718__SYNEPHRINE_20_MG_90_VCAPS__PVP_19_20_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Synephrine 20 MG 90 Vcaps. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 188,
  "active": true
 },
 {
  "id": 134,
  "code": "714",
  "name": "Green TEA Extract WITH Vitamin C 100 CAPS",
  "category": "Quemadores de grasa",
  "price": 23.7,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__714__GREEN_TEA_EXTRACT_WITH_VITAMIN_C_100_CAPS__PVP_23_70_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Green TEA Extract WITH Vitamin C 100 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 145,
  "active": true
 },
 {
  "id": 135,
  "code": "791",
  "name": "Tyrosine 120 CAPS",
  "category": "Quemadores de grasa",
  "price": 28.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__791__TYROSINE_120_CAPS__PVP_28_70_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Tyrosine 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 346,
  "active": true
 },
 {
  "id": 136,
  "code": "713",
  "name": "Champion Sport FUEL 1000 ML",
  "category": "Quemadores de grasa",
  "price": 29.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__713__CHAMPION_SPORT_FUEL_1000_ML__PVP_29_50_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Champion Sport FUEL 1000 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 279,
  "active": true
 },
 {
  "id": 137,
  "code": "781",
  "name": "CLA 1200 120 CAPS",
  "category": "Quemadores de grasa",
  "price": 30.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__781__CLA_1200_120_CAPS__PVP_30_90_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "CLA 1200 120 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 192,
  "active": true
 },
 {
  "id": 138,
  "code": "711",
  "name": "Synemax 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 34.9,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__711__SYNEMAX_90_CAPS__PVP_34_90_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Synemax 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 195,
  "active": true
 },
 {
  "id": 139,
  "code": "731",
  "name": "Carnilean Burner 480 ML",
  "category": "Quemadores de grasa",
  "price": 35.7,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__731__CARNILEAN_BURNER_480_ML__PVP_35_70_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Carnilean Burner 480 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.6,
  "reviews": 284,
  "active": true
 },
 {
  "id": 140,
  "code": "701",
  "name": "Thermolean 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 36.3,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__701__THERMOLEAN_90_CAPS__PVP_36_30_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Thermolean 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 76,
  "active": true
 },
 {
  "id": 141,
  "code": "715",
  "name": "CARB Blocker WITH Starchlite 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 36.3,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__715__CARB_BLOCKER_WITH_STARCHLITE_90_CAPS__PVP_36_30_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "CARB Blocker WITH Starchlite 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 247,
  "active": true
 },
 {
  "id": 142,
  "code": "761",
  "name": "Carniline 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 36.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__761__CARNILINE_90_CAPS__PVP_36_30_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Carniline 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 138,
  "active": true
 },
 {
  "id": 143,
  "code": "753",
  "name": "Carnishot 3000 20*60 ML",
  "category": "Quemadores de grasa",
  "price": 37.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__753__CARNISHOT_3000_20_60_ML__PVP_37_00_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Carnishot 3000 20*60 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 110,
  "active": true
 },
 {
  "id": 144,
  "code": "707",
  "name": "Lipolean 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 40.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__707__LIPOLEAN_90_CAPS__PVP_40_50_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Lipolean 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 236,
  "active": true
 },
 {
  "id": 145,
  "code": "710",
  "name": "Lipotropic FAT Burner 200 CAPS",
  "category": "Quemadores de grasa",
  "price": 40.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__710__LIPOTROPIC_FAT_BURNER_200_CAPS__PVP_40_50_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Lipotropic FAT Burner 200 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 280,
  "active": true
 },
 {
  "id": 146,
  "code": "703",
  "name": "Thermocore 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 40.9,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__703__THERMOCORE_90_CAPS__PVP_40_90_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Thermocore 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 310,
  "active": true
 },
 {
  "id": 147,
  "code": "754",
  "name": "X-FAT Thermogenic FAT Burner 90 CAPS",
  "category": "Quemadores de grasa",
  "price": 43.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__754__X_FAT_THERMOGENIC_FAT_BURNER_90_CAPS__PVP_43_20_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "X-FAT Thermogenic FAT Burner 90 CAPS. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.7,
  "reviews": 139,
  "active": true
 },
 {
  "id": 148,
  "code": "755",
  "name": "X-FAT 2 IN 1 SHOT 20*60 ML",
  "category": "Quemadores de grasa",
  "price": 44.0,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__755__X_FAT_2_IN_1_SHOT_20_60_ML__PVP_44_00_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "X-FAT 2 IN 1 SHOT 20*60 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 247,
  "active": true
 },
 {
  "id": 149,
  "code": "756",
  "name": "Carnitine 100.000 1000 ML",
  "category": "Quemadores de grasa",
  "price": 44.5,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/QUEMADORES_DE_GRASA/QUEMADORES_DE_GRASA__756__CARNITINE_100_000_1000_ML__PVP_44_50_EUR.webp",
  "emoji": "🔥",
  "customizable": false,
  "brand": "Amix",
  "description": "Carnitine 100.000 1000 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 35,
  "active": true
 },
 {
  "id": 150,
  "code": "SUPERANTI",
  "name": "AMIX Unidosis Super ANTI-CELLULITE GEL 4 ML",
  "category": "Unidosis",
  "price": 0.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__SUPERANTI__AMIX_UNIDOSIS_SUPER_ANTI_CELLULITE_GEL_4_ML__PVP_0_70_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "AMIX Unidosis Super ANTI-CELLULITE GEL 4 ML. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 322,
  "active": true
 },
 {
  "id": 151,
  "code": "CARBO1",
  "name": "Unidosis Carbojet GAIN 50 GR",
  "category": "Unidosis",
  "price": 1.35,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__CARBO1__UNIDOSIS_CARBOJET_GAIN_50_GR__PVP_1_35_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Carbojet GAIN 50 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 436,
  "active": true
 },
 {
  "id": 152,
  "code": "CLEAR24",
  "name": "Unidosis Clear ISO WHEY 25 GR",
  "category": "Unidosis",
  "price": 2.0,
  "badge": "Destacado",
  "badgeColor": "bg-yellow-400 text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__CLEAR24__UNIDOSIS_CLEAR_ISO_WHEY_25_GR__PVP_2_00_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Clear ISO WHEY 25 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 168,
  "active": true
 },
 {
  "id": 153,
  "code": "PREDATOR1",
  "name": "Unidosis Predator Protein 30 GR",
  "category": "Unidosis",
  "price": 2.1,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__PREDATOR1__UNIDOSIS_PREDATOR_PROTEIN_30_GR__PVP_2_10_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Predator Protein 30 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 124,
  "active": true
 },
 {
  "id": 154,
  "code": "CELLZOOM11",
  "name": "Unidosis Cellzoom 7 GR",
  "category": "Unidosis",
  "price": 2.3,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__CELLZOOM11__UNIDOSIS_CELLZOOM_7_GR__PVP_2_30_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Cellzoom 7 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 49,
  "active": true
 },
 {
  "id": 155,
  "code": "MICELLAR1",
  "name": "Unidosis Black Micellar Casein 35 GR",
  "category": "Unidosis",
  "price": 2.7,
  "badge": "Nuevo",
  "badgeColor": "bg-red-600 text-white",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__MICELLAR1__UNIDOSIS_BLACK_MICELLAR_CASEIN_35_GR__PVP_2_70_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Black Micellar Casein 35 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.5,
  "reviews": 172,
  "active": true
 },
 {
  "id": 156,
  "code": "MONSTER1",
  "name": "Unidosis Monster BEEF 33 GR",
  "category": "Unidosis",
  "price": 3.5,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__MONSTER1__UNIDOSIS_MONSTER_BEEF_33_GR__PVP_3_50_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Monster BEEF 33 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.8,
  "reviews": 195,
  "active": true
 },
 {
  "id": 157,
  "code": "ISOPRIME1",
  "name": "Unidosis Isoprime CFM Isolate 28 GR",
  "category": "Unidosis",
  "price": 4.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__ISOPRIME1__UNIDOSIS_ISOPRIME_CFM_ISOLATE_28_GR__PVP_4_20_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Isoprime CFM Isolate 28 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 394,
  "active": true
 },
 {
  "id": 158,
  "code": "ANABOLIC1",
  "name": "Unidosis Anabolic Masster 50 GR",
  "category": "Unidosis",
  "price": 4.2,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_EN_UNIDOSIS/PRODUCTOS_EN_UNIDOSIS__ANABOLIC1__UNIDOSIS_ANABOLIC_MASSTER_50_GR__PVP_4_20_EUR.webp",
  "emoji": "💊",
  "customizable": false,
  "brand": "Amix",
  "description": "Unidosis Anabolic Masster 50 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.3,
  "reviews": 338,
  "active": true
 },
 {
  "id": 159,
  "code": "4001",
  "name": "Isolyn Isotonic 800 GR",
  "category": "Bike Elite",
  "price": 22.5,
  "badge": "Top ventas",
  "badgeColor": "bg-brand-gold text-black",
  "featured": true,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_BIKE_ELITE/PRODUCTOS_BIKE_ELITE__4001__ISOLYN_ISOTONIC_800_GR__PVP_22_50_EUR.webp",
  "emoji": "🚴",
  "customizable": false,
  "brand": "Amix",
  "description": "Isolyn Isotonic 800 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.4,
  "reviews": 43,
  "active": true
 },
 {
  "id": 160,
  "code": "4002",
  "name": "Isolyn Recovery 800 GR",
  "category": "Bike Elite",
  "price": 25.7,
  "badge": null,
  "badgeColor": "",
  "featured": false,
  "image": "sources/amix_fotos_categoria_nombre_pvp_FINAL_WEB/01_webp_ligeras_para_web/PRODUCTOS_BIKE_ELITE/PRODUCTOS_BIKE_ELITE__4002__ISOLYN_RECOVERY_800_GR__PVP_25_70_EUR.webp",
  "emoji": "🚴",
  "customizable": false,
  "brand": "Amix",
  "description": "Isolyn Recovery 800 GR. Producto oficial Amix Nutrition. Calidad premium para tu rendimiento.",
  "rating": 4.9,
  "reviews": 54,
  "active": true
 }
];
