'use strict';
const SESSION='nutretium_user';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function token(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')?.token||''}catch{return''}}
async function api(method,body){const r=await fetch('/.netlify/functions/admin-settings',{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No se pudo completar la operación');return d}
let state={content:{bannerEnabled:false,bannerText:''},couponsManaged:false,points:{managed:false,enabled:false,perEuro:0},coupons:[]};
function couponRow(c={}){const div=document.createElement('div');div.className='coupon';div.innerHTML=`<div><label>Código</label><input data-k="code" value="${esc(c.code||'')}"></div><div><label>Tipo</label><select data-k="type"><option value="percent" ${c.type==='percent'?'selected':''}>%</option><option value="fixed" ${c.type==='fixed'?'selected':''}>€ fijo</option></select></div><div><label>Valor</label><input data-k="value" type="number" min="0" step="0.01" value="${Number(c.type==='fixed'?(c.valueCents||0)/100:c.value||0)}"></div><div><label>Mínimo €</label><input data-k="min" type="number" min="0" step="0.01" value="${Number(c.minCents||0)/100}"></div><div><label>Tope €</label><input data-k="cap" type="number" min="0" step="0.01" value="${Number(c.maxDiscountCents||0)/100}"></div><div><label>Activo</label><input data-k="active" type="checkbox" style="width:auto" ${c.active!==false?'checked':''}></div><button class="secondary" data-remove type="button">Quitar</button>`;div.querySelector('[data-remove]').onclick=()=>div.remove();return div}
function render(){const bannerEnabled=$('bannerEnabled'),bannerText=$('bannerText'),pointsEnabled=$('pointsEnabled'),pointsPerEuro=$('pointsPerEuro'),coupons=$('coupons');bannerEnabled.checked=Boolean(state.content?.bannerEnabled);bannerText.value=state.content?.bannerText||'';pointsEnabled.checked=Boolean(state.points?.enabled);pointsPerEuro.value=Number(state.points?.perEuro||0);coupons.innerHTML='';(state.coupons||[]).forEach(c=>coupons.appendChild(couponRow(c)))}
function readCoupons(){return[...document.querySelectorAll('.coupon')].map(row=>{const get=k=>row.querySelector(`[data-k="${k}"]`),type=get('type').value,v=Number(get('value').value)||0;return{code:get('code').value,type,value:type==='percent'?v:0,valueCents:type==='fixed'?Math.round(v*100):0,minCents:Math.round((Number(get('min').value)||0)*100),maxDiscountCents:Math.round((Number(get('cap').value)||0)*100),active:get('active').checked}}).filter(c=>c.code.trim())}
async function load(){if(!token()){location.href='/backoffice.html';return}try{const d=await api('GET');state=d.settings||state;render()}catch(e){$('status').textContent=e.message;$('status').className='status error'}}
$('addCoupon').onclick=()=>$('coupons').appendChild(couponRow({active:true}));$('save').onclick=async()=>{const save=$('save'),status=$('status');save.disabled=true;status.textContent='Guardando…';status.className='status';try{const settings={content:{bannerEnabled:$('bannerEnabled').checked,bannerText:$('bannerText').value},couponsManaged:true,points:{managed:true,enabled:$('pointsEnabled').checked,perEuro:Number($('pointsPerEuro').value)||0},coupons:readCoupons()};const d=await api('POST',{action:'save',settings});state=d.settings;render();status.textContent='Ajustes guardados. El panel pasa a ser la fuente explícita para cupones y Points.';status.className='status ok'}catch(e){status.textContent=e.message;status.className='status error'}finally{save.disabled=false}};load();