'use strict';
const SESSION_KEY='nutretium_user';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function token(){return(session()||{}).token||''}
async function api(method,body){const headers={'Content-Type':'application/json'};if(token())headers.Authorization='Bearer '+token();const r=await fetch('/.netlify/functions/admin-settings',{method,credentials:'same-origin',headers,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'No se pudo completar la operación'),{status:r.status,data:d});return d}
let state={content:{bannerEnabled:false,bannerText:''},couponsManaged:false,points:{managed:false,enabled:false,perEuro:0},shipping:{managed:false,enabled:false,rateCents:null,freeFromCents:5000,country:'España',label:'Envío'},coupons:[]},version=null,shippingTouched=false;
function couponRow(c={}){const div=document.createElement('div');div.className='coupon';div.innerHTML=`<div><label>Código</label><input data-k="code" value="${esc(c.code||'')}"></div><div><label>Tipo</label><select data-k="type"><option value="percent" ${c.type==='percent'?'selected':''}>%</option><option value="fixed" ${c.type==='fixed'?'selected':''}>€ fijo</option></select></div><div><label>Valor</label><input data-k="value" type="number" min="0" step="0.01" value="${Number(c.type==='fixed'?(c.valueCents||0)/100:c.value||0)}"></div><div><label>Mínimo €</label><input data-k="min" type="number" min="0" step="0.01" value="${Number(c.minCents||0)/100}"></div><div><label>Tope €</label><input data-k="cap" type="number" min="0" step="0.01" value="${Number(c.maxDiscountCents||0)/100}"></div><div><label>Activo</label><input data-k="active" type="checkbox" style="width:auto" ${c.active!==false?'checked':''}></div><button class="secondary" data-remove type="button">Quitar</button>`;div.querySelector('[data-remove]').onclick=()=>div.remove();return div}
function euro(cents){return cents===null||cents===undefined?'':(Number(cents)/100).toFixed(2)}
function render(){const bannerEnabled=$('bannerEnabled'),bannerText=$('bannerText'),pointsEnabled=$('pointsEnabled'),pointsPerEuro=$('pointsPerEuro'),coupons=$('coupons'),s=state.shipping||{};bannerEnabled.checked=Boolean(state.content?.bannerEnabled);bannerText.value=state.content?.bannerText||'';pointsEnabled.checked=Boolean(state.points?.enabled);pointsPerEuro.value=Number(state.points?.perEuro||0);$('shippingEnabled').checked=Boolean(s.enabled);$('shippingRate').value=euro(s.rateCents);$('shippingFreeFrom').value=euro(s.freeFromCents);$('shippingCountry').value=s.country||'España';$('shippingLabel').value=s.label||'Envío';$('shippingState').textContent=s.managed?(s.enabled?'Política gestionada desde este panel y activa.':'Política gestionada desde este panel, actualmente desactivada.'):'La política aún no está gestionada desde este panel. Hasta que la guardes, se usan las variables de Netlify si existen.';coupons.innerHTML='';(state.coupons||[]).forEach(c=>coupons.appendChild(couponRow(c)))}
function readCoupons(){return[...document.querySelectorAll('.coupon')].map(row=>{const get=k=>row.querySelector(`[data-k="${k}"]`),type=get('type').value,v=Number(get('value').value)||0;return{code:get('code').value,type,value:type==='percent'?v:0,valueCents:type==='fixed'?Math.round(v*100):0,minCents:Math.round((Number(get('min').value)||0)*100),maxDiscountCents:Math.round((Number(get('cap').value)||0)*100),active:get('active').checked}}).filter(c=>c.code.trim())}
function parseEuro(id){const raw=$(id).value.trim();if(raw==='')return null;const n=Number(raw);return Number.isFinite(n)&&n>=0?Math.round(n*100):NaN}
function readShipping(){const enabled=$('shippingEnabled').checked,rateCents=parseEuro('shippingRate'),freeFromCents=parseEuro('shippingFreeFrom'),country=$('shippingCountry').value.trim(),label=$('shippingLabel').value.trim();if(enabled&&(rateCents===null||Number.isNaN(rateCents)))throw new Error('Indica una tarifa normal de envío válida antes de activar los envíos.');if(Number.isNaN(freeFromCents))throw new Error('El umbral de envío gratis no es válido.');if(!country)throw new Error('Indica el país de envío.');if(!label)throw new Error('Indica el nombre del servicio de envío.');return{managed:shippingTouched||Boolean(state.shipping?.managed),enabled,rateCents:Number.isNaN(rateCents)?null:rateCents,freeFromCents:Number.isNaN(freeFromCents)?null:freeFromCents,country,label}}
async function load(){try{const d=await api('GET');state=d.settings||state;version=d.version||null;shippingTouched=false;render()}catch(e){if([401,403].includes(e.status)){location.href='/backoffice.html';return}$('status').textContent=e.message;$('status').className='status error'}}
['shippingEnabled','shippingRate','shippingFreeFrom','shippingCountry','shippingLabel'].forEach(id=>$(id).addEventListener(id==='shippingEnabled'?'change':'input',()=>{shippingTouched=true;$('shippingState').textContent='Cambios de envío pendientes de guardar.'}));
$('addCoupon').onclick=()=>$('coupons').appendChild(couponRow({active:true}));
$('save').onclick=async()=>{const save=$('save'),status=$('status');save.disabled=true;status.textContent='Guardando…';status.className='status';try{const shipping=readShipping();const settings={content:{bannerEnabled:$('bannerEnabled').checked,bannerText:$('bannerText').value},couponsManaged:true,points:{managed:true,enabled:$('pointsEnabled').checked,perEuro:Number($('pointsPerEuro').value)||0},shipping,coupons:readCoupons()};const d=await api('POST',{action:'save',settings,version});state=d.settings;version=d.version||version;shippingTouched=false;render();status.textContent='Ajustes guardados. La política de envío activa será utilizada por el checkout.';status.className='status ok'}catch(e){status.textContent=e.status===409?'Los ajustes cambiaron en otra sesión. Recarga antes de volver a guardar.':e.message;status.className='status error'}finally{save.disabled=false}};
load();