/* NUTRETIUM Smart Store — progressive UX, isolated from checkout */
(function(){
'use strict';
const E=window.NutretiumSmartEngine;
if(!E)return;
const RECENT_KEY='nutretium_smart_recent_v1';
const STORE_KEY='nutretium_store_list_v1';
const REORDER_KEY='nutretium_reorder_v1';
const IMPORT_KEY='nutretium_shared_import_v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=v=>Number(v||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
const catalog=()=>E.activeCatalog(window.NUTRETIUM_PRODUCTS||[]);
const read=(k,f=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const productUrl=p=>`/producto/${E.text(p.name).replace(/\s+/g,'-')}-${encodeURIComponent(p.id)}`;
const availability=p=>E.availability(p);
let deferredInstall=null;
function toast(msg){let el=document.getElementById('ntSmartToast');if(!el){el=document.createElement('div');el.id='ntSmartToast';el.className='nt-smart-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function emit(name,detail={}){window.dispatchEvent(new CustomEvent('nt:smart-event',{detail:{name,...detail}}))}
function availableBadge(p){const a=availability(p);return a==='in_stock'?'<span class="nt-smart-badge ok">Disponible</span>':a==='out_of_stock'?'<span class="nt-smart-badge">Agotado</span>':'<span class="nt-smart-badge warn">Disponibilidad por confirmar</span>'}
function card(p,{compact=false}={}){const up=E.unitPrice(p);return `<article class="nt-smart-card" data-smart-product="${Number(p.id)}">${compact?'':(p.image?`<img src="/${esc(String(p.image).replace(/^\//,''))}" alt="${esc(p.name)}" loading="lazy" decoding="async">`:`<div class="emoji" aria-hidden="true">${esc(p.emoji||'•')}</div>`)}<h3>${esc(p.name)}</h3><div class="nt-smart-list">${availableBadge(p)}${p.category?`<span class="nt-smart-badge">${esc(p.category)}</span>`:''}</div><p class="price">${euro(p.price)}</p>${up?`<small>${euro(up.per100)} / 100 ${up.kind}</small>`:'<small>Formato unitario no calculado</small>'}<div class="nt-smart-list"><a href="${productUrl(p)}">Ver ficha</a>${availability(p)==='in_stock'&&typeof window.addToCart==='function'?`<button class="primary" type="button" data-smart-add="${Number(p.id)}">Añadir</button>`:''}${typeof window.ntToggleCompare==='function'?`<button type="button" data-smart-compare="${Number(p.id)}">Comparar</button>`:''}<button type="button" data-store-save="${Number(p.id)}">Guardar tienda</button></div></article>`}
function ensureShell(){if(document.getElementById('ntSmartDrawer'))return;
 const launcher=document.createElement('div');launcher.className='nt-smart-launcher';launcher.innerHTML='<button type="button" id="ntSmartOpen" class="nt-smart-pulse">Smart Store</button><button type="button" id="ntSmartInstall" class="nt-smart-install">Instalar app</button>';document.body.appendChild(launcher);
 const d=document.createElement('div');d.id='ntSmartDrawer';d.className='nt-smart-drawer';d.setAttribute('aria-hidden','true');d.innerHTML=`<section class="nt-smart-shell" role="dialog" aria-modal="true" aria-label="Nutretium Smart Store"><header class="nt-smart-head"><strong>NUTRETIUM · SMART STORE</strong><button type="button" class="nt-smart-close" id="ntSmartClose" aria-label="Cerrar">×</button></header><nav class="nt-smart-tabs" aria-label="Funciones Smart Store"><button data-tab="finder" class="active">Finder</button><button data-tab="stacks">Stacks</button><button data-tab="foryou">Para ti</button><button data-tab="reorder">Reponer</button><button data-tab="club">Club</button><button data-tab="prepared">Preparados</button><button data-tab="store">Tienda</button></nav><div id="ntSmartPanels"></div></section>`;document.body.appendChild(d);
 document.getElementById('ntSmartOpen').onclick=()=>open('finder');document.getElementById('ntSmartClose').onclick=close;d.addEventListener('pointerdown',e=>{if(e.target===d)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&d.classList.contains('open'))close()});d.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
 d.addEventListener('click',handleAction);
 renderPanels();
}
function open(tab='finder'){const d=document.getElementById('ntSmartDrawer');if(!d)return;d.classList.add('open');d.setAttribute('aria-hidden','false');document.documentElement.style.overflow='hidden';showTab(tab);emit('open',{tab})}
function close(){const d=document.getElementById('ntSmartDrawer');if(!d)return;d.classList.remove('open');d.setAttribute('aria-hidden','true');document.documentElement.style.overflow=''}
function showTab(tab){const d=document.getElementById('ntSmartDrawer');if(!d)return;d.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));d.querySelectorAll('.nt-smart-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===tab));if(tab==='foryou')renderForYou();if(tab==='reorder')renderReorder();if(tab==='prepared')renderPrepared();if(tab==='store')renderStore()}
function renderPanels(){const host=document.getElementById('ntSmartPanels');if(!host)return;host.innerHTML=`
 <section class="nt-smart-panel active" data-panel="finder"><span class="nt-smart-kicker">BUSCA POR INTENCIÓN</span><h2 class="nt-smart-title">Dime qué buscas.</h2><p class="nt-smart-copy">Busca por producto, categoría, formato o presupuesto. El sistema solo utiliza información publicada en el catálogo y no realiza recomendaciones médicas.</p><form id="ntSmartFindForm" class="nt-smart-search"><input id="ntSmartQuery" autocomplete="off" placeholder="Ej.: creatina por menos de 30 euros" aria-label="Qué buscas"><button type="submit">Buscar</button></form><div class="nt-smart-list"><button type="button" id="ntVoiceSearch">🎙 Voz</button><a href="/comparar">Abrir comparador</a></div><div id="ntSmartFindResults" class="nt-smart-grid" style="margin-top:16px"></div></section>
 <section class="nt-smart-panel" data-panel="stacks"><span class="nt-smart-kicker">CONSTRUCTOR</span><h2 class="nt-smart-title">Crea tu Stack.</h2><p class="nt-smart-copy">Combina categorías con presupuesto real. No sustituye el etiquetado ni una recomendación profesional.</p><div class="nt-smart-controls"><select id="ntStackPreset"><option value="entrenamiento">Entrenamiento</option><option value="energia">Energía</option><option value="bienestar">Bienestar</option><option value="snack">Snacks</option></select><input id="ntStackBudget" type="number" min="1" step="1" placeholder="Presupuesto €"><select id="ntStackItems"><option value="2">2 productos</option><option value="3" selected>3 productos</option><option value="4">4 productos</option></select></div><button type="button" class="nt-smart-cta primary" id="ntBuildStack">Construir stack</button><div id="ntStackResults"></div></section>
 <section class="nt-smart-panel" data-panel="foryou"><span class="nt-smart-kicker">CONTINUIDAD</span><h2 class="nt-smart-title">Continúa donde lo dejaste.</h2><p class="nt-smart-copy">Se basa únicamente en navegación guardada en este dispositivo, no en datos sensibles ni en inferencias de salud.</p><div id="ntForYou" class="nt-smart-grid"></div></section>
 <section class="nt-smart-panel" data-panel="reorder"><span class="nt-smart-kicker">REPOSICIÓN</span><h2 class="nt-smart-title">Recuérdamelo cuando tú decidas.</h2><p class="nt-smart-copy">Elige producto y plazo. No calculamos consumo ni dosis: la fecha la decides tú.</p><div class="nt-smart-controls"><select id="ntReorderProduct"></select><select id="ntReorderDays"><option value="30">30 días</option><option value="45">45 días</option><option value="60">60 días</option><option value="90">90 días</option></select><button type="button" class="nt-smart-cta primary" id="ntSaveReorder">Guardar recordatorio</button></div><div id="ntReorderList"></div></section>
 <section class="nt-smart-panel" data-panel="club"><span class="nt-smart-kicker">MI NUTRETIUM</span><h2 class="nt-smart-title">Club sin números inventados.</h2><div class="nt-smart-club"><div class="nt-smart-hero-card"><h3>Puntos, referidos y gift cards</h3><p class="nt-smart-copy">El saldo y las ventajas reales se consultan en tu cuenta. Esta pantalla no muestra cantidades hasta que provengan del sistema autenticado.</p><a class="nt-smart-cta primary" href="/cuenta.html">Abrir Mi Nutretium</a></div><div class="nt-smart-card"><h3>Ventajas verificables</h3><p>Historial de pedidos, recompra, favoritos, puntos, referidos y tarjetas regalo cuando estén disponibles en tu cuenta.</p></div></div></section>
 <section class="nt-smart-panel" data-panel="prepared"><span class="nt-smart-kicker">PREPARADOS</span><h2 class="nt-smart-title">Tu Nutretium, a tu manera.</h2><p class="nt-smart-copy">Solo aparecen preparados publicados actualmente. No activamos recetas o ingredientes que no estén dados de alta.</p><div id="ntPrepared" class="nt-smart-grid"></div></section>
 <section class="nt-smart-panel" data-panel="store"><span class="nt-smart-kicker">SANTANDER</span><h2 class="nt-smart-title">Tienda física + online.</h2><p class="nt-smart-copy">C/ La Albericia nº 1 · Santander · Lun–Sáb 09:30–22:00. Guarda productos para consultarlos en tienda; guardar no equivale a reservar stock.</p><div class="nt-smart-list"><button type="button" id="ntShareStoreList">Compartir mi lista</button><button type="button" id="ntClearStoreList">Vaciar lista</button></div><div id="ntStoreList" class="nt-smart-grid" style="margin-top:16px"></div></section>`;
 document.getElementById('ntSmartFindForm').onsubmit=e=>{e.preventDefault();renderFinder(document.getElementById('ntSmartQuery').value)};
 document.getElementById('ntBuildStack').onclick=renderStack;
 document.getElementById('ntSaveReorder').onclick=saveReorder;
 document.getElementById('ntShareStoreList').onclick=shareStoreList;
 document.getElementById('ntClearStoreList').onclick=()=>{write(STORE_KEY,[]);renderStore();toast('Lista vaciada')};
 setupVoice();populateReorderSelect();renderFinder('');renderForYou();renderPrepared();renderStore();renderReorder();
}
function handleAction(e){const add=e.target.closest('[data-smart-add]');if(add&&typeof window.addToCart==='function'){window.addToCart(Number(add.dataset.smartAdd));emit('add',{productId:Number(add.dataset.smartAdd)});return}const cmp=e.target.closest('[data-smart-compare]');if(cmp&&typeof window.ntToggleCompare==='function'){window.ntToggleCompare(Number(cmp.dataset.smartCompare));return}const save=e.target.closest('[data-store-save]');if(save){saveForStore(Number(save.dataset.storeSave));return}const custom=e.target.closest('[data-smart-customize]');if(custom&&typeof window.openCustomModal==='function'){window.openCustomModal(Number(custom.dataset.smartCustomize));close()}}
function renderFinder(q){const host=document.getElementById('ntSmartFindResults');if(!host)return;const list=q.trim()?E.find(catalog(),q,{limit:12}):catalog().filter(p=>p.featured&&availability(p)!=='out_of_stock').slice(0,6);if(!list.length){host.innerHTML='<div class="nt-smart-empty">No hay coincidencias publicadas con esos criterios. Prueba otra categoría o un presupuesto diferente.</div>';return}host.innerHTML=list.map(p=>card(p)).join('');emit('find',{query:q,count:list.length})}
function renderStack(){const preset=document.getElementById('ntStackPreset').value;const budget=Number(document.getElementById('ntStackBudget').value)||Infinity;const maxItems=Number(document.getElementById('ntStackItems').value)||3;const out=E.buildStack(catalog(),{preset,budget,maxItems});const host=document.getElementById('ntStackResults');if(!out.items.length){host.innerHTML='<div class="nt-smart-empty" style="margin-top:16px">No se puede construir un stack con productos publicados dentro de ese presupuesto.</div>';return}host.innerHTML=`<div class="nt-smart-stack-summary"><div><small>Total de catálogo</small><strong>${euro(out.total)}</strong></div><div>${out.budget?`Presupuesto ${euro(out.budget)}`:'Sin límite fijado'}</div></div><div class="nt-smart-grid">${out.items.map(p=>card(p,{compact:true})).join('')}</div>`;emit('stack',{preset,total:out.total,count:out.items.length})}
function recentIds(){return read(RECENT_KEY,[]).map(Number).filter(Number.isFinite).slice(0,20)}
function recordRecent(id){const n=Number(id);if(!Number.isFinite(n))return;write(RECENT_KEY,[n,...recentIds().filter(x=>x!==n)].slice(0,20))}
function renderForYou(){const host=document.getElementById('ntForYou');if(!host)return;const all=catalog(),ids=recentIds(),seen=all.filter(p=>ids.includes(Number(p.id)));let list=[];if(seen.length){const cats=[...new Set(seen.map(p=>p.category))];list=all.filter(p=>cats.includes(p.category)&&!ids.includes(Number(p.id))&&availability(p)!=='out_of_stock').slice(0,6)}if(!list.length)list=all.filter(p=>p.featured&&availability(p)!=='out_of_stock').slice(0,6);if(!list.length)list=all.filter(p=>availability(p)!=='out_of_stock').slice(0,6);host.innerHTML=list.length?list.map(p=>card(p)).join(''):'<div class="nt-smart-empty">Aún no hay suficientes productos publicados para personalizar esta sección.</div>'}
function populateReorderSelect(){const s=document.getElementById('ntReorderProduct');if(!s)return;s.innerHTML='<option value="">Selecciona un producto</option>'+catalog().map(p=>`<option value="${Number(p.id)}">${esc(p.name)}</option>`).join('')}
function saveReorder(){const id=Number(document.getElementById('ntReorderProduct').value),days=Number(document.getElementById('ntReorderDays').value);if(!Number.isFinite(id)||!days)return toast('Selecciona un producto');const due=new Date(Date.now()+days*86400000).toISOString();const list=read(REORDER_KEY,[]).filter(x=>Number(x.productId)!==id);list.push({productId:id,dueAt:due,createdAt:new Date().toISOString()});write(REORDER_KEY,list.slice(-30));renderReorder();toast('Recordatorio guardado');emit('reorder',{productId:id,days})}
function renderReorder(){const host=document.getElementById('ntReorderList');if(!host)return;const byId=new Map(catalog().map(p=>[Number(p.id),p]));const items=read(REORDER_KEY,[]).filter(x=>byId.has(Number(x.productId)));if(!items.length){host.innerHTML='<div class="nt-smart-empty">No tienes recordatorios de reposición en este dispositivo.</div>';return}host.innerHTML='<div class="nt-smart-grid">'+items.map(x=>{const p=byId.get(Number(x.productId));const d=new Date(x.dueAt);return `<article class="nt-smart-card"><h3>${esc(p.name)}</h3><p>Fecha elegida: <strong>${d.toLocaleDateString('es-ES')}</strong></p><a href="${productUrl(p)}">Ver producto</a><button type="button" data-remove-reorder="${Number(p.id)}">Eliminar</button></article>`}).join('')+'</div>';host.querySelectorAll('[data-remove-reorder]').forEach(b=>b.onclick=()=>{write(REORDER_KEY,items.filter(x=>Number(x.productId)!==Number(b.dataset.removeReorder)));renderReorder()});notifyDue(items,byId)}
function notifyDue(items,byId){const due=items.filter(x=>new Date(x.dueAt).getTime()<=Date.now());if(!due.length)return;const names=due.slice(0,2).map(x=>byId.get(Number(x.productId))?.name).filter(Boolean);if(names.length)toast(`Tienes productos marcados para reponer: ${names.join(', ')}`)}
function renderPrepared(){const host=document.getElementById('ntPrepared');if(!host)return;const list=E.prepared(catalog());if(!list.length){host.innerHTML='<div class="nt-smart-empty">No hay preparados publicados actualmente en el catálogo online. No se muestran recetas internas ni artículos desactivados.</div>';return}host.innerHTML=list.slice(0,12).map(p=>`<article class="nt-smart-card">${p.image?`<img src="/${esc(String(p.image).replace(/^\//,''))}" alt="${esc(p.name)}">`:`<div class="emoji">${esc(p.emoji||'•')}</div>`}<h3>${esc(p.name)}</h3><p class="price">${euro(p.price)}</p>${availableBadge(p)}<div class="nt-smart-list">${p.customizable&&typeof window.openCustomModal==='function'?`<button class="primary" data-smart-customize="${Number(p.id)}">Personalizar</button>`:`<a href="${productUrl(p)}">Ver ficha</a>`}</div></article>`).join('')}
function storeIds(){return [...new Set(read(STORE_KEY,[]).map(Number).filter(Number.isFinite))].slice(0,30)}
function saveForStore(id){const ids=storeIds();if(!ids.includes(Number(id)))ids.push(Number(id));write(STORE_KEY,ids);renderStore();toast('Guardado en tu lista de tienda');emit('store-save',{productId:Number(id)})}
function renderStore(){const host=document.getElementById('ntStoreList');if(!host)return;const ids=storeIds(),list=catalog().filter(p=>ids.includes(Number(p.id)));host.innerHTML=list.length?list.map(p=>card(p,{compact:true})).join(''):'<div class="nt-smart-empty">Tu lista está vacía. Guarda productos desde Finder o desde cualquier pestaña Smart Store.</div>'}
async function shareStoreList(){const ids=storeIds();if(!ids.length)return toast('No hay productos en la lista');const token=E.encodeList(ids);const url=new URL(location.href);url.searchParams.set('ntlist',token);url.hash='';try{await navigator.clipboard.writeText(url.toString());toast('Enlace copiado')}catch{prompt('Copia este enlace',url.toString())}emit('share',{count:ids.length})}
function importShared(){const token=new URL(location.href).searchParams.get('ntlist');if(!token||sessionStorage.getItem(IMPORT_KEY)===token)return;const allowed=new Set(catalog().map(p=>Number(p.id))),ids=E.decodeList(token).filter(id=>allowed.has(id));if(ids.length){write(STORE_KEY,ids);sessionStorage.setItem(IMPORT_KEY,token);setTimeout(()=>{open('store');toast('Lista compartida cargada')},500)}}
function setupVoice(){const b=document.getElementById('ntVoiceSearch');if(!b)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){b.hidden=true;return}b.onclick=()=>{const r=new SR();r.lang='es-ES';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>{const q=e.results?.[0]?.[0]?.transcript||'';document.getElementById('ntSmartQuery').value=q;renderFinder(q)};r.onerror=()=>toast('No se pudo usar la búsqueda por voz');r.start()}}
function setupInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;const b=document.getElementById('ntSmartInstall');if(b)b.classList.add('visible')});document.addEventListener('click',async e=>{if(e.target?.id!=='ntSmartInstall'||!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice.catch(()=>null);deferredInstall=null;e.target.classList.remove('visible')});if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js',{scope:'/'}).catch(()=>{})}
function observeProducts(){document.addEventListener('click',e=>{const link=e.target.closest('a[href*="/producto/"]');if(!link)return;const card=link.closest('[data-product-id],[data-smart-product]');let id=Number(card?.dataset.productId||card?.dataset.smartProduct);if(!Number.isFinite(id)){const m=link.getAttribute('href')?.match(/-(\d+)(?:$|[?#])/);id=m?Number(m[1]):NaN}if(Number.isFinite(id))recordRecent(id)},true)}
function init(){ensureShell();setupInstall();observeProducts();importShared();const q=new URL(location.href).searchParams.get('smart');if(q&&['finder','stacks','foryou','reorder','club','prepared','store'].includes(q))setTimeout(()=>open(q),180)}
window.NutretiumSmartStore={open,close,showTab,saveForStore};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
