'use strict';
const PRODUCTS=(window.NUTRETIUM_PRODUCTS||[]).filter(p=>p.active!==false&&(p.stock===null||Number(p.stock)>0));
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s||'producto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const GOALS={muscle:['Proteínas','Creatinas','Alimentación proteica'],performance:['Pre-entrenos','Creatinas','Proteínas'],recovery:['Proteínas','Colágeno y bienestar','Vitaminas y salud'],wellness:['Vitaminas y salud','Colágeno y bienestar'],food:['Alimentación proteica','Barritas y snacks']};
function track(name){try{if(localStorage.getItem('nutretium_cookies')==='accepted')fetch('/.netlify/functions/analytics-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})}catch{}}
function render(list){$('results').innerHTML=list.length?list.map(p=>`<article class="product"><span class="tag">${esc(p.category)}</span><strong>${esc(p.name)}</strong><div class="price">${Number(p.price).toFixed(2)} €</div><a class="btn" href="/producto/${slug(p.name)}-${p.id}">Ver producto</a></article>`).join(''):'<div class="card">No hay productos disponibles con esos criterios.</div>'}
function recommend(){const goal=$('goal').value,budget=Number($('budget').value)||Infinity,pref=$('preference').value;let list=PRODUCTS.filter(p=>Number(p.price)<=budget);if(pref)list=list.filter(p=>p.category===pref);else if(goal)list=list.filter(p=>GOALS[goal]?.includes(p.category));list.sort((a,b)=>(Number(b.featured)-Number(a.featured))||Number(a.price)-Number(b.price));render(list.slice(0,9));track('recommendation')}
function best(cat){return PRODUCTS.filter(p=>p.category===cat).sort((a,b)=>(Number(b.featured)-Number(a.featured))||Number(a.price)-Number(b.price))[0]||null}
function packCard(title,cats){const items=cats.map(best).filter(Boolean);if(items.length<2)return'';const total=items.reduce((s,p)=>s+Number(p.price||0),0);return `<article class="product pack"><span class="tag">Pack</span><strong>${esc(title)}</strong><ul class="muted">${items.map(p=>`<li>${esc(p.name)}</li>`).join('')}</ul><div class="price">${total.toFixed(2)} €</div><button class="btn" data-pack='${JSON.stringify(items.map(p=>({id:p.id,name:p.name}))).replace(/'/g,'&#39;')}'>Añadir pack</button></article>`}
function renderPacks(){const html=[packCard('Rendimiento',['Pre-entrenos','Creatinas','Proteínas']),packCard('Recuperación',['Proteínas','Colágeno y bienestar','Vitaminas y salud']),packCard('Snack inteligente',['Alimentación proteica','Barritas y snacks','Bebidas'])].filter(Boolean).join('');$('packs').innerHTML=html||'<div class="card">Los packs aparecerán cuando haya suficiente stock compatible.</div>';document.querySelectorAll('[data-pack]').forEach(btn=>btn.onclick=()=>{let arr=[];try{arr=JSON.parse(btn.dataset.pack)}catch{};let cart=[];try{cart=JSON.parse(localStorage.getItem('nutretium_cart_v1')||'[]')}catch{};const map=new Map(cart.map(x=>[String(x.id),x]));arr.forEach(x=>{const k=String(x.id),r=map.get(k)||{key:k,id:x.id,quantity:0,customization:null};r.quantity=Math.min(99,Number(r.quantity||0)+1);map.set(k,r)});localStorage.setItem('nutretium_cart_v1',JSON.stringify([...map.values()]));location.href='/?cart=1'})}
$('recommend').onclick=recommend;renderPacks();
