'use strict';
const crypto=require('crypto');
const {getBlobStore}=require('./blob-store');
const STORE='admin-config-secrets-v1';
const KEY='factusol-v1';
function master(){const seed=String(process.env.CONFIG_VAULT_KEY||'').trim();if(!seed)return null;return crypto.createHash('sha256').update(`nutretium-factusol-vault:v1:${seed}`).digest()}
function configured(){return Boolean(master()&&getBlobStore(STORE))}
function seal(value){const key=master();if(!key)throw new Error('vault key unavailable');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const plain=Buffer.from(JSON.stringify(value),'utf8'),data=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();return{v:1,alg:'AES-256-GCM',iv:iv.toString('base64'),tag:tag.toString('base64'),data:data.toString('base64'),updatedAt:new Date().toISOString()}}
function open(record){const key=master();if(!key||!record||record.v!==1)return null;try{const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(record.iv,'base64'));decipher.setAuthTag(Buffer.from(record.tag,'base64'));const plain=Buffer.concat([decipher.update(Buffer.from(record.data,'base64')),decipher.final()]);const parsed=JSON.parse(plain.toString('utf8'));return parsed&&typeof parsed==='object'?parsed:null}catch{return null}}
async function read(){const store=getBlobStore(STORE);if(!store)return null;const record=await store.get(KEY,{type:'json',consistency:'strong'}).catch(()=>null);return open(record)}
async function status(){const value=await read();return{vaultConfigured:configured(),dedicatedKeyConfigured:Boolean(master()),manufacturerConfigured:Boolean(value?.manufacturerCode),clientConfigured:Boolean(value?.clientCode),databaseConfigured:Boolean(value?.database),passwordConfigured:Boolean(value?.password),warehouseCodesConfigured:Boolean(value?.warehouseCodes),tariffConfigured:Boolean(value?.tariffCode),liveEnabled:value?.liveEnabled===true,writeEnabled:value?.writeEnabled===true,updatedAt:value?.updatedAt||null}}
function clean(v,max=160){return String(v??'').trim().slice(0,max)}
async function write(input={}){const store=getBlobStore(STORE);if(!store||!master())throw Object.assign(new Error('vault unavailable'),{code:'UNAVAILABLE'});const current=await read()||{};const next={manufacturerCode:clean(input.manufacturerCode||current.manufacturerCode,32),clientCode:clean(input.clientCode||current.clientCode,32),database:clean(input.database||current.database,64),password:clean(input.password||current.password,512),warehouseCodes:clean(input.warehouseCodes??current.warehouseCodes,256),tariffCode:clean(input.tariffCode??current.tariffCode,64),liveEnabled:input.liveEnabled===undefined?Boolean(current.liveEnabled):Boolean(input.liveEnabled),writeEnabled:input.writeEnabled===undefined?Boolean(current.writeEnabled):Boolean(input.writeEnabled),updatedAt:new Date().toISOString()};if(!/^\d+$/.test(next.manufacturerCode)||!/^\d+$/.test(next.clientCode)||!next.database||!next.password)throw Object.assign(new Error('missing credentials'),{code:'INVALID'});await store.setJSON(KEY,seal(next));const verify=await read();if(!verify||verify.manufacturerCode!==next.manufacturerCode||verify.clientCode!==next.clientCode||verify.database!==next.database||verify.password!==next.password)throw Object.assign(new Error('vault verification failed'),{code:'VERIFY'});return status()}
async function clear(){const store=getBlobStore(STORE);if(!store)return false;await store.delete(KEY).catch(()=>{});return true}
module.exports={configured,read,status,write,clear,_test:{master,seal,open}};
