'use strict';
const crypto=require('crypto');
const store=require('./enterprise-store');
const actions=require('./enterprise-actions');
const {getBlobStore}=require('./blob-store');
const SYSTEM={email:'system@nutretium.local',role:'system'};
async function withLock(key,fn){const locks=getBlobStore('enterprise-locks-v1');if(!locks)throw Object.assign(new Error('Bloqueo transaccional no disponible.'),{code:'STORE_UNAVAILABLE'});const id=String(key).replace(/[^a-zA-Z0-9._:-]/g,'-');const token=crypto.randomUUID();const ok=await locks.setJSON(id,{token,at:Date.now()},{onlyIfNew:true}).then(r=>r===true||r?.modified===true||r?.etag||r===undefined).catch(()=>false);if(!ok)throw Object.assign(new Error('Recurso ocupado; reintenta la operación.'),{code:'CONFLICT'});try{return await fn();}finally{await locks.delete(id).catch(()=>{});}}
async function inventoryRowsForSku(sku){const rows=await store.list('inventory',{limit:1000});return rows.filter(r=>r.sku===sku&&!r.archivedAt).sort((a,b)=>Number(Boolean(b.isDefault))-Number(Boolean(a.isDefault))||String(a.warehouseId).localeCompare(String(b.warehouseId)));}
async function reserveOrder(order,items){const reservations=[];for(const item of items){const sku=String(item.code||item.sku||'');if(!sku)continue;const rows=await inventoryRowsForSku(sku);if(!rows.length)continue;let remaining=Number(item.qty||0);for(const row of rows){if(remaining<=0)break;const available=Math.max(0,Number(row.onHand||0)-Number(row.reserved||0));if(!available)continue;const qty=Math.min(remaining,available);await withLock(`inventory:${row.id}`,async()=>{const fresh=await store.get('inventory',row.id);const changed=actions.reserveInventory(fresh,qty);if(!changed.ok)throw Object.assign(new Error(changed.error),{code:'CONFLICT'});await store.save('inventory',changed.record,SYSTEM,{id:row.id,reason:`reserve:${order}`});});reservations.push({inventoryId:row.id,sku,qty});remaining-=qty;}if(remaining>0){await releaseReservations(order,reservations);throw Object.assign(new Error(`Stock Enterprise insuficiente para ${sku}.`),{code:'CONFLICT'});}}return reservations;}
async function releaseReservations(order,reservations){for(const r of reservations||[]){await withLock(`inventory:${r.inventoryId}`,async()=>{const fresh=await store.get('inventory',r.inventoryId);if(!fresh)return;const qty=Math.min(Number(r.qty||0),Number(fresh.reserved||0));if(!qty)return;const changed=actions.releaseInventory(fresh,qty);if(changed.ok)await store.save('inventory',changed.record,SYSTEM,{id:r.inventoryId,reason:`release:${order}`});}).catch(()=>{});}}
async function commitReservations(order,reservations){for(const r of reservations||[]){await withLock(`inventory:${r.inventoryId}`,async()=>{const fresh=await store.get('inventory',r.inventoryId);if(!fresh)return;const qty=Number(r.qty||0);if(Number(fresh.reserved||0)<qty||Number(fresh.onHand||0)<qty)throw new Error('Reserva de inventario inconsistente.');const next={...fresh,onHand:Number(fresh.onHand||0)-qty,reserved:Number(fresh.reserved||0)-qty};next.available=next.onHand-next.reserved;const movements=Array.isArray(next.movements)?next.movements.slice(-99):[];movements.push({id:crypto.randomUUID(),at:new Date().toISOString(),delta:-qty,reason:'sale',reference:order});next.movements=movements;await store.save('inventory',next,SYSTEM,{id:r.inventoryId,reason:`paid:${order}`});});}}
async function getCommerceSettings(){return(await store.list('commerce-settings',{limit:100})).find(r=>r.key==='checkout'&&r.status!=='inactive')||{};}
async function quoteBenefits({email,subtotalAfterPromoCents,giftCardCode,usePoints,referralCode}){const settings=await getCommerceSettings();let remaining=Math.max(0,Number(subtotalAfterPromoCents||0)),giftCard=null,loyalty=null,referral=null,b2b=null,extraDiscountCents=0;const accounts=await store.list('b2b-accounts',{limit:1000});const account=accounts.find(a=>String(a.email||'').toLowerCase()===String(email).toLowerCase()&&a.status==='active');if(account&&account.priceListId){const list=await store.get('price-lists',account.priceListId);if(list&&list.status==='active')b2b={accountId:account.id,priceListId:list.id};}
if(giftCardCode){const cards=await store.list('gift-cards',{limit:1000});const card=cards.find(c=>String(c.code||'').toUpperCase()===String(giftCardCode).trim().toUpperCase()&&c.status==='active');if(!card)throw Object.assign(new Error('Tarjeta regalo no válida o no activa.'),{statusCode:400});const use=Math.min(remaining,Number(card.balanceCents??card.initialCents??0));giftCard={id:card.id,code:card.code,useCents:use};remaining-=use;extraDiscountCents+=use;}
if(Number(usePoints)>0){const cents=Number(settings.loyaltyCentPerPoint||0);if(!Number.isInteger(cents)||cents<=0)throw Object.assign(new Error('El canje de puntos no está configurado.'),{statusCode:409});const rows=await store.list('loyalty',{limit:1000});const rec=rows.find(r=>String(r.customerEmail||'').toLowerCase()===String(email).toLowerCase()&&r.status!=='suspended');const requested=Math.floor(Number(usePoints));if(!rec||Number(rec.balance||0)<requested)throw Object.assign(new Error('Saldo de puntos insuficiente.'),{statusCode:409});const value=Math.min(remaining,requested*cents);const used=Math.ceil(value/cents);loyalty={id:rec.id,points:used,valueCents:used*cents};remaining=Math.max(0,remaining-loyalty.valueCents);extraDiscountCents+=loyalty.valueCents;}
if(referralCode){const refs=await store.list('referrals',{limit:1000});const rec=refs.find(r=>String(r.code||'').toUpperCase()===String(referralCode).trim().toUpperCase()&&r.status==='active');if(!rec)throw Object.assign(new Error('Código de referido no válido.'),{statusCode:400});if(String(rec.ownerEmail||'').toLowerCase()===String(email).toLowerCase())throw Object.assign(new Error('No puedes usar tu propio código de referido.'),{statusCode:409});const value=Math.min(remaining,Number(settings.referralBuyerDiscountCents||0));if(value>0){referral={id:rec.id,code:rec.code,discountCents:value,ownerEmail:rec.ownerEmail};remaining-=value;extraDiscountCents+=value;}}
return{settings,b2b,giftCard,loyalty,referral,extraDiscountCents,remainingCents:remaining};}
async function commitBenefits(order,email,effects){if(!effects)return;const marker=await store.get('commerce-settings',`settled:${order}`).catch(()=>null);if(marker)return; if(effects.giftCard)await withLock(`gift:${effects.giftCard.id}`,async()=>{const c=await store.get('gift-cards',effects.giftCard.id);if(!c)return;const balance=Number(c.balanceCents??c.initialCents??0);if(balance<effects.giftCard.useCents)throw new Error('Saldo de tarjeta regalo insuficiente al liquidar.');const ledger=Array.isArray(c.ledger)?c.ledger.slice(-199):[];ledger.push({at:new Date().toISOString(),order,deltaCents:-effects.giftCard.useCents});await store.save('gift-cards',{...c,balanceCents:balance-effects.giftCard.useCents,status:balance-effects.giftCard.useCents===0?'redeemed':c.status,ledger},SYSTEM,{id:c.id,reason:`order:${order}`});});if(effects.loyalty){const rec=await store.get('loyalty',effects.loyalty.id);const changed=actions.loyaltyAdjust(rec,-effects.loyalty.points,`Canje pedido ${order}`);if(!changed.ok)throw new Error(changed.error);await store.save('loyalty',changed.record,SYSTEM,{id:rec.id,reason:`order:${order}`});}const settings=effects.settings||{};const earn=Math.floor(Number(effects.paidCents||0)/100*Number(settings.loyaltyEarnPointsPerEuro||0));if(earn>0){let rows=await store.list('loyalty',{limit:1000});let rec=rows.find(r=>String(r.customerEmail||'').toLowerCase()===String(email).toLowerCase());if(!rec)rec=await store.save('loyalty',{customerEmail:email,balance:0,status:'active'},SYSTEM,{reason:'loyalty-create'});const changed=actions.loyaltyAdjust(rec,earn,`Compra ${order}`);if(changed.ok)await store.save('loyalty',changed.record,SYSTEM,{id:rec.id,reason:`earn:${order}`});}if(effects.referral){const ref=await store.get('referrals',effects.referral.id);if(ref){await store.save('referrals',{...ref,conversions:Number(ref.conversions||0)+1,lastConversionAt:new Date().toISOString()},SYSTEM,{id:ref.id,reason:`conversion:${order}`});const reward=Number(settings.referralOwnerRewardPoints||0);if(reward>0){let rows=await store.list('loyalty',{limit:1000});let owner=rows.find(r=>String(r.customerEmail||'').toLowerCase()===String(ref.ownerEmail||'').toLowerCase());if(!owner)owner=await store.save('loyalty',{customerEmail:ref.ownerEmail,balance:0,status:'active'},SYSTEM,{reason:'referral-loyalty-create'});const changed=actions.loyaltyAdjust(owner,reward,`Referido ${order}`);if(changed.ok)await store.save('loyalty',changed.record,SYSTEM,{id:owner.id,reason:`referral:${order}`});}}}await store.save('commerce-settings',{key:`settled:${order}`,status:'inactive',settledAt:new Date().toISOString()},SYSTEM,{id:`settled:${order}`,reason:'settlement-marker'});}
module.exports={reserveOrder,releaseReservations,commitReservations,quoteBenefits,commitBenefits};
