'use strict';
const CONTRACT_VERSION=1;
const REQUIRED_METHODS=Object.freeze(['get','set','setJSON','delete','list']);
function validateStore(store,{conditional=false}={}){if(!store||typeof store!=='object')return{ok:false,missing:[...REQUIRED_METHODS]};const required=conditional?[...REQUIRED_METHODS,'getWithMetadata']:REQUIRED_METHODS,missing=required.filter(name=>typeof store[name]!=='function');return{ok:missing.length===0,missing}}
function memoryStore(name){const root=globalThis.__NUTRETIUM_TEST_BLOBS__||(globalThis.__NUTRETIUM_TEST_BLOBS__=new Map());if(!root.has(name))root.set(name,new Map());const map=root.get(name),etags=globalThis.__NUTRETIUM_TEST_BLOB_ETAGS__||(globalThis.__NUTRETIUM_TEST_BLOB_ETAGS__=new Map());if(!etags.has(name))etags.set(name,new Map());const tagMap=etags.get(name),tag=key=>tagMap.get(String(key))||null,bump=key=>{const next=`\"mem-${Date.now()}-${Math.random().toString(36).slice(2)}\"`;tagMap.set(String(key),next);return next};function canWrite(key,opts={}){const k=String(key),exists=map.has(k),current=tag(k);if(opts.onlyIfNew===true&&exists)return false;if(opts.onlyIfMatch!==undefined&&opts.onlyIfMatch!==null){if(!exists||current!==opts.onlyIfMatch)return false}return true}return{async get(key,opts={}){const v=map.get(String(key));if(v===undefined)return null;if(opts.type==='json')return JSON.parse(JSON.stringify(v));return typeof v==='string'?v:JSON.stringify(v)},async getWithMetadata(key,opts={}){const k=String(key);if(!map.has(k))return null;const v=map.get(k),etag=tag(k),data=opts.etag&&opts.etag===etag?null:(opts.type==='json'?JSON.parse(JSON.stringify(v)):(typeof v==='string'?v:JSON.stringify(v)));return{data,etag,metadata:{}}},async setJSON(key,value,opts={}){const k=String(key);if(!canWrite(k,opts))return{modified:false};map.set(k,JSON.parse(JSON.stringify(value)));return{modified:true,etag:bump(k)}},async set(key,value,opts={}){const k=String(key);if(!canWrite(k,opts))return{modified:false};map.set(k,value);return{modified:true,etag:bump(k)}},async delete(key){const k=String(key);map.delete(k);tagMap.delete(k)},async list(opts={}){const prefix=String(opts.prefix||'');return{blobs:[...map.keys()].filter(key=>String(key).startsWith(prefix)).map(key=>({key,etag:tag(key)}))}}}}
function netlifyStore(name){try{const{getStore}=require('@netlify/blobs'),siteID=process.env.SITE_ID,token=process.env.NETLIFY_API_TOKEN;if(siteID&&token)return getStore({name,siteID,token});return getStore(name)}catch{return null}}
function selectedProvider(env=process.env){return String(env.NUTRETIUM_STORAGE_PROVIDER||'netlify-blobs').trim().toLowerCase()||'netlify-blobs'}
function status(env=process.env){const provider=selectedProvider(env),supported=provider==='netlify-blobs';return{contractVersion:CONTRACT_VERSION,provider,supported,primary:supported?provider:null,testMemory:env.NUTRETIUM_TEST_MEMORY_BLOBS==='true',migrationReady:supported,sqlAdapterReady:false}}
// El almacén en memoria es solo para pruebas. Dentro de una función desplegada
// (AWS Lambda siempre define AWS_LAMBDA_FUNCTION_NAME) se ignora aunque alguien
// ponga la variable en el sitio: si no, los pedidos vivirían en memoria y se
// perderían al reciclarse la función.
function memoriaDePruebas(env=process.env){return env.NUTRETIUM_TEST_MEMORY_BLOBS==='true'&&!env.AWS_LAMBDA_FUNCTION_NAME}
function getBlobStore(name){if(memoriaDePruebas())return memoryStore(name);if(selectedProvider()!=='netlify-blobs')return null;const store=netlifyStore(name);return validateStore(store).ok?store:null}
async function blobStoreReady(name='system-health-probe'){const store=getBlobStore(name);if(!store||typeof store.list!=='function')return false;try{const page=await store.list({paginate:false});return Boolean(page&&Array.isArray(page.blobs))}catch{return false}}
module.exports={memoriaDePruebas,CONTRACT_VERSION,REQUIRED_METHODS,validateStore,memoryStore,getBlobStore,blobStoreReady,selectedProvider,status};
