'use strict';
const crypto=require('crypto');
const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function decodeBase32(input){const clean=String(input||'').toUpperCase().replace(/[^A-Z2-7]/g,'');let bits='';for(const c of clean){const v=ALPHABET.indexOf(c);if(v<0)throw new Error('Secret TOTP no válido');bits+=v.toString(2).padStart(5,'0')}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}
function encodeBase32(buffer){let bits='';for(const byte of Buffer.from(buffer||[]))bits+=byte.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5){const chunk=bits.slice(i,i+5).padEnd(5,'0');out+=ALPHABET[parseInt(chunk,2)]}return out}
function generateSecret(bytes=20){return encodeBase32(crypto.randomBytes(Math.max(16,Number(bytes)||20)))}
function code(secret,time=Date.now(),step=30,digits=6){const counter=Math.floor(time/1000/step),buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',decodeBase32(secret)).update(buf).digest(),offset=h[h.length-1]&15,value=((h[offset]&127)<<24)|(h[offset+1]<<16)|(h[offset+2]<<8)|h[offset+3];return String(value%(10**digits)).padStart(digits,'0')}
function verify(secret,input,time=Date.now()){const given=String(input||'').replace(/\s/g,'');if(!/^\d{6}$/.test(given))return false;for(const drift of[-30000,0,30000]){const expected=code(secret,time+drift),a=Buffer.from(given),b=Buffer.from(expected);if(a.length===b.length&&crypto.timingSafeEqual(a,b))return true}return false}
function secrets(){try{const parsed=JSON.parse(process.env.STAFF_TOTP_SECRETS||'{}');return parsed&&typeof parsed==='object'?parsed:{}}catch{return{}}}
function encryptionKey(){const master=String(process.env.MFA_ENCRYPTION_KEY||process.env.JWT_SECRET||'');if(!master)throw new Error('No hay clave de cifrado MFA configurada');return crypto.createHash('sha256').update(`nutretium-mfa-v1\0${master}`).digest()}
function sealSecret(secret){const clean=String(secret||'').trim();if(!clean)throw new Error('Secret MFA vacío');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv),ciphertext=Buffer.concat([cipher.update(clean,'utf8'),cipher.final()]),tag=cipher.getAuthTag();return['v1',iv.toString('base64url'),tag.toString('base64url'),ciphertext.toString('base64url')].join('.')}
function openSecret(value){const raw=String(value||'');if(!raw)return'';const parts=raw.split('.');if(parts.length!==4||parts[0]!=='v1')throw new Error('Secret MFA cifrado no válido');const decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(parts[1],'base64url'));decipher.setAuthTag(Buffer.from(parts[2],'base64url'));return Buffer.concat([decipher.update(Buffer.from(parts[3],'base64url')),decipher.final()]).toString('utf8')}
function envSecretFor(email){const map=secrets(),key=Object.keys(map).find(k=>k.toLowerCase()===String(email||'').toLowerCase());return key?String(map[key]||''):''}
function secretFor(email,user=null){if(user?.mfaSecretEncrypted){try{return openSecret(user.mfaSecretEncrypted)}catch{return''}}return envSecretFor(email)}
function provisioningUri(email,secret){const account=String(email||'').trim().toLowerCase(),issuer='Nutretium';const label=encodeURIComponent(`${issuer}:${account}`);return `otpauth://totp/${label}?secret=${encodeURIComponent(String(secret||''))}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`}
module.exports={decodeBase32,encodeBase32,generateSecret,code,verify,secretFor,envSecretFor,sealSecret,openSecret,provisioningUri};
